### ISSUE TITLE
Implement friendlier zsh and fish prompts in default install.

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/Pengwin#132]
We may need to include friendlier default zsh and fish prompts.

![capture](https://user-images.githubusercontent.com/33820650/47397728-9da9fa80-d6fe-11e8-86b0-e68c904f2a6b.PNG)

**Comment by kbrock84** [comment]
Maybe create a simple wlinux theme without icons for each and install it during the zsh and fish install scripts.

Either that or find one for each without icons and install that.

The icons show up nicely once you switch to something other than cmd.exe (hyper in my case)

**Comment by Bodup** [comment]
zsh doesn't work at all for me. Any command results in a permission denied

**Comment by kbrock84** [comment]
@Bodup I believe that would be a separate issue. I recommend using the Bug Report template in the [Issue Templates](https://github.com/WhitewaterFoundry/WLinux/issues/new/choose). I didn't see an issue for this when i searched.

**Comment by patrick330602** [comment]
Alternatively, we can provide installation for [nerd fonts](https://github.com/ryanoasis/nerd-fonts) from `wlinux-setup` or as @kbrock84 says, provide a theme without icon. However, this means we shouldn't use the default installation scripts for oh-my-zsh or oh-my-fish, we need a manual installation for Oh My Fish. [oh my zsh](https://github.com/robbyrussell/oh-my-zsh#manual-installation) have a manual way of installing which could be helpful.

**Comment by kbrock84** [comment]
I love the nerd font idea if you can get it to work. I've struggled with this from the Linux side. Unless you're using X you will need to install them on windows as well so it can be used in whatever terminal emulator. At that point it's up to the user to select it.

**Comment by kbrock84** [comment]
Also see [Microsoft/WSL/issues/1288](https://github.com/Microsoft/WSL/issues/1288#issuecomment-391141361)

**Comment by fonnesbeck** [comment]
Any headway on this? I assume most folks just use bash.

**Comment by crramirez** [comment]
Fix: https://github.com/WhitewaterFoundry/pengwin-setup/pull/175

The problem happens when oh-my-zsh or oh-my-fish are installed. Their default theme uses special characters. To fix that an easy solution is to use another theme. I found that bira looks good and doesn't use special characters, at least in my tests. 

To fix:

Fish: 

`omf install bira`

Zsh: 

`sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="bira"/' "${HOME}/.zshrc"`

Regards
