### ISSUE TITLE
Give users option of pyenv to install python

### ISSUE THREAD

**Issue by khuongduybui** [WhitewaterFoundry/Pengwin#155]
Similar to how we are using `nodejs-n` and `rbenv`, using `pyenv` to install python allows installing and managing different python versions easily.

**Comment by sirredbeard** [comment]
Managing python and various versions has been a nightmare.

**Comment by khuongduybui** [comment]
Are you saying we shouldn't use `pyenv` to discourage the practice of installing and managing different python versions?

**Comment by sirredbeard** [comment]
No, just that I wish a simple solution existed. I am more than willing 
to consider pyenv, I have not yet.

**Comment by khuongduybui** [comment]
I gave it a test today, seems to work fine

```
sudo apt -t testing install -y \
git-core wget curl build-essential software-properties-common xz-utils \
libbz2-dev libffi-dev liblzma-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libssl1.0-dev llvm tk-dev zlib1g-dev
curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
~/.pyenv/bin/pyenv install 3.7.1
~/.pyenv/bin/pyenv global 3.7.1
```

Then I successfully installed

```
~/.pyenv/bin/pyenv install 3.5.6
~/.pyenv/bin/pyenv install 3.4.9
~/.pyenv/bin/pyenv install 3.3.7
~/.pyenv/bin/pyenv install 3.2.6
~/.pyenv/bin/pyenv install 3.1.5
~/.pyenv/bin/pyenv install 2.7.15
~/.pyenv/bin/pyenv install 2.6.9
~/.pyenv/bin/pyenv install 2.5.6
~/.pyenv/bin/pyenv install 2.4.6
```

**Comment by DarthSpock** [comment]
Wouldn't a better solution be using Anaconda? It does the work for you for managing different python environments.

**Comment by khuongduybui** [comment]
does Anaconda let me install 4 separate versions of Python 3 and 2 versions of Python 2?
Their site doesn't seem to make that info easy to find: https://www.anaconda.com/download/

**Comment by DarthSpock** [comment]
Yes. That is just the page to download from. You can download it through apt. Here's the link to the [set-up guide](https://docs.anaconda.com/anaconda/user-guide/getting-started/#open-nav-lin):  Ignore using Spyder IDE, VS Code is far superior and even has a link for using it on the bottom of the page.

**Comment by khuongduybui** [comment]
that's not exactly what I particularly look for, but if WLinux would like to ship Anaconda by default I won't object

**Comment by ThatWeirdAndrew** [comment]
Maybe we should give the user the option and link to a page describing the differences between the two so they can choose the best one for them.

**Comment by sirredbeard** [comment]
We are looking at this as part of a new approach to managing dev environments.

**Comment by cicorias** [comment]
Anaconda, even MiniConda, while I like them, is a heavyweight implementation. PyEnv seems more Linux friendly and so far we've had greater flexibility and fewer headaches.

**Comment by patrick330602** [comment]
An implementation of pyenv is now under testing

**Comment by sirredbeard** [comment]
Issue in -development branch implementation, see https://gist.github.com/sirredbeard/38a9c3ebfd08214f3f3ff37a45be2fef

```
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/WhitewaterFoundryLtd.Co.16571368D6CFF_1.2.3.0_x64__fbkee70p8a0b6:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Docker/Docker/Resources/bin:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/:/mnt/c/Users/Hayden/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Hayden/AppData/Local/GitHubDesktop/bin:/mnt/c/Users/Hayden/.dotnet/tools:/mnt/c/Users/Hayden/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/Hayden/AppData/Local/Microsoft/WindowsApps
```

**Comment by grufwub** [comment]
Working fix + possible explanation here: https://github.com/WhitewaterFoundry/pengwin-setup/pull/151
