### ISSUE TITLE
Add Xrdp server setup option to wlinux-setup

### ISSUE THREAD

**Issue by itadder** [WhitewaterFoundry/Pengwin#19]
Would it be possible to use xrdp?

**Comment by int19h** [comment]
It is definitely possible to use Xrdp in WSL; the only trick is to pick a server port different from the one that WIndows itself uses.

I think this is about having it out of the box, or easily configured. It might be a nice way to provide X access to people who want to experiment with the distro without having to pay for X410, or setting up Xming etc.

**Comment by itadder** [comment]
Yes it was just a way to make it easy to provide desktop easily.

**Comment by AceHack** [comment]
I tried the commands above and all I get is a blue/green screen after I login to XOrg with RDP on 3390.  I've never used xrdp so not sure what to expect.

**Comment by int19h** [comment]
A blank blue/green screen sounds like you get the default twm X session with no apps in it, probably because the only thing you have there is X itself (which was brought in as a dependency of Xrdp). Try installing some WM or DE, e.g. `apt install xfce4`.

**Comment by AceHack** [comment]
Thank you, I just ran that and installed xfce4 but I still get the same result just a blue/green screen nothing else.  Do I need to start xfce4 or something?  Thanks.

**Comment by davidfi01** [comment]
I recently used Hyper-V to install Ubuntu 19.04. MSFT has a script that installs and activates xrdp upon launch of the Ubuntu gui (gnome).  Here is a link:
https://github.com/Microsoft/linux-vm-tools/wiki/Onboarding:-Ubuntu

This might be a good way to provide a high fidelity desktop with Pengwin.
