### ISSUE TITLE
WLinux VC++ Redistributable dependencies packages not described (proposal for docs fix included)

### ISSUE THREAD

**Issue by n3rd4i** [WhitewaterFoundry/Pengwin#205]
**Describe the bug**
There is not clear description of the dependency packages in Windows in order to run WLinux.

**To Reproduce**
1. **WLinux must be installed and possible to run** as a prerequisite to this guide.
1. **Warning** This guide **will remove all** the existing Visual Studio packages (if any installed) leaving the current build set-up in non-working building environment.
1. Install Visual Studio Community [(bare-minimum)](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=15)
1. In **Visual Studio Installer**, install **only** Visual Studio core editor (if not installed already)
1. **Requirement**: remove **ALL** the other packages (if they exist)
1. Proving that other distro do not have this dependencies
1. Install **Debian** WSL app from Store
2. Run Debian application 
3. Installation and Debian successfully and works as expected.
4. Try to run **WLinux** distribution now
4. WLinux distribution fails to start with the error message:
	```
	---------------------------
	wlinux.exe - System Error
	---------------------------
	The code execution cannot proceed because VCRUNTIME140D.dll was not found. Reinstalling the program may fix this problem. 
	---------------------------
	OK   
	---------------------------
	```
1. After **trial & error** I've found that the following packages are expected to be installed:
	```
	Windows Universal CRT SDK
	VC++ 2017 version 15.9 v14.16 latest v141 tools
	Visual C++ 2017 Redistributable Update
	```
13. Open **Visual Studio Installer** and install them.
14. Optionally the following package could be installed: 
	```
	VC++ 2017 version 15.9 v14.16 Libs for Spectre (x86 and x64)
	```

**Expected behavior**
Documentation of this distro should explicitly say the minimum dependencies in order for this distro to work. This is important if one has limited disk space available and wants only the minimum packages.

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here: N/A

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: **1.1.22.0**

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
```
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.18282 N/A Build 18282
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO*
```

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment]
Is #206 sufficient?

**Comment by n3rd4i** [comment]
The solution provided could be considered a good workaround but be aware that this regards "Usage" and not Building.
If one wants to Build the project in Visual Studio if you have only IDE installed the required packages "for Build" are provided as recommended for this project.

In short I would suggest of adding to the Main readme OR better some new Usage readme?

**Comment by sirredbeard** [comment]
Ah, I see, I misunderstood.

**Comment by sirredbeard** [comment]
Could you submit a PR of your proposed changes?

**Comment by n3rd4i** [comment]
Trying to push new feature branch for adding new INSTALLATION.md file.
```
ERROR: Permission to WhitewaterFoundry/WLinux.git denied to n3rd4i.
```

**Comment by crramirez** [comment]
Create a fork, push there and create a pull request

**Comment by n3rd4i** [comment]
will close this
