### ISSUE TITLE
[Feature] WLinux icon in explorer integration

### ISSUE THREAD

**Issue by n3rd4i** [WhitewaterFoundry/Pengwin#241]
**Is your feature request related to a problem? Please describe.**

I would like to see in the Explorer integration, context menu, not only the WLinux option entry with `Open ith Wlinux` but also a [tiny] WLinux logo:

![image](https://user-images.githubusercontent.com/7346660/49327455-464f4380-f562-11e8-8211-30f02697dd6b.png)

**Describe the solution you'd like**
1. The registry entry used for the Explorer integration could also contain the address of the icon.
	- Computer\HKEY_CLASSES_ROOT\Directory\Background\shell\WLinux
	- Computer\HKEY_CLASSES_ROOT\Directory\shell\VSCode

	Path for the icon:
	`%ProgramFiles%\WindowsApps\WhitewaterFoundryLtd.Co.16571368D6CFF_{RELEASE_VERSION}_x64__w5sbsrqw3hh4p\wlinux.exe`

1. Also a key shortcut for the entry could be used, E.g.:

	`Open with &WLinux` instead of `Open with WLinux` in registry entry name.

**Describe alternatives you've considered**

One could manually to this by directly modifying the Windows Registry entry where WLinux command entry exists.

**Additional context**

The problem that I've found is that the icon location change with the new versions of the distro installation. For example, current path is: `%ProgramFiles%\WindowsApps\WhitewaterFoundryLtd.Co.16571368D6CFF_1.1.25.0_x64__w5sbsrqw3hh4p\wlinux.exe`.
Beacuse of this `{RELEASE_VERSION}` should be scripted somehow when the Explorer Integration takes place.

**Comment by sirredbeard** [comment]
Good idea. We will take a look into this. @patrick330602 leads up this feature and is taking a bit of a break for exams currently.

**Comment by sirredbeard** [comment]
I think this will require bundling the .ico in Linux space in distro image build.

**Comment by n3rd4i** [comment]
> I think this will require bundling the .ico in Linux space in distro image build.

Since this is a "Windows feature", you need that in "Windows space", I was using the .ICO built already embedded in the .EXE. Pointing to the .EXE gives you the first ICO from **bundled exe resources**.

Of course one could chose different one, if they exist with adding the index number, e.g. for **index 1**:
``` cmd
%ProgramFiles%\WindowsApps\WhitewaterFoundryLtd.Co.16571368D6CFF_1.1.25.0_x64__w5sbsrqw3hh4p\wlinux.exe, 1
```

**Comment by sirredbeard** [comment]
Moving to milestone 1.2 so .ico can be bundled in new .deb format.

.ico has been added to https://github.com/WhitewaterFoundry/wlinux-base
