### ISSUE TITLE
Give users the option to install NodeJS with nvm

### ISSUE THREAD

**Issue by SukkaW** [WhitewaterFoundry/Pengwin#270]
**Describe the solution you'd like**

I am always using nvm to manage NodeJS version and I have got used to it now. So I am wonder whether wlinux can give an option for install NodeJS using `nvm` besides `n` when run `wlinux-setup`.

**Describe alternatives you've considered**

I know I can simply choose not to install NodeJS and install `nvm` later, but I think add nvm to `wlinux setup` is not a bad idea.

**Comment by sirredbeard** [comment]
Can I ask why you prefer nvm over n?

**Comment by sirredbeard** [comment]
We are looking at a new method of managing multiple dev environments and versions.

We could look at including nvm in this too.

**Comment by grufwub** [comment]
I added support for this under my current virtual-lang-envs project :+1: we just need to figure out what's happening with this

**Comment by grufwub** [comment]
update on the situation, is in PR right now: https://github.com/WhitewaterFoundry/pengwin-setup/pull/188

**Comment by sirredbeard** [comment]
This is currently being tested in dev branch and works well. Expect to be pulled into master branch in next week or so.
