### ISSUE TITLE
Switch path written to installservice.bat (part of Cassandra implementation) from Linux format to Windows format

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/Pengwin#271]
The path to autorun.bat (that auto-runs Cassandra) in installservice.bat (what installs autorun.bat as a Windows service) needs to be in Windows format, not Linux format, because it is running in cmd.

At https://github.com/WhitewaterFoundry/WLinux/blob/master/linux_files/setup#L1013

**Comment by grufwub** [comment]
@patrick330602 do you have any plans to add WSLU support for Linux-->Windows path conversion? Otherwise, we can look into another fix.

**Comment by DarthSpock** [comment]
Any way to make them use Powershell instead (change .bat to .ps1)? Formatting wouldn't be an issue then since it's cross platform.

**Comment by sirredbeard** [comment]
I would be fine with .ps1 files.
