### ISSUE TITLE
Install Openstack CLI

### ISSUE THREAD

**Issue by fabiobo2005** [WhitewaterFoundry/Pengwin#317]
**Install Openstack CLI.**
I would like to suggest the setup of Openstack CLI (OCLI) using Wlinux-setup. Lots of cloud-admins uses Openstack now a days and it's CLI is a handy tool to manage private cloud & public cloud distributions.
More information about how to setup OCLI https://docs.openstack.org/newton/user-guide/common/cli-install-openstack-command-line-clients.html 

thanks,
Fabio Oliveira

**Comment by crramirez** [comment]
Hello,

Looks like it is a good idea. I would like to listen what other members think.

Regards

**Comment by DarthSpock** [comment]
This would be very useful in OpenStack environments.
