### ISSUE TITLE
Terraform Install

### ISSUE THREAD

**Issue by fabiobo2005** [WhitewaterFoundry/Pengwin#318]
**[Feature request] Terraform install**
Hi WLinux team! I would like to suggest the inclusion of Terraform to the wlinux-setup. Terrafom is a very handy tool form cloud admins and the ability to install it directly with wlinux-setup would be awesome.

thanks,
Fabiobo2005

**Comment by crramirez** [comment]
Hello,

This is a good idea. The last time I tested terraform in WSL it didn't work. Have you tested it installing manually?

Regards

**Comment by fabiobo2005** [comment]
Hi Carlos, thanks for reply!
I did the setup and it seems to work nice!
I follow the steps to do the setup:
1. Install unzip
`sudo apt-get install unzip`

2. Download latest version of the terraform
`wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip`

3. Extract the downloaded file archive
`unzip terraform_0.11.11_linux_amd64.zip`

4. Move the executable into a directory searched for executables
`sudo mv terraform /usr/local/bin/`

5. Run it
`terraform --version`

**Comment by crramirez** [comment]
Ok this is better than the results I had. Let's discuss about it. And as always if anyone thinks it is a good proposal, say it.

**Comment by AlexGitHubAcc** [comment]
Would be fantastic to have Terraform available out of the box.

**Comment by crramirez** [comment]
You will have it in release 1. 2
