### ISSUE TITLE
1.2: handle old 'open with wlinux' 

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/Pengwin#359]
we need to handle old 'open with wlinux' either when upgrading to pengwin or when re-installing explorer integration in pengwin

**Comment by sirredbeard** [comment]
I think we should create a function that erases both WLinux and Penguin references, always call it, and call it first thing.

If the user _isn't_ going to install integration, we already do a clean up and we now need to erase both WLinux and Pengwin, so that's not a big change.

If the user _is_ going to install integration, by doing this we go ahead and clean up any old WLinux references at the same time.

Around here https://github.com/WhitewaterFoundry/pengwin-setup/blob/9f1993fdd3dfd403bf241c9fba5abcfecb4135b8/pengwin-setup.d/explorer.sh#L9

**Comment by sirredbeard** [comment]
Any other ideas, @grufwub @crramirez @patrick330602?

**Comment by crramirez** [comment]
We can just delete the Open WLinux entry at startup for a while. But also we can place this code in the transition script setup and leave it there

**Comment by grufwub** [comment]
We can set up the transition script to look for existence of a registry entry, and if found then run the 'uninstall' section of explorer.sh, followed by the 'install' section? Or failing that just include the code itself in the transition script.

**Comment by crramirez** [comment]
Sounds good for me

**Comment by grufwub** [comment]
I've been doing some experimenting and if you run a registry key uninstall operation it provides no output as to whether anything was removed or not. And all my efforts using 'regedit /E' to export firstly don't work work, but even if they did it requires administrator privileges (and brings up a prompt asking).

I think the best solution might be to automatically attempt removal of the WLinux registry key, then make a whiptail prompt letting the user know that they'll need to reinstall pengwin explorer integration if if they previously had it installed
