### ISSUE TITLE
Missing OS release info for npm

### ISSUE THREAD

**Issue by kerbe** [WhitewaterFoundry/Pengwin#365]
**Describe the bug**
Apparently wlinux isn't giving enough release information, which is used in some npm automatic scripts. I have ran into this when trying to install mongodb-memory-server -package. It tries automatically download file from mongodb website, but automatic url generation doesn't work. I'm trying to figure out workaround or some fix in wlinux.

**To Reproduce**
1. Have npm installed.
2. Create new folder, for example: mkdir mongotest
3. cd mongotest && npm init -y
4. npm install mongodb mongodb-memory-server sinon jest --save-dev
3. git clone https://github.com/vladgolubev/jest-mongodb
4. cp jest-mongodb/setup.js .
5. cp jest-mongodb/jest.config.js .
6. cp jest-mongodb/mongo-environment.js .
7. cp jest-mongodb/teardown.js .
8. edit package.json and replace:
   "test": "echo \"Error: no test specified\" && exit 1"
with following:
   "test": "jest"
10. run: npm test
11. See error:
Error: Too small (243 bytes) mongod binary downloaded from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian-4.0.3.tgz

Correct urls would have -debian92- or -debian81- or similar identifier. List of correct packages can be found here:
https://www.mongodb.org/dl/linux

**Expected behavior**
Expected npm / jest to be able to identify proper release info, and download correct package.

**Additional context**
NPM package github page:
https://github.com/nodkz/mongodb-memory-server

Similar problem that has been with in mongodb-memory-server, which lead into figuring out this release info is missing:
https://github.com/nodkz/mongodb-memory-server/issues/131

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 1.1.28.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 1.0.21, 8.8.2017

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello,

Thanks for reporting we will check that

**Comment by sirredbeard** [comment]
I am not very familiar with npm. Which script is actually doing the distro detection/downloading? We can look there and see what it's checking. It's probably checking /etc/os-releases. It might be parsing the NAME tag instead of the ID tag.

**Comment by kerbe** [comment]
Unfortunately I'm not very familiar with npm either, just started to dive deeper there. This is how far I got myself with one afternoon googling and trying out, and decided I need to tap out for help. :D

**Comment by crramirez** [comment]
Replace: /usr/lib/os-release with:

```
PRETTY_NAME="Pengwin"
NAME="Pengwin"
VERSION_ID="10"
VERSION="10 (buster)"
ID=debian
ID_LIKE=debian
HOME_URL="https://github.com/whitewaterfoundry/Pengwin"
SUPPORT_URL="https://github.com/whitewaterfoundry/Pengwin"
BUG_REPORT_URL="https://github.com/whitewaterfoundry/Pengwin"
VERSION_CODENAME=buster
```
https://github.com/WhitewaterFoundry/pengwin-setup/pull/173

**Comment by kerbe** [comment]
Thank you @crramirez, that works. Had to work a bit with test case, as repo that I had used to form that had moved on.

**Comment by crramirez** [comment]
You are welcome
