### ISSUE TITLE
home backup did not work

### ISSUE THREAD

**Issue by paveldvorak5** [WhitewaterFoundry/Pengwin#372]
Upgraded to penguin today.
Run backup from penguin-setup
It could't create windows folder, backuped in some strange folder in ~
![image](https://user-images.githubusercontent.com/14863835/55280225-bdcf8c80-5322-11e9-9566-fde9735e3133.png)

**Comment by crramirez** [comment]
Hello,

Please give us more details. Try to fill the template for issues. Your screenshot suggests that you are using an insider version. Also I cannot identify what tool you are using.

Regards,
Carlos

**Comment by sirredbeard** [comment]
![IMG_0070](https://user-images.githubusercontent.com/33820650/55284491-d1401f00-5345-11e9-8d7f-5f0492da95ed.JPG)

**Comment by paveldvorak5** [comment]
my version is this:
bash <(curl -s https://raw.githubusercontent.com/WhitewaterFoundry/Pengwin/1.2/linux_files/setup)  

![image](https://user-images.githubusercontent.com/14863835/55280437-f1f87c80-5325-11e9-8437-07ec8fdb5ec6.png)

you can close this issue, my windows broke, I can't run WSL now. I will probably work fine on clean install

**Comment by crramirez** [comment]
Hello,

I was asking for your Windows version to try to reproduce it. 

Regards

**Comment by paveldvorak5** [comment]
![image](https://user-images.githubusercontent.com/14863835/55292139-43b50b80-53e7-11e9-9ed7-b0d42e8995f7.png)
I got some windows store troubles with this insider build so maybe the problem is there

**Comment by crramirez** [comment]
@paveldvorak5 Please test again, we made a fix for Windows Insiders and also it should work for regular ones

**Comment by paveldvorak5** [comment]
yes it works now
