### ISSUE TITLE
How to enble HIDPI support in WLinux?

### ISSUE THREAD

**Issue by jelipo** [WhitewaterFoundry/Pengwin#383]
![Snipaste_2019-04-05_03-05-39](https://user-images.githubusercontent.com/16136814/55581732-36ce4a00-5750-11e9-9c73-96e81ad1ca71.png)

I tried to run
```bash
export QT_SCALE_FACTOR=2
export GDK_SCALE=2
```
But it seems not work.

Windows10 1809
X410

**Comment by crramirez** [comment]
Hello

Check in X410 if you have the High DPI enabled. 

Regards

**Comment by springmarker** [comment]
@crramirez 
![Snipaste_2019-04-05_11-57-25](https://user-images.githubusercontent.com/16136814/55602872-407c9f80-579a-11e9-9f1d-200c80480006.png)

If I choose the "High Quality" option, the x410 simply enlarges the original image, which causes the display to be blurred.
![Snipaste_2019-04-05_12-05-32](https://user-images.githubusercontent.com/16136814/55603099-8d14aa80-579b-11e9-84e3-e796073a004d.png)

 I think the work of scaling should be done by WLinux/GNOME.

**Comment by crramirez** [comment]
Tomorrow I will try to reproduce the issue

**Comment by crramirez** [comment]
Hello,

I noticed that you are using CLion. This is a Java application that probably doesn't obey those env vars, To sure execute another one like terminator which is a GTK app. 

For a more smooth experience, I recommend to use the Windows version and compile your programs in WLinux. Check this: https://www.jetbrains.com/help/clion/how-to-use-wsl-development-environment-in-clion.html 

With the upcoming release 1.2 that we will expect to release today, a fully automated configuration is included for CLion and Visual Studio. It has support even to develop GTK graphical applications with the debugger.

Also, you can install this plugin for controlling the HighDPI inside the IDE: https://plugins.jetbrains.com/plugin/9541-hidpi-profiles

Regards
