### ISSUE TITLE
Unable to upgrade to Pengwin from wlinux

### ISSUE THREAD

**Issue by valorin** [WhitewaterFoundry/Pengwin#389]
**Describe the bug**
Unable to upgrade from wlinux to pengwin. I originally tried the `wlinux-setup` command, but it threw an error and `wlinux-setup` was removed without `pengwin-setup` being installed. I then tried manually running the setup, as per https://twitter.com/PengwinLinux/status/1115457997575196672, but it failed with the same error (below).

**To Reproduce**
1. Run `curl -s https://packagecloud.io/install/repositories/whitewaterfoundry/pengwin-setup/script.deb.sh | sudo bash`
2. Output displays error

**Expected behavior**
`pengwin-setup` should be installed and usable.

**Error logs**
```
valorin@gandalf:~$ curl -s https://packagecloud.io/install/repositories/whitewaterfoundry/pengwin-setup/script.deb.sh | sudo bash
Detected operating system as wlinux/stretch.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/whitewaterfoundry_pengwin-setup.list...curl: (22) The requested URL returned error: 404

Unable to download repo config from: https://packagecloud.io/install/repositories/whitewaterfoundry/pengwin-setup/config_file.list?os=wlinux&dist=stretch&source=script

This usually happens if your operating system is not supported by
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this.
```

**Additional context**
```
valorin@gandalf:~$ lsb_release -a
No LSB modules are available.
Distributor ID: WLinux
Description:    WLinux GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch
```

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

1.2.0.0

**Windows Build**

```
valorin@GANDALF C:\Users\valorin
$ systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO N1MET52W(1.37), 14/02/2019
```

**Comment by sirredbeard** [comment]
Yes, you are running an older version of WLinux, before we reverted the distribution identifier back to Debian for compatability purposes, and the Packagecloud install script is breaking.

Can you try curling the script to install pengwin-base a file and then running:

`$ os=debian dist=buster ./script.sh`

Installing pengwin-base should correct your /etc/os-releases file.

Pengwin-setup should then install normally.

Sorry for the hiccup.

**Comment by valorin** [comment]
Seems to be working now, thanks! 👍
