### ISSUE TITLE
Typo: pengwin-setup

### ISSUE THREAD

**Issue by AnTiZ** [WhitewaterFoundry/Pengwin#390]
**Describe the bug**
Spelling/Typo: "Enables varios services"

**To Reproduce**
1. Run pengwin-setup
2. Proceed to "Services Menu"

**Expected behavior**
"Enables **various** services"

**Screenshots**
n/a

**Additional context**
[Source line?](https://github.com/WhitewaterFoundry/pengwin-setup/blob/1d445d3d3514ad29f1fac076fb5844b2a4e9d2ff/pengwin-setup.d/services.sh#L101)

**Basic Troubleshooting Checklist**
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.

What other troubleshooting have you attempted?
n/a

**Pengwin Version**
1.2.0.0

**Windows Build**
n/a

**Comment by sirredbeard** [comment]
Thank you for the report.

Fixed in this commit. https://github.com/WhitewaterFoundry/pengwin-setup/commit/25e87ffe55210b999356e35ee87bc1db7f55e80c
