### ISSUE TITLE
nodejs and n issues on Machine with WLinux  already installed - when moved to Pengwin

### ISSUE THREAD

**Issue by cicorias** [WhitewaterFoundry/Pengwin#396]
An existing OS install of WLinux - when the store app was upgraded, during running of wlinux-setup, the Nodejs areas failed indicating existing bins, etc. 

Repro:
1. existing Wlinux
2. allow store to run upgrade
3. run wlinux-setup and choose nodejs parts.

Errors as below

![image](https://user-images.githubusercontent.com/1080406/55903252-3ba15c80-5b9b-11e9-85a5-abe197fa8d46.png)

I've tried reset of app, uninstall, reinstall and similar.

![image](https://user-images.githubusercontent.com/1080406/55903471-b9656800-5b9b-11e9-8047-d7a19ecc5dc8.png)

**Comment by sirredbeard** [comment]
Do you have Node installed on Windows too?

**Comment by cicorias** [comment]
I do have Node on windows but that's in \program files... 

As for is node in those paths - can you let me know where on the OS file system /rootfs is now? As it used to be under /packages/whitewater...../LocalState/rootfs   

I can look first and ensure.

The WLinux install from the store had lots of things. The store upgraded it to Pengwin.  Then I checked in the shell that i had nothing in my /home path in WSL/Pengwin.  There was nothing except basic .bashrc, etc.

I'll try another reset and run again.

**Comment by cicorias** [comment]
I'm going to close this as I cannot repro now. I did a reset and that removed all - i'll reopen if the setup fails.  I believe I was in a state of were some WLinux bits were crossing with pengwin bits. I see that the old /rootfs is now gone for me after a reboot. 

I'd suggest anyone else moving from WLinux with configuration things, etc. backup those configs, etc. then do a "reset" from the Apps & Settings UI in settings on Windows 10.

**Comment by cicorias** [comment]
Now end up with a different error. The nodejs/npm/n detection is finding the windows version. I see why you asked me before about if I had installed on windows.

I will bypass and use NVM for now in WSL.  But ideally, detection should only look in Linux land.

![image](https://user-images.githubusercontent.com/1080406/55918228-53d7a280-5bc0-11e9-97ac-b2b910c80343.png)
