### ISSUE TITLE
Lag when opening pengwin

### ISSUE THREAD

**Issue by cptsk1ttles** [WhitewaterFoundry/Pengwin#397]
**Describe the bug**
A long lag time exists when opening pengwin where one did no exist before the update to WLinux.

**To Reproduce**
1. Go to start
2. Click on pengwin
3. window will take approx 4s to open with the title "unpacking pengwin"

**Expected behavior**
Opening Penguin after the initial setup should open in approx 2s similar to the debian app from the windows store

**Screenshots**
![image](https://user-images.githubusercontent.com/11273611/55908197-aa77b900-5b8d-11e9-8fda-337329fa1e83.png)

**Additional context**

**Basic Troubleshooting Checklist**

[ x] I have searched Google for the error message.
[ x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ x] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ x] I have disabled and re-enabled WSL in Windows Features.
[ x] I have run Windows 10 updates and restarted.

Insert here:

**Pengwin Version**

1.2.1.0

Insert here:

**Windows Build**

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              HP Q85 Ver. 01.06.00, 1/3/2019

**Comment by sirredbeard** [comment]
Can you please try commenting out `create_winhome_link` in /etc/profile.d/00-pengwin.sh?

Have you configured sshd to run on startup or any other services with rc.local?

**Comment by cptsk1ttles** [comment]
@sirredbeard I commented out create_winhome_link in /etc/profile.d/00-pengwin.sh and the issue still persists. I do not have anything in rc.local and no other services starting on startup

**Comment by sirredbeard** [comment]
If it's not win_home_link, I wonder if it is a delay due to bash completion which also runs at startup, unlike Debian.

Can you try moving it's profile.d script?
```
sudo mv /etc/profile.d/bash_completion.sh ~
```

To restore:
```
sudo mv ~/bash_completion.sh /etc/profile.d/
```

I get roughly the same delay opening Pengwin and Debian on my machine. We have not heard from anyone else about a slow down but will leave this open to see if there are other reports.

**Comment by cptsk1ttles** [comment]
@sirredbeard removing the bash completion did not work either. I didn't test with WLinux just Pengwin. I'm not sure what's "unpacking". Maybe one of the utilities is causing the delay rvm or something so I'll do the reinstall and see.

**Comment by cptsk1ttles** [comment]
after reinstall but before I added ruby etc. the startup time is the same as the debian WSL.
