### ISSUE TITLE
Old WLinux shortcut on taskbar still appearing, unable to remove.

### ISSUE THREAD

**Issue by Sheerley** [WhitewaterFoundry/Pengwin#399]
**Describe the bug**
After update from ```WLinux``` to ```Pengwin``` old shortcut on taskbar disappeared, but continuosly appears on it. I am unable to unpin it.

**To Reproduce**
??? No idea how you can reproduce it...

**Expected behavior**
Clicking unpin - and removing old shortcut? 

**Screenshots**
![Image](https://i.ibb.co/0DJhWGJ/New-Bitmap-Image.png)

**Additional context**

**Basic Troubleshooting Checklist**
[ x ] I have searched Google for the error message.
[ x ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ x ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ x ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ x ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ x ] I have disabled and re-enabled WSL in Windows Features.
[ x ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?
Insert here:  Restarting PC and explorer, trying to remove it from registry and file system.

**Pengwin Version**
1.2.1.0

**Windows Build**
10.0.17763 N/A Build 17763

**Comment by sirredbeard** [comment]
It's a taskbar issue.

See https://github.com/WhitewaterFoundry/Pengwin/issues/392#issuecomment-481484042
