### ISSUE TITLE
Fix 'Open with Pengwin' failure on root drive

### ISSUE THREAD

**Issue by ogdenpm** [WhitewaterFoundry/Pengwin#401]
**Describe the bug**
See issue #282 for details

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Basic Troubleshooting Checklist**

[ ] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: 1.2.3.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment]
![IMG_0447](https://user-images.githubusercontent.com/33820650/55954971-245f7f00-5c2e-11e9-87f2-0ce1b1af18ad.JPG)

can reproduce

**Comment by sirredbeard** [comment]
Can you lend a hand with this, @patrick330602?

**Comment by grufwub** [comment]
Might have a fix to this here once we can confirm working: https://github.com/WhitewaterFoundry/pengwin-setup/pull/131

**Comment by crramirez** [comment]
Working
