### ISSUE TITLE
Vim keys behaving abnormally in ConEmu

### ISSUE THREAD

**Issue by holmesb** [WhitewaterFoundry/Pengwin#402]
Hi,

Pengwin's Bash experience is great, but I can't fix the Vim key mappings.  End and Del keys don't work properly.  According to the cat command, they are mapped as follows:
end: ^[[F
del: ^[[3

But with or without the following mapping in my .vimrc: `nmap <esc>OF $`, the end key does nothing.  Vim freezes for a few seconds, then nothing.  Home key works fine. The del key produces a tilde rather than deleting a character, but I've been focusing so far on fixing the end key.

My inputrc file has: `"\eoF": end-of-line`

Yes I know I can use $ instead of end, but I believe vim is a tool for using the keyboard to edit stuff.  I'm still using the keyboard this way and the end key is more in-keeping with every other text editor.

Vim seems sensitive to the `set term=<terminal string>` line in vimrc.  I've set this to `set term=ansi`.  Is this correct?

**Comment by crramirez** [comment]
Hello

You can try: set term=xterm

Regards

**Comment by holmesb** [comment]
Tried xterm.  Even worse.  Home key, arrow keys, and others also stop working.  Can someone post a .vimrc with functioning home, end, arrow and delete keys?

**Comment by crramirez** [comment]
I will try to reproduce your issue today. Meanwhile press $ instead of end and x instead of del.

**Comment by crramirez** [comment]
Hello,

I am sorry but I can't reproduce your issue. This is the .vimrc that I use but without it, everything works:

```
source /etc/vim/vimrc
syntax on
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type
set visualbell           " don't beep
set noerrorbells         " don't beep
```

Are you running Pengwin directly from the start menu? 

Also, make sure that this check is disabled when you open the properties of the console:

![image](https://user-images.githubusercontent.com/8397379/55976754-c8f3b800-5c52-11e9-9665-d25d6310d2c9.png)

For alternative console I would recommend: 

https://github.com/mintty/wsltty/releases/tag/1.9.6

This has full xterm and WSL support

Regards

**Comment by holmesb** [comment]
I'm using Pengwin in ConEmu terminal, but same occurred when launching directly from the start menu.  Anyway I have fixed.  I don't know what exactly was causing, but I emptied /etc/vim/vimrc and now all keys work as expected.  Many thanks.

**Comment by holmesb** [comment]
I spoke too soon, is only working fine when launching directly from the start menu,  Conemu still has the problems I originally described above.  My conemu task uses command:
```
set "PATH=C:\Program Files\WindowsApps\WhitewaterFoundryLtd.Co.16571368D6CFF_1.2.3.0_x64__kd1vv0z0vy70w:%PATH%" & "C:\Program Files\WindowsApps\WhitewaterFoundryLtd.Co.16571368D6CFF_1.2.3.0_x64__kd1vv0z0vy70w\Pengwin.exe"
```
Is this correct?  Can you simulate this?

**Comment by crramirez** [comment]
Ok, this will take time, but I will test and tell you the results.

**Comment by holmesb** [comment]
Hi @crramirez were you able to reproduce this?

**Comment by crramirez** [comment]
Hello,

Sorry for the delay. I configured correctly ConEmu following the instructions from here: https://conemu.github.io/en/BashOnWindows.html

Be sure you have the latest version of ConEmu. Then import the config file for pengwin:

![image](https://user-images.githubusercontent.com/8397379/56381666-28b20c00-61db-11e9-8546-a79626a3149d.png)

In the import settings dialog, paste:

https://raw.githubusercontent.com/crramirez/WLinux/crramirez/ftr/conemu/ConEmuPengwin.xml

And click Open:

![image](https://user-images.githubusercontent.com/8397379/56381812-79c20000-61db-11e9-8c55-64f5d6a10f4d.png)

The click Save settings.

Close and open ConEmu. It should be running normally, with the pengwin icon in the tab.

Regards

**Comment by holmesb** [comment]
Thanks but after restarting and launching Pengwin in Conemu, I get error:
```wslbridge error: failed to start backend process
note: bash.exe output: Error: 0x80070002
ConEmuC: Root process was alive less than 10 sec, ExitCode=0.
Press Enter or Esc to close console...
```
Still works fine when launching pengwin.exe directly from the start menu.  Here are the imported settings:
![image](https://user-images.githubusercontent.com/5072156/56383598-1f906180-6212-11e9-8258-4de4dcf88f95.png)

**Comment by crramirez** [comment]
Ok delete this: 

`--distro-guid={4e8492ab-8920-49f4-a02d-4dd413253607} `

Or import the xml again I fixed it there

**Comment by holmesb** [comment]
You beaut!  Thanks @crramirez, you've unleashed the mighty Pengwin for me :-)
