### ISSUE TITLE
Unable to install Powershell (failed dependencies)

### ISSUE THREAD

**Issue by thalamus** [WhitewaterFoundry/Pengwin#405]
Unable to install powershell on a fresh 1.2.3 install. Failed dependencies of libssl1.0.2 and libicu57.

1. Install latest version of Pengwin from Microsoft Store
2. Launch pengwin-setup
3. Select install powershell
4. Install fails with unmet dependency errors

**Expected behavior**
Powershell should be installed, all dependencies should be met.

**Additional context**

The reason why it fails is because debian unstable provides libssl1.1, and libicu63, and libssl1.0.2 and libicu57 are not available.

To resolve this issue, I have had to create a new file /etc/apt/sources.list.d/stable-repos.list and put the stable repos into it, which provides the missing libraries and resolves the issue.

**Basic Troubleshooting Checklist**

[y] I have searched Google for the error message.
[n/a] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[n/a] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[y] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[n/a] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[n/a] I have disabled and re-enabled WSL in Windows Features.
[n/a] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

See resolution above.

**Pengwin Version**
1.2.3.0

**Windows Build**
18362.53

**Comment by crramirez** [comment]
We will check this.

Thanks for reporting

**Comment by sirredbeard** [comment]
Can reproduce. 
![Capture2](https://user-images.githubusercontent.com/33820650/56061667-16962080-5d38-11e9-99fc-023b54e3d418.PNG)

**Comment by sirredbeard** [comment]
Proposed patch: https://github.com/WhitewaterFoundry/pengwin-setup/pull/126
