### ISSUE TITLE
Enlarge programming menu

### ISSUE THREAD

**Issue by PhMajerus** [WhitewaterFoundry/Pengwin#410]
There is a small UI issue in pengwin-setup, the text-based GUI uses a character that typically isn't available in the Windows console.

A glyph used in the vertical scrollbar in pengwin-setup menus isn't available in Consolas, which is the default font for the Windows console, and so the [?] replacement character is shown instead.
This can be seen in menu lists that require vertical scrolling, such as the Programming Menu.

Tested on Pengwin 1.2.3.0 running on Windows 10 version 1903 build 18362.53.

![Pengwin setup glyph issue](https://user-images.githubusercontent.com/25664275/56086634-40943380-5e5b-11e9-93ad-dacf947f9605.png)

**Comment by crramirez** [comment]
Worse you shouldn't see the scroll bar. We will check

**Comment by sirredbeard** [comment]
https://github.com/WhitewaterFoundry/pengwin-setup/pull/127
