### ISSUE TITLE
Run bashrc or .profile upon launch with explorer integration

### ISSUE THREAD

**Issue by astrelsky** [WhitewaterFoundry/Pengwin#413]
It would be helpful to have the bashrc or .profile scripts run upon launch when using the 'open with Pengwin' option. This is helpful so that custom environment variables are set such as PATH extensions.

**Comment by crramirez** [comment]
Yes sure we will fix this.

**Comment by grufwub** [comment]
Currently working on this here: https://github.com/WhitewaterFoundry/pengwin-setup/pull/131
