### ISSUE TITLE
Errors shown on launch after fresh install

### ISSUE THREAD

**Issue by andrewsil1** [WhitewaterFoundry/Pengwin#417]
I purchased Pengwin from the MS Store and launched it.  Every launch brings up the following errors immediately:

"wslpath: R:\: No such file or directory"
"ln: failed to create symbolic link '/home/andrewsi/winhome' -> '': No such file or directory"

I have checked that /home/andrewsi was created, but I'm not quite sure what the system is attempting to do here at launch.  There is no R:\ on this machine so I don't know why it's looking for it in the first place.

**Expected behavior**
Sessions launch without errors.

**Basic Troubleshooting Checklist**

[ x] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[X ] I have disabled and re-enabled WSL in Windows Features.
[X ] I have run Windows 10 updates and restarted.

**Pengwin Version**

Insert here: 1.2.3.0

**Windows Build**
10.0.17763

**Comment by crramirez** [comment]
Thanks for reporting we will fix that

**Comment by andrewsil1** [comment]
It returns "R:\"  which seems to be the source of the problem.  However, I honestly have no idea where it's getting that idea from.

**Comment by crramirez** [comment]
And this?: 

`cmd.exe /c 'echo %HOMEDRIVE%%HOMEPATH%'`

The command invocation is different.

I can fix it so it doesn't show the error but I want to dig the error cause.

**Comment by andrewsil1** [comment]
That also returns R:\

**Comment by crramirez** [comment]
I am completely lost. This command should return where your home folder is in Windows. Like:

C:\Users\ _youruser_

**Comment by andrewsil1** [comment]
I agree with you completely! But I do not know why we're getting what we're getting.  However, I'm opening an ordinary cmd.exe window and getting the same result, so it seems like something about this machine's environment is strangely horked rather than it being a WSL or Pengwin problem.  I'll investigate further at my end.

**Comment by andrewsil1** [comment]
I found some registry settings that were redirecting these two environment variables on my machine (why, I still have no clue) but I've fixed them up and the errors go away - this was clearly NOT Pengwin's problem so I am closing the issue. Sorry that it was Pengwin that exposed it to me for the first time...

**Comment by crramirez** [comment]
I am happy you could solve the problem. Now you have a symbolic link to your windows home called: winhome. Test it:

`cd ~/winhome`

Also an environment var:

`echo $WIN_HOME`

**Comment by nyouna** [comment]
I have the same issue with the latest of Pengwin.
My home drive is set to U: (domain admin decision) and I am getting issues that are not reproduced with other distributions:

1. after a fresh install each time I open pengwin I am getting the error:
"ln: failed to create symbolic link '/home/yyona/winhome' -> '': No such file or directory"

until I created manually the symbolic link to my windows home:
"ln -s /mnt/c/Users/myUsername ~/winhome"


2. each time I open pengwin, it wrotes before the bash prompt a line with :
"wslpath: U:\"

echo %HOMEDRIVE% -> U:
