### ISSUE TITLE
Add unzip to AWS CLI tool installer

### ISSUE THREAD

**Issue by jwalsh2NU** [WhitewaterFoundry/Pengwin#419]
**Describe the bug**
running pengwin-setup fails to install awscli and terraform

**To Reproduce**

Output:

Selected: TOOLS
TOOLS
CLOUDCLI
Selected: AWS
Installing AWS CLI...
Python 3.7.3rc1
Saving current directory as $CURDIR
Going to $TMPDIR: /tmp/tmp.9rxhzkuGQr
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/jwalsh2/.wget-hsts'. HSTS will be disabled.
--2019-04-16 13:24:59--  https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.131.109
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.131.109|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11612915 (11M) [application/zip]
Saving to: ‘awscli-bundle.zip’

awscli-bundle.zip             100%[=================================================>]  11.07M  2.31MB/s    in 4.8s

2019-04-16 13:25:04 (2.32 MB/s) - ‘awscli-bundle.zip’ saved [11612915/11612915]

/usr/local/pengwin-setup.d/cloudcli.sh: line 43: unzip: command not found
python3: can't open file 'awscli-bundle/install': [Errno 2] No such file or directory
Installing bash-completion

RESOLUTION:

sudo apt install unzip

re run pengwin-setup, awscli installs

unzip should be added to base image if it is used by pengwin-setup

**Comment by crramirez** [comment]
We will fix that. Thank you for reporting

**Comment by sirredbeard** [comment]
Fix PR https://github.com/WhitewaterFoundry/pengwin-setup/pull/129/files
