### ISSUE TITLE
"Reset" of Pengwin causes it to disappear from launch menu, errors during reinstall

### ISSUE THREAD

**Issue by andrewsil1** [WhitewaterFoundry/Pengwin#420]
**Describe the bug**
In attempting to troubleshoot a different problem, I took the template suggestion of using "Reset" from Windows 10's Apps control panel for the Pengwin "app."  The reset seemed to fail at some point, claiming that I didn't have permissions to run the pengwin.exe that was installed to WindowsApps.  Pengwin is gone from the start menu, and attempting to reinstall from the store tries but fails three times (downloads, then gets to "Installing...", reports an error and retries) and produces error 0x80073CF6 in the store.  Since it's gone, I can't uninstall it and now I'm stuck.

**To Reproduce**
Repro steps are above.

**Expected behavior**
Reset process should have completed successfully and left the Pengwin environment in a clean state.

**Pengwin Version**
Latest from MS Store

Insert here:
Windows 10 17763

**Comment by andrewsil1** [comment]
Ability to reinstall was cleared up after a reboot.

**Comment by crramirez** [comment]
To explain a bit. The problem is that after you close pengwin, the init process keeps running to keep services. To correctly reset it you first need to end the init process.
