### ISSUE TITLE
Issues with WSL path

### ISSUE THREAD

**Issue by deanhtid** [WhitewaterFoundry/Pengwin#421]
**Describe the bug**
Everything seemed to install fine but I'm getting errors with wsl path and symbolic links. The reason i bought pengwin win the first place is to stop me getting path issues with windows.

**To Reproduce**
1. install pengwin
2. close terminal
3. open pengwin

**Expected behavior**
zsh prompt with no issues. VS code also not working but probably linked to this issuec

**Screenshots**
![Capture](https://user-images.githubusercontent.com/10110324/56302778-5bec9080-6132-11e9-8fa9-7b0386156d0c.PNG)

**Basic Troubleshooting Checklist**

[x ] I have searched Google for the error message.
[x ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[x ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[x ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: cant find version but its the latest. just downloaded today 

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO N1QET79W (1.54 ), 16/11/2018

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment]
wslpath is not supported on 16299.

**Comment by crramirez** [comment]
Please upgrade your Windows version to at least 1803. If it is not possible I can send you instructions to disable the error messages. But many Pengwin functionalities are based on wslpath and won't work in your current Windows version.

**Comment by deanhtid** [comment]
Hi, I have updated windows and now no errors. However, I can't get VScode to open. Any ideas? Thanks

**Comment by deanhtid** [comment]
Do I need to buy x410 for it to work?

**Comment by deanhtid** [comment]
Yeah, so I pretty much answered my own question and installed x410. Now working. Thanks
