### ISSUE TITLE
The scale of the screen is increased by executing vscode.

### ISSUE THREAD

**Issue by KenMal** [WhitewaterFoundry/Pengwin#426]
pengwin Ver. 1.2.3.0

Running vscode will make the screen bigger and occupy the display.
The same goes for other X applications as well.
X uses X410.

We performed reinstallation etc.
It was not big at the first start.
It becomes bigger after the second time.

I do not know how to deal with it.

![Display](https://user-images.githubusercontent.com/49750266/56352435-392dab00-620a-11e9-9a15-750796a9e29d.jpg)

**Comment by DistractionRectangle** [comment]
If you don't know if you enabled hidpi scaling, run
`ls /etc/profile.d/`
and check the output for 'hidpi.sh'
If your issue does not involve hidpi scaling, then the following doesn't apply.

Assuming you configured hidpi in pengwin-setup, you need to rescale text, as explained [here](https://wiki.archlinux.org/index.php/HiDPI#GDK_3_(GTK+_3)).

To apply and test this in pengwin, run
`export GDK_DPI_SCALE=0.5 && code`
If you don't like how it looks, close vscode and rerun the above with a different value for GDK_DPI_SCALE
Tweak GDK_DPI_SCALE as need until you like how it looks, personally, 0.6 looks best on my machine.

To finalize your setting
` sudo bash -c "echo \"export GDK_DPI_SCALE=${GDK_DPI_SCALE}\" >> /etc/profile.d/hidpi.sh"`

**Comment by KenMal** [comment]
There was no setting of 'export GDK_DPI_SCALE = 0.5' in 'hidpi.sh'.
I added the settings, restarted pengwin and started 'code' and it was displayed correctly.

Thank you very much.
