### ISSUE TITLE
Recommendation for lightweight desktop environment

### ISSUE THREAD

**Issue by ghost** [WhitewaterFoundry/Pengwin#427]
I'd like a lightweight desktop environment compatible with the theme I have selected in lxappearance.

I'm rather new to Linux overall so a list of commands for installation and starting a recommended desktop environment would be appreciated.

EDIT: I have X410 already installed and running in the background.

**Comment by crramirez** [comment]
I have used lxde but not to have a full desktop environment but to have an start menu for graphic applications. There are people here who use KDE let's wait them answer.

Regards

**Comment by sirredbeard** [comment]
The lightweight desktop environment most compatible with the theme selected in lxappearance would be lxde. 

Here is a guide for installing lxde on Debian-based distros: https://wiki.debian.org/LXDE#Installation

Make sure you use `sudo` before `apt-get...` in Pengwin.

You will want X410 set to 'Full Desktop', right-click on it and change to that setting.

To start lxde:

`$ startlxde`

As an alternative to running an entire second desktop in a window, you could set X410 to Windows Apps, and start just the individual components of the desktop environment you like, such a customized lxpanel. That way you can integrate it more into your existing Windows desktop.

**Comment by Aidolii** [comment]
Would you consider adding these as options in pengwin-setup?

Like, an option for installing a desktop GUI, and it asks if you just want enough components for a panel, or if you want everything for a second desktop.

**Comment by sirredbeard** [comment]
Yes, we certainly will.
