### ISSUE TITLE
Reset how?

### ISSUE THREAD

**Issue by alanfluff** [WhitewaterFoundry/Pengwin#431]
Hi, The Googles tell me:

> ...useful for when resetting Pengwin...

all over the place, but I cannot find the actual command(s) I need to carry out to reset.

Please can you point me to a doc that covers this (and the command to use the home folder backup before the reset)?

Thanks v.m : )

**Comment by crramirez** [comment]
Hello, 

Look for Pengwin in the start menu. Right-click and choose More->App Settings. There you will find a Reset button.

Before resetting make sure you finish the process called init in the task manager, to avoid problems. 

Regards

**Comment by alanfluff** [comment]
Thank you @crramirez : )

**Comment by crramirez** [comment]
Hello, 

Now re-reading your question, you asked where the home backup is located. Just in case it is in the maintenance section of pengwin-setup.

Regards
