### ISSUE TITLE
AMD ROCm stack installation

### ISSUE THREAD

**Issue by iamkucuk** [WhitewaterFoundry/Pengwin#433]
This is a both question and a feature request so please excuse me pointing this one in the issues section.

What is ROCm stack of AMD?
ROCm stack is a kernel stack for using high computational powers of AMD GPUs for intensive calculations that are intended to be calculated on GPUs. It provides (and enables) a solution for AMD users that are not able to use Nvidia's propriety CUDA. 

The problem with ROCm stack:
The main problem with that stack is it provides a FULL KERNEL solution. It requires a linux kernel to run on and modify. 

What you can do?
Microsoft WSL might provide a brilliant solution for AMD users to migrate on Windows from Linux. However, it's a quite painful problem to install ROCm stack on anywhere besides Ubuntu and CentOs relatives. Despite Ubuntu on WSL is provided by Windows, I had no luck with installing ROCm stack on Ubuntu. 

So my question is: Can I install ROCm stack if I buy Pengwin? Or have you got any future plans to provide AMD ROCm support in your system?

Regards.

**Comment by crramirez** [comment]
Hello,

Here is the answer: https://github.com/RadeonOpenCompute/Experimental_ROC/issues/13

Pengwin as all WSL distributions use the Microsoft Kernel. In Pengwin we provide a better WSL experience, but at the kernel level, we have all the same limitations. 

Regards,
Carlos
