### ISSUE TITLE
node and other various packages not working 

### ISSUE THREAD

**Issue by deanhtid** [WhitewaterFoundry/Pengwin#435]
**Describe the bug**
I use pengwin to install node and python etc and i also allow it to install zsh and oh-my-zsh. Whenever i try to npm install anything it says zsh: command not found: npm

How do i get this working? I'm pretty sure its installed. It also doesnt pick up python or anything

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

Cant run this either due to zsh

**Comment by crramirez** [comment]
Let's try to reproduce your issue and give you choices.

**Comment by deanhtid** [comment]
so i open up pengwin
i try to npm install something and i get:

 zsh: command not found: npm

i try to do systeminfo | findstr /C:"OS"

zsh: command not found: systeminfo
zsh: command not found: findstr

**Comment by deanhtid** [comment]
its like zsh is not picking up anything i have installed?

**Comment by deanhtid** [comment]
Tried adding 

source /home/YOUUSERNAME/.bash_profile at the beginning of ~/.zshrc

But also didnt work

**Comment by crramirez** [comment]
OK,

From zsh, delete your previous node installation:

`rm -rf $HOME/n`

And run pengwin-setup again from zsh. Install nodejs in the same way you did before. It will be configured correctly with zsh.

Regards

**Comment by deanhtid** [comment]
Hi so that did the job but i have other issues with npm installing stuff globally. For example, I have installed eslint globally but I get the same error zsh: command not found: eslint
