### ISSUE TITLE
Quick Access Reset

### ISSUE THREAD

**Issue by laurinkeithdavis** [WhitewaterFoundry/Pengwin#439]
Installing Pengwin or some part of that process caused by Quick Access links to be completely reset. 

Before installation:

![image](https://user-images.githubusercontent.com/75857/56751430-ae8a0600-674b-11e9-8f5e-ef7a16248c8d.png)

After installation:

![image](https://user-images.githubusercontent.com/75857/56751447-b5b11400-674b-11e9-8428-2e893b94d8e1.png)

Windows 10 Pro x64 1809

**Comment by sirredbeard** [comment]
That is bizarre. We don't do anything that should affect Quick access. I will leave this open in case we get any other reports.
