### ISSUE TITLE
symbolic link not working as expected

### ISSUE THREAD

**Issue by deanhtid** [WhitewaterFoundry/Pengwin#443]
**Describe the bug**
after installing pengwin a symbolic link is created to winhome. Within winhome i created a dir called projects. Within wsl i have files within that project, but its empty on windows. Any ideas?

**Comment by patrick330602** [comment]
Can you show the output of `ls -l ~/winhome`? Have tested on my machine and it works
![image](https://user-images.githubusercontent.com/15316889/56819991-6d920e80-687d-11e9-8416-7cde393d2be5.png)

**Comment by deanhtid** [comment]
![Annotation 2019-04-29 083651](https://user-images.githubusercontent.com/10110324/56881956-fcf41900-6a59-11e9-9569-ba3aa655bafe.jpg)

So i created files within the terminal but not showing up in windows

**Comment by deanhtid** [comment]
Actually please ignore this. Weirdly the files are there now. I'll close the issue. thanks
