### ISSUE TITLE
Mounting AppImages

### ISSUE THREAD

**Issue by ghost** [WhitewaterFoundry/Pengwin#445]
I tried to mount an AppImage and it wouldn't let me, it said I should try the `modprobe fuse` command. That gave me this error:
```
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-18362-Microsoft/modules.dep.bin'
modprobe: FATAL: Module fuse not found in directory /lib/modules/4.4.0-18362-Microsoft
```

I saw in #274 that FUSE was not yet supported in WSL.

Is this still the case in WSL from build 1903? (I updated early using Insider's Release Preview channel, which is the lowest tier that is even more stable than the Slow ring.) I'm guessing yes but I just want to make sure before looking into an alternate way of executing this AppImage. If there's no way to get FUSE working, I would love advice on what to do with this instead.

Also, it's not a big deal since I found a solution thanks to your help, but I never got a follow-up reply on #429. Thank you for all your support.

**Comment by crramirez** [comment]
Hello

I haven't seen FUSE in the WSL roadmap for the near future. Definitely, for Windows 1903, it won't be included. And we don't have any near plans.

About the other solution, you found for LXDE sure we will include it when we create the desktop environment installer in pengwin-setup

Regards

**Comment by Aidolii** [comment]
This question was asked before the WSL2 announcement, so new readers of this issue should take note: WSL2 will have FUSE mounts and Pengwin will be offering a WSL2-based distribution as noted in #458

**Comment by sirredbeard** [comment]
WSL2 is going to be awesome. Closing this for now.
