### ISSUE TITLE
Hang without Error Code on launch

### ISSUE THREAD

**Issue by bushidocodes** [WhitewaterFoundry/Pengwin#446]
Pengwin is sporatically hanging on launch. The only feedback is that the Window name changes from "Loading Pengwin" to "Select Loading Pengwin" when I double click on the window pane. Sporadically, this resolves my restarting my system. Seems like this is a WSL issue, but I'm not sure how to determine this.

These WSL error messages occur from time to time and can tricky to troubleshoot short of reinstalling WSL.

They are usually not an issue with Pengwin itself but a glitch with the underlying Windows Subsystem for Linux in Windows 10.

You can help us help you and Microsoft improve WSL and address these if you can provide us some debugging information.

[X] I have read the above statement.

**Basic Troubleshooting**

Please check:

[X] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched Google for the error message.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted to date?

**Error Code**

No error. Just hangs

**Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here:

![image](https://user-images.githubusercontent.com/8700322/56870172-6aac3080-69d9-11e9-9057-e4300f5b1092.png)

If I double click, changes to this:
![image](https://user-images.githubusercontent.com/8700322/56870206-fc1ba280-69d9-11e9-97f2-6d21a385c6ad.png)

Insert here:

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro                                                                                                                                                                                          OS Version:                10.0.18362 N/A Build 18362                                                                                                                                                                                        OS Manufacturer:           Microsoft Corporation                                                                                                                                                                                             OS Configuration:          Standalone Workstation                                                                                                                                                                                            OS Build Type:             Multiprocessor Free                                                                                                                                                                                               BIOS Version:              American Megatrends Inc. F12, 5/15/2014                    

                                                                                                                                                       
For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**WSL Debug Data**

Please collect and attach .etl files by following this guide: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#starting-bash-gives-an-error-code

**Comment by bushidocodes** [comment]
It seems that `wslconfig /l` also is hanging, which further suggests WSL.

**Comment by sirredbeard** [comment]
I would recommend disable and then re-enabling WSL.

**Comment by bushidocodes** [comment]
My semester finally ended, so I had a bit of bandwidth to clean up my environments. Things seem to be working now (and an issue I filed in the WSL repo about Explorer integration not working is fixed too). You can feel free to close this issue. Also, have a wonderful weekend!
