### ISSUE TITLE
Cannot install openjdk-8-jre and openjdk-8-jdk

### ISSUE THREAD

**Issue by sida-khalibre** [WhitewaterFoundry/Pengwin#448]
**Describe the bug**
Try to install openjdk-8-jre & openjdk-8-jdk both from pengwin-setup and apt command get the same error:

$ apt-get install openjdk-8-jre openjdk-8-jdk -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package openjdk-8-jre
E: Unable to locate package openjdk-8-jdk

**To Reproduce**
1. run apt-get install openjdk-8-jre openjdk-8-jdk

**Expected behavior**
openjdk-8-jre and openjdk-8-jdk package should be successfully installed 

**Additional context**

**Basic Troubleshooting Checklist**

[*] I have searched Google for the error message.
[*] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[*] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[*] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[*] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[*] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:
Try to use stretch backport still not help

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here:
1.2.3.0
**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Version: 10.0.17763 N/A Build 17763
For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by grufwub** [comment]
Hi I'm sorry to hear you're having this issue! This is a problem that we do need to address, in that we need to update our install script to install a later version of the JDK and JRE. 

However, version 8 can no longer be found in the repositories as Oracle removed support for it earlier this year for those not paying for a commercial license, as it has reached 'End of Public Updates' status. So repository `default-jdk` and `default-jre` packages now point directly to openjdk-11.

I'll work on a fix for this, this morning, but in the meantime if you're happy to use the current supported release version then:
`sudo apt-get install default-jre default-jdk`
should serve you just fine 😊

**Comment by hkumard** [comment]
Thanks @grufwub

**Comment by cracker458** [comment]
nice..

**Comment by crramirez** [comment]
The recommended way to install Java in pengwin is via SDKMan using pengwin setup:

`pengwin-setup install PROGRAMMING JAVA`

**Comment by Kodwings22** [comment]
I keep reading a lot of posts when I first get into trouble. This is how I once reached this website (https://kodlogs.net/341/c-signed-unsigned-mismatch) and got the desired solution. You can read this post as well as visit here. I think it will be very useful for you

**Comment by Kodwings22** [comment]
I keep reading a lot of posts when I first get into trouble. This is how I once reached this website (https://kodlogs.net/340/unable-to-locate-package-openjdk-8-jre) and got the desired solution. You can read this post as well as visit here. I think it will be very useful for you
