### ISSUE TITLE
Add pip to python3 in Pengwin-Setup

### ISSUE THREAD

**Issue by WSLUser** [WhitewaterFoundry/Pengwin#452]
**Is your feature request related to a problem? Please describe.**
I'm unable to install packages with pip without first installing pip.
**Describe the solution you'd like**
Pengwin-Setup already includes python and recent pyenv so having pip installed by default when python3 is installed would make a more complete experience. Within that, I would recommend installing pytest and pylint at bare minimum with pip.
**Describe alternatives you've considered**
Install pip manually by doing `apt install python3-pip`
**Additional context**
Was setting up VS Code installed with pengwin setup with the python extension and offered to install pylint and pytest but couldn't because pip wasn't installed. 

Also get this warning when VS Code installs pip packages, this is just installing pylint:

`The script isort is installed in '/home/wsluser/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts epylint, pylint, pyreverse and symilar are installed in '/home/wsluser/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.`

So that home user bin path should be added to PATH after installing pip as well.

Update: Using the new dev version of pengwin-setup to set up pyenv as well it appears export PATH="/home/wsluser/.pyenv/bin:$PATH" needs to be added to the setup script as well.

**Comment by sirredbeard** [comment]
We are still ironing out pyenv issues and will then take a look at installing pip as well.

**Comment by ThatWeirdAndrew** [comment]
pengwin-setup should already install pip

**Comment by WSLUser** [comment]
Well it doesn't. I tried using pip from the terminal as well. I installed with command shown in OP. Which proves it's not included.

**Comment by grufwub** [comment]
Have you tried using `pip3` ?

**Comment by WSLUser** [comment]
Yes. Installing python doesn't by default install pip. You need get-pip.py and python executes it. Most distros make it easily available through their package manager.

**Comment by WSLUser** [comment]
I think this has been addressed by now. So closing the issue.

**Comment by jonycastagna** [comment]
No it's not. And in general is rude to close the issue without verifying it...

**Comment by WSLUser** [comment]
I verified using my own installation. With the addition of the virtualenv, pip was included.

**Comment by jonycastagna** [comment]
The point is to have it without the addition of virtualenv, but by default

**Comment by sirredbeard** [comment]
The default image is getting big as it is, not sure I want to ship all of a python. And then we get into debates about which one. I think allowing users to easily install the python they need using pengwin-setup is probably the best solution. Part of the reason we created pengwin-setup was because we had so many requests for this or that in the base.
