### ISSUE TITLE
Run as root error message when building create-tar-x64

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/Pengwin#453]
I get the following non-fatal error when building the x64 image, even when when a non-root user.
 
![Annotation 2019-05-04 095234](https://user-images.githubusercontent.com/33820650/57180063-d74c8280-6e52-11e9-8bcd-2355e2e51577.jpg)

**Comment by grufwub** [comment]
Can you reproduce this issue then print your PATH? This is how that login-shell PATH fix I submitted was presenting, so it'd be interesting to see what your PATH is at this point.
