### ISSUE TITLE
Docker Bridge broken in build 745 of pengwin-setup

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/Pengwin#454]
Steps to reproduce:

1. Install Pengwin from store
2. run sudo apt-get update; sudo apt-get upgrade -y to update to latest pengwin-setup
3. Run Docker bridge creation routine
4. Close and re-open Pengwin
5. Get message below:

```
docker pull debian:latest
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by sirredbeard** [comment]
The current workaround is to install Docker bridge with the store version of pengwin-setup first, then upgrade pengwin-setup to install whatever else you need.

**Comment by sirredbeard** [comment]
I nuked build 745 from the repo until we worked this one out.

**Comment by Aidolii** [comment]
Is there any ETA on this?

**Comment by crramirez** [comment]
Yes check: https://github.com/WhitewaterFoundry/pengwin-setup/pull/153

Regards

**Comment by Aidolii** [comment]
Well, it sounds like the fix is working, hope to see it go live soon!

**Comment by Aidolii** [comment]
I'm a little concerned at how long this is taking. Usually in development when a critical bug is discovered that causes the update to get pulled, a fix for it is deployed as soon as possible.

**Comment by bushidocodes** [comment]
We're still waiting for this, right? I see the fix is merged into develop in pengwin-setup, but it appears not to have been released yet.

**Comment by crramirez** [comment]
Hello,

The change is now on master. Remember to run the docker installation again to apply the patch. 

Regards
