### ISSUE TITLE
Plans for WSL2?

### ISSUE THREAD

**Issue by ghost** [WhitewaterFoundry/Pengwin#458]
As you're probably already aware, Microsoft recently announced WSL2 and plans to start having Insiders test it in June. Supposedly WSL1 and WSL2 run independent from one another.

https://news.softpedia.com/news/microsoft-announces-windows-subsystem-for-linux-2-525917.shtml
https://news.softpedia.com/news/microsoft-brings-a-full-linux-kernel-to-windows-10-525918.shtml

Will Pengwin be making the jump to WSL2, or will it remain WSL1?

**Comment by crramirez** [comment]
Hello,

Pengwin will support both WSL versions. 

Regards

**Comment by Biswa96** [comment]
> Pengwin will support both WSL versions.

We should say "Microsoft" will support both versions 😁
