### ISSUE TITLE
not technically a Pengwin bug, but am running VS Code under Pengwin and am getting errors trying to install support for Python

### ISSUE THREAD

**Issue by wwvierg** [WhitewaterFoundry/Pengwin#460]
I'm using Visual Studio Code 1.33.1, running in Windows Subsystem for Linux (WSL)SL, and when i try Customize by installing support for Python, i get an error.

The message reads: "An unknown errror occurred. Please consult the log for more detials".

I don't know which log, or where it is, that this message mentions.

Can anyone help? - Thanks.

Note: i have reviewed the different suggestions presented as i tried to ask this question, but none were specific to Visual studio code.

Pengwin Version:
1.2.4.0

Windows Build:
10.0.17763 N/A Build 17763

**Comment by crramirez** [comment]
Hello,

I have seen that others have problems installing plugins in VS code. Try running VS Code from / instead your home directory and try again to install the plugin.

Regards

**Comment by sirredbeard** [comment]
Extensions have never worked great in Code on WSL. We've opened a couple issues on Code before about this. I think that's in part why they brought out the new Remote WSL extension.

**Comment by wwvierg** [comment]
hi Hayden:

thanks for the reply - as always.

Carlos Ramirez had replied the same.

and then last night, back at the house, i reinstalled VS Code, via Pengwin-Setup, b/c i noted v1.4 had just come out, and that install suggested removing it from WSL, installing the Windows version, and then use the extension.

i couldn’t figure out how to simply uninstall VS Code from WSL, however (again, being a WSL newbie —- maybe put uninstall capabilities in Setup?) . . . so uninstalled Pengwin from Windows Settings/Apps . . . and started over.

if you get chance to check out my direct e-mail to you, re. using the UltraEdit editor, would very much appreciate your thoughts.

10-4 for now,

thanks.


--------------------------------------------------------------
William W. Viergever
Viergever & Associates
Health Data Analysis / Systems Design & Development
2920 Arden Way Suite N<x-apple-data-detectors://6/1>
Sacramento, CA 95825<x-apple-data-detectors://6/1>
william@viergever.net<mailto:william@viergever.net>
www.viergever.net<http://www.viergever.net/>
 (916) 483-8398<tel:(916)%20483-8398>
--------------------------------------------------------------

On May 17, 2019, at 9:05 AM, Hayden <notifications@github.com<mailto:notifications@github.com>> wrote:


Extensions have never worked great in Code on WSL. We've opened a couple issues on Code before about this. I think that's in part why they brought out the new Remote WSL extension.

**Comment by Biswa96** [comment]
Which extension do you want to install in VSCode?

**Comment by wwvierg** [comment]
hi Biswapriyo:

thanks for getting back to me.

i was trying to do the Python extension – shown on the initial splash-screen (under Customize / Tools and Languages).

note, however, i had noticed a new (1.34.0) version had come out that very day, and when i installed that (under Pengwin) it actually said to uninstall, install under Windows, and use the WSL extension . . . so i went that route.

appreciate all you guys’ replies.




--------------------------------------------------------------
William W. Viergever
Viergever & Associates
Health Data Analysis / Systems Design & Development
2920 Arden Way Suite N
Sacramento, CA 95825
william@viergever.net<mailto:william@viergever.net>
www.viergever.net<http://www.viergever.net/>
 (916) 483-8398
--------------------------------------------------------------

**Comment by bushidocodes** [comment]
I personally decided to dump the x version of Code for the native Windows Insiders build with the remote WSL extension as well. I suspect this is going to be a better developer experience going forward, but it's nice to know the X infrastructure is in place in case I need to use other GUI tools.
