### ISSUE TITLE
want to install my own editor but it has Ubuntu 18.04+ and Ubuntu 16.04+ version

### ISSUE THREAD

**Issue by wwvierg** [WhitewaterFoundry/Pengwin#462]
the editor is UltraEdit (i've used this under Windows for years) and want to try in under Pengwin (and X410). you can see it here:

http://www.ultraedit.com/downloads/uex.html

any advice on which version i should try?

i have Googled everywhere but can't seem to find which Debian verion Pengwin is based on, hence my asking for help here.

![ue_linux](https://user-images.githubusercontent.com/46386818/57955805-ab49ec00-78ab-11e9-9fff-1f289d8f8001.png)

thanks

**Comment by crramirez** [comment]
Try the 18.04 one

**Comment by wwvierg** [comment]
awesome; appreciate the *real* quick reply.

just installed neovim and was about to start it’s tutorial . . .

and i was having flashbacks to the early 70s at UCSB where we used WYLBUR (not TSO) and RJE to run SAS jobs on an Amdahl mainframe running 360/MVT

not all flashbacks are good  ;>)

thanks again


--------------------------------------------------------------
William W. Viergever
Viergever & Associates
Health Data Analysis / Systems Design & Development
2920 Arden Way Suite N
Sacramento, CA 95825
william@viergever.net<mailto:william@viergever.net>
www.viergever.net<http://www.viergever.net/>
 (916) 483-8398
--------------------------------------------------------------

**Comment by wwvierg** [comment]
hi Carlos:

me again.

I downloaded  the 18.04 version to (Windows) c:\uex and whilst in Pengwin, cd’d to /mnt/c/uex where I could see the DEB file.

From there I ran sudo dpkg -I uex_18.00.0.40_amd64.deb and it ran fine but said it couldn’t configure as I was missing some stuff.

So I then ran sudo apt install -f . . . and everything finished.

But I did a ls -a and couldn’t see anything other than the DEB file. i tried “uex” and it said unknown bash command.

then i cd’d back to rootfs area and couldn’t see anything uex there either

Finally, back where the DEB file is, I ran dpkg –contents uex_18.00.0.40_amd64.deb and got a listing of where everything (supposedly) was installed.

See PNG pic.

But as before – couldn’t find anything.

So . . . with fingers crossed . . . am hoping you may have some ideas???

As always – thanks!


--------------------------------------------------------------
William W. Viergever
Viergever & Associates
Health Data Analysis / Systems Design & Development
2920 Arden Way Suite N
Sacramento, CA 95825
william@viergever.net<mailto:william@viergever.net>
www.viergever.net<http://www.viergever.net/>
 (916) 483-8398
--------------------------------------------------------------

**Comment by wwvierg** [comment]
![2019-05-17_15-20-23](https://user-images.githubusercontent.com/46386818/57962040-17d2e400-78c8-11e9-8f2d-63604a46e127.png)
