### ISSUE TITLE
yarn installation does not pass `-y` to apt-get

### ISSUE THREAD

**Issue by cspotcode** [WhitewaterFoundry/Pengwin#465]
**Is your feature request related to a problem? Please describe.**

When pengwin-setup installs yarn, it doesn't pass the `-y` flag to apt-get so I have to manually confirm.

**Describe the solution you'd like**

apt-get does not show a prompt when installing yarn, since I've already confirmed via the whiptail menus.

**Comment by ThatWeirdAndrew** [comment]
I pushed a fix. Hopefully it gets added soon.
