### ISSUE TITLE
mongoDb install issue!!

### ISSUE THREAD

**Issue by delcata** [WhitewaterFoundry/Pengwin#469]
please, I have an issue when I try to install MongoDB like on Debian or Ubuntu, I have this error message :
The following packages have unmet dependencies:
 mongodb : Depends: mongodb-dev but it is not going to be installed
           Depends: mongodb-server (>= 1:2.4.1-2) but it is not going to be installed

**Comment by crramirez** [comment]
Hello, 

We will reproduce the issue later today and give you the command to use.

Regards

**Comment by delcata** [comment]
Great thanks

**Comment by crramirez** [comment]
Hello @delcata,

I installed it in Pengwin without problems. Please be sure that you execute:

`sudo apt update && sudo apt install mongodb`

If the problem persists please run the command bellow and send me the result:

`sudo apt-cache madison mongodb mongodb-dev mongodb-server`

Regards

**Comment by delcata** [comment]
-thanks, your command works for me, but it installs MongoDB v3.4.18, not 3.6 or 4.0 , and after that when i try to start the DB the server is shutting down with code:100 (directory /data/db not found), so for resolving that temporary, I create that directory on my root (cd ~) then for starting the server i use this command : sudo mongod --dbpath ~/data/db.

**Comment by crramirez** [comment]
Ok, I will check that

**Comment by crramirez** [comment]
Hello,

I have installed correctly mongodb version 3.4. I didn't found any issues with the data directory. I also saw this on their web page:

![image](https://user-images.githubusercontent.com/8397379/59162200-5cc7f000-8aed-11e9-96c9-5a652272aa58.png)

So I recommend you to stick with the Debian provided version and to upgrade Windows to 1809.

When I tried to install a newer version I found that Debian 10 is not still supported for MongoDB newer versions. There is a solution which involves compiling and installing Mongo DB from the source. You can try it, I did it but my SSD became full. https://github.com/patrikx3/docker-debian-testing-mongodb-stable 

I recommend that if you want a stable and reliable solution for Mongo DB 4.0 to use Docker: https://hub.docker.com/_/mongo. You can also wait for Debian 10 support.

Regards

**Comment by delcata** [comment]
Hello, 
I think i wil wait for debian 10 support , i’m using Windows 10 build 1903, and for the db directory i have the same problem , after installing MongoDB 3.4.1 i can’t start the server  because data/db not found so  i make a dir in m y root to resolve that, then i got another issue  the MongoDB.conf can’t update the new path , for resolving that i start the server by this command : 
sudo mongod --dbpath ~/data/db , after that it works
Provenance : Courrier pour Windows 10

De : Carlos Rafael Ramirez
Envoyé le :dimanche 9 juin 2019 17:37
À : WhitewaterFoundry/Pengwin
Cc : delcata; Mention
Objet :Re: [WhitewaterFoundry/Pengwin] mongoDb install issue!! (#469)

Hello,
I have installed correctly mongodb version 3.4. I didn't found any issues with the data directory. I also saw this on their web page:

So I recommend you to stick with the Debian provided version and to upgrade Windows to 1809.
When I tried to install a newer version I found that Debian 10 is not still supported for MongoDB newer versions. There is a solution which involves compiling and installing Mongo DB from the source. You can try it, I did it but my SSD became full. https://github.com/patrikx3/docker-debian-testing-mongodb-stable
I recommend that if you want a stable and reliable solution for Mongo DB 4.0 to use Docker: https://hub.docker.com/_/mongo. You can also wait for Debian 10 support.
Regards
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by crramirez** [comment]
Finally, mongo team released MongoDB for Debian 10.

Here the steps to install it in Pengwin:

```bash
echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main" | sudo tee /etc/apt/sources.list.d/mongodb-org.list
wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
sudo apt update
sudo apt-get install -y mongodb-org
sudo -u mongodb /usr/bin/mongod  --config /etc/mongod.conf &
```
