### ISSUE TITLE
Npm init problem

### ISSUE THREAD

**Issue by delcata** [WhitewaterFoundry/Pengwin#470]
Hello,
I need help, i have an issue after installing npm via pengwin-setup ,when i try to npm init a new project , i got permission denied error (code - 13 error to open mypath/package.json) and when i use sudo npm init i got another error (sudo npm command not found).

The first thing i did after installing this distro from store is:
1- installing zsh and oh-my-zsh via pengwin-setup.
2- configuring my .zshrc file (changing theme, adding aliases)
3 - installing n, node and npm via pengwin-setup.
4 - checking there versions .
5 - creating my folder project on winhome/Documents/myProjet.
And then i got those issues.

**Comment by crramirez** [comment]
Hello,

1. Issue a `cat ~/.zshrc` then copy the last line you see it says something about N_PREFIX. 
2. The run `sudo -s`
3. Execute the line that you have copied. This will add npm to the path
4. Execute `npm init`.

You shouldn't require root for this, there is something with the permissions in your directory, but sometimes nom requires root to install packages.

Regards

**Comment by delcata** [comment]
The same problem_
![Issue_part_1](https://user-images.githubusercontent.com/28787067/58966119-3af30400-87a1-11e9-8509-5dbc79a4cbe2.png)
![Issue_part_2](https://user-images.githubusercontent.com/28787067/58966138-40e8e500-87a1-11e9-9379-a66b157a236e.png)
![Issue_part_3](https://user-images.githubusercontent.com/28787067/58966147-45150280-87a1-11e9-99a7-aa7d1b8b8e74.png)

**Comment by crramirez** [comment]
Hello,

After the sudo -s and issuing the export go to your dir and run npm init, do not close the Pengwin window.

I recommend you check your permission in Windows, I don't believe that a sudo will help you in this case.

Regards

**Comment by delcata** [comment]
I have the same problem again, my permissions in windows are normal, I did the same thing on my ubuntu distro and  everything works well:
![Issue_part_4](https://user-images.githubusercontent.com/28787067/58977967-5d454b80-87ba-11e9-95d6-cd7eb8794097.png)

**Comment by sirredbeard** [comment]
Are you able to reproduce the bug in zsh on Ubuntu?

To me that looks like bash in your Ubuntu screenshot.

**Comment by delcata** [comment]
I'm not using zsh on my ubuntu, but after resetting my pengwin distro without zsh, I have the same problems on bash, I think the problem comes with the n, node,npm install on pengwin-setup, because my node install on ubuntu is done from curl

**Comment by sirredbeard** [comment]
Can you reset Pengwin and install the latest updates we just pushed about 20 minutes ago? A handful of patches for npm just went into production.

**Comment by delcata** [comment]
ok great, I will do it

**Comment by delcata** [comment]
again,
![issue_part6](https://user-images.githubusercontent.com/28787067/58981944-f2e4d900-87c2-11e9-9da2-767daf9508c7.png)
![issue_part5](https://user-images.githubusercontent.com/28787067/58981957-fa0be700-87c2-11e9-8a2f-4886965f3573.png)

**Comment by crramirez** [comment]
@delcata run `sudo npm` as follows:

`sudo env PATH="$PATH" npm` meanwhile we will find the way to automate this.

**Comment by delcata** [comment]
Thanks i will check that !

**Comment by delcata** [comment]
Great your command "sudo env PATH="$PATH" npm init --y" works for me without problem

**Comment by crramirez** [comment]
Great! I added a more generic way in pengwin-setup: https://github.com/WhitewaterFoundry/pengwin-setup/pull/169

**Comment by delcata** [comment]
ok thanks for help
