### ISSUE TITLE
Add option to pengwin-setup to convert between WSL1 and WSL2

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/Pengwin#472]
It's possible this could be done inside Pengwin, we don't know yet.

We do know converting to DrvFS inside a WSL distro causes issues.

We may need to write an external batch file and then call it using CMD.

**Comment by sirredbeard** [comment]
Also consider adding an option to enable WSL2, which will generate a .PS script on the user's Desktop they need to run outside of WSL and reboot.

**Comment by Biswa96** [comment]
I think this should go into WSL-DistroLauncher repository, from which Pengwin was forked.

**Comment by sirredbeard** [comment]
There's really no practical way to do this in WSL-DistroLauncher.

Sit tight though.

**Comment by sirredbeard** [comment]
We have something in the pipeline to address this.
