### ISSUE TITLE
Pengwin Assigned to Port 2222

### ISSUE THREAD

**Issue by jimp02** [WhitewaterFoundry/Pengwin#475]
The new Microsoft Store installer assigns Pengwin to port 2222.
Is this what you intended? Or should it be 22?

**Comment by sirredbeard** [comment]
Assigns what from Pengwin?

**Comment by jimp02** [comment]
It is assigned in Visual Studio, Tools > Options > Cross Platform, Connection Manager.
The localhost connection Port is assigned a value of 2222, replacing the 22 that was already there.
It is assigned during Pengwin installation, and 2222 is displayed on the console when it is assigned.
I forget which program is running when it is actually assigned.

**Comment by crramirez** [comment]
Hello, 

In the issue description, you wrote Microsoft Store this is why we got confused.

Pengwin-setup assigns automatically the port 2222 to the ssh service. This is to avoid interference with another service. You can change it to whatever you want just execute again pengwin-setup -> SERVICES -> SSH

Regards

**Comment by WSLUser** [comment]
Windows uses 22 by default and there have been conflicts in the past by using 22 in WSL. You can change the port number but it's not recommended to use 22 unless they make some changes in Windows itself to prevent conflicts (doubtful).

**Comment by jimp02** [comment]
Can any port number be used? Or are there restrictions?

**Comment by WSLUser** [comment]
Technically yes but I wouldn't use reserved ports like 53 (dns)
