### ISSUE TITLE
Offline Install?

### ISSUE THREAD

**Issue by Aidolii** [WhitewaterFoundry/Pengwin#477]
I'm testing on 18917 on a separate machine not connected to the internet as well as a VM, and I could use some sort of offline image of the Pengwin app, not sure how to get it.

I know the other distros have them: https://docs.microsoft.com/en-us/windows/wsl/install-manual

Just wondering if it was at all possible with Pengwin.

**Comment by ThatWeirdAndrew** [comment]
As far as I know, pre-built appx files of Pengwin are not provided as it is a paid distro. You can however build them yourself for free by following the guide in the BUILDING.md file.

**Comment by sirredbeard** [comment]
You could also buy it, install it on your primary machine, and use wsl.exe --export to export an image to your VM.

**Comment by Aidolii** [comment]
> You could also buy it, install it on your primary machine, and use wsl.exe --export to export an image to your VM.

THERE we go! Thank you.
