### ISSUE TITLE
Pengwin lost internet

### ISSUE THREAD

**Issue by Macfly** [WhitewaterFoundry/Pengwin#478]
Pengwin does not have internet access anymore even if my computer does.
It was working before and I didn't do anything special.

**Screenshots**
![image](https://user-images.githubusercontent.com/1222059/59556629-43aebb80-8f93-11e9-94ca-5ff730ec341b.png)

**Pengwin version**

Insert here: 1.2.5.0

**Windows Build**

OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. 5.11, 2/23/2018
For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by Biswa96** [comment]
What is the output of this command `cat /etc/resolv.conf`?
Try to run this command _as root_ `echo nameserver 1.1.1.1 > /etc/resolv.conf`. Any change in internet connection?

**Comment by Macfly** [comment]
the output of `cat /etc/resolv.conf` was empty.
Running `echo nameserver 1.1.1.1 > /etc/resolv.conf` fixed the issue.
Still don't know what happened. 
Thanks a lot!

**Comment by sirredbeard** [comment]
Glad that fixed for you. Thanks for your help @Biswa96!

**Comment by Biswa96** [comment]
I don't know if this is real issue but I found that every install.tar.gz (in Windows Store Appx files) from WhiteWater Corp. contains `/etc/resolv.conf`. Shouldn't that be removed before packaging it in CI/CD? So that user can choose if they use Windows DNS or another one.

**Comment by sirredbeard** [comment]
I guess we could remove resolv.conf but it gets re-written by WSL1 on launch each time.
