### ISSUE TITLE
DHCP Tools for Pengwin

### ISSUE THREAD

**Issue by GrantaLisa** [WhitewaterFoundry/Pengwin#479]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GrantaLisa** [comment]
One of my biggest reasons for using Pengwin, or any of the Linux subsystems on Windows, is to avoid having to install Cygwin.  However, one of my biggest gripes is that none of the DHCP queries I run work because of a lack of integration with the Windows system.  It would really benefit my day to day work if I could use DHCP/Ping etc, because I can more easily script my tools than in powershell.

**Comment by sirredbeard** [comment]
This is probably going to be one of those limitations of WSL1 that will make WSL2 a better fit for your use-case.

**Comment by WSLUser** [comment]
Network related functionality is extremely limited in WSL1. Perhaps they may still implement the necessary AF family in WSL to get most network functionality up and running but if so, I suspect it will be a long time coming with the major focus being on WSL2 and making it better in every way than WSL1 (at least that's my hope).
