### ISSUE TITLE
Unable to install clang-3.9 and related libraries

### ISSUE THREAD

**Issue by HelloEdit** [WhitewaterFoundry/Pengwin#480]
Hi everyone,

I'm sorry to open a way out just for that but I can't install packages with Pengwin where I used to with Unbuntu WSL.

I tried the following :
```
sudo apt-get -f install llvm-3.9-dev libclang-3.9-dev clang-3.9
```

which generates the following output :

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang-3.9 : Depends: libclang1-3.9 (= 1:3.9.1-9) but it is not going to be installed
             Depends: libllvm3.9 (>= 1:3.9.1-6~) but it is not going to be installed
             Depends: libclang-common-3.9-dev (= 1:3.9.1-9) but it is not going to be installed
 libclang-3.9-dev : Depends: libclang1-3.9 (= 1:3.9.1-9) but it is not going to be installed
                    Depends: libclang-common-3.9-dev (= 1:3.9.1-9) but it is not going to be installed
 llvm-3.9-dev : Depends: libllvm3.9 (= 1:3.9.1-9) but it is not going to be installed
                Depends: llvm-3.9 (= 1:3.9.1-9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I think it's just a lack of source in the `etc/apt/source.list` file but I have no idea what is missing >.<

Thanks,

**Comment by crramirez** [comment]
Hello,

This version of llvm (3.9) requires libstdc++6 version 6.3.0-18+deb9u1. But pengwin depends on libstdc++6 version   8.3.0-6. It creates conflict and this is why cannot be installed.

I tried the binary distribution without success. I don't know if compiling it can do the magic.

I suppose that you cannot use a newer version.

Sorry, I don't have an easy solution.

Regards

**Comment by HelloEdit** [comment]
hi, thank for your response,

You're right, this specific packages and versions are needed for rust-bindgen. I don't know if it is possible to add pengwin sources to counter this problem (I tried with debian sources without success). I'm going to go back to Ubuntu WSL for now.

Thanks,

**Comment by Biswa96** [comment]
> But pengwin depends on libstdc++6 version 8.3.0-6

Which part of Pengwin depends on it? And why? Shouldn't be Pengwin just a distribution? That `clang-3.9` packages can be installed in Debian or Ubuntu.

**Comment by Biswa96** [comment]
> But pengwin depends on libstdc++6 version 8.3.0-6

Which part of Pengwin depends on it? And why? That `clang-3.9` packages can be installed in Debian or Ubuntu.

**Comment by sirredbeard** [comment]
It looks to me like llvm-3.9 is only available for stretch: https://packages.debian.org/search?keywords=llvm-3.9.

They don't even maintain a 3.9 backport for llvm for stretch, only a 6.0 version.

Pengwin is on testing, so we are on bullseye, way ahead of stretch, so llvm 3.9 isn't available, sorry.

You could add stretch to your sources.list (I would add stretch-backports too) and pin them at an optional priority.

Then you could llvm 3.9 install from stretch: `$ sudo apt-get -t stretch install llvm...`

Another option would be to download and manually install the .deb from http://releases.llvm.org/download.html.
