### ISSUE TITLE
Pengwin-base needs to update repos

### ISSUE THREAD

**Issue by WSLUser** [WhitewaterFoundry/Pengwin#487]
**Describe the bug**
 After release of Buster as stable, performing apt update yields the following: 
E: The repository 'https://deb.debian.org/debian-security testing/updates Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
**To Reproduce**
1.) Open Pengwin
2.) `apt update`

**Expected behavior**
I expect security updates for testing to still work. Looking at the debian repos, I discovered the path to the Release file is found here: 
http://cdn-fastly.deb.debian.org/debian-security/zzz-dists/testing-security/
**Screenshots**

**Additional context**

**Basic Troubleshooting Checklist**

[x ] I have searched Google for the error message.
[x ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here:
1.2.5.0 but use the dev repos for pengwin-base and pengwin-setup.
**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. E1781IMS.104, 7/31/2014

**Comment by crramirez** [comment]
Hello,

Thank you for reporting. We made a patch for this:

https://github.com/WhitewaterFoundry/pengwin-setup/pull/185

Regards

**Comment by WSLUser** [comment]
I see it hasn't merged yet. Can @sirredbeard  review?

**Comment by sirredbeard** [comment]
Look for it in build 975 in the next few minutes.

**Comment by WSLUser** [comment]
Yep it's good. Thanks.

**Comment by aborruso** [comment]
Hi,
I have the same problem. How to solve it? How to update to build 975 ?

Thank you

**Comment by crramirez** [comment]
Hello,

Just run `pengwin-setup` it will take care of it for you.

Regards

**Comment by aborruso** [comment]
Hi @crramirez I have done it, but I have

```
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 https://dl.yarnpkg.com/debian stable InRelease
Hit:3 http://dl.google.com/linux/chrome/deb stable Release
Hit:4 https://deb.nodesource.com/node_10.x buster InRelease
Hit:5 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease
Get:6 https://cdn-aws.deb.debian.org/debian testing InRelease [117 kB]
Get:7 https://cdn-aws.deb.debian.org/debian testing-updates InRelease [38.8 kB]
Hit:8 https://cdn-aws.deb.debian.org/debian-security testing-security InRelease
Hit:9 https://cdn-aws.deb.debian.org/debian unstable InRelease
Get:11 https://cdn-aws.deb.debian.org/debian stable InRelease [118 kB]
Hit:10 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian buster InRelease
Hit:13 https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian buster InRelease
Hit:14 https://packagecloud.io/whitewaterfoundry/wslu/debian buster InRelease
Reading package lists... Done
E: Repository 'https://cdn-aws.deb.debian.org/debian testing InRelease' changed its 'Codename' value from 'buster' to 'bullseye'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'https://cdn-aws.deb.debian.org/debian testing-updates InRelease' changed its 'Codename' value from 'buster-updates' to 'bullseye-updates'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
N: Repository 'https://cdn-aws.deb.debian.org/debian stable InRelease' changed its 'Version' value from '9.9' to '10.0'
E: Repository 'https://cdn-aws.deb.debian.org/debian stable InRelease' changed its 'Codename' value from 'stretch' to 'buster'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

**Comment by crramirez** [comment]
run this `sudo apt-get update --allow-releaseinfo-change`

**Comment by aborruso** [comment]
@crramirez it works.

Do I must use always `sudo apt-get update --allow-releaseinfo-change` to do the list update?

**Comment by crramirez** [comment]
Just the first time. It updates your repositories
