### ISSUE TITLE
apt upgrade behind corporate firewall

### ISSUE THREAD

**Issue by ryn1x** [WhitewaterFoundry/Pengwin#489]
I am behind a corporate firewall with self signed certs and cannot get apt upgrade with the Pengwin repos to work:
```
Preconfiguring packages ...
Setting up pengwin-base (0.1-221) ...
Symlinking /etc/dpkg/origins/pengwin to default
Installing Whitewater Foundry GPG keys...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:41 --:--:--     0curl: (7) Failed to connect to packagecloud.io port 443: Con
nection refused
dpkg: error processing package pengwin-base (--configure):
 installed pengwin-base package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 pengwin-base
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

- I can use Ubuntu and OpenSuse in WSL just fine.
- I can `apt update` in Pengwin
- I have my ca-certificate installed to /usr/local/share/ca-certificates/
- I have my proxy set up in /etc/apt/apt.conf.d/proxy.conf and ~/.bashrc
- I've manually `apt-key add`ed this gpg key: https://packagecloud.io/whitewaterfoundry/wslu/gpgkey

**Comment by crramirez** [comment]
Hello, 

First, try to go to https://packagecloud.io/ in your browser and try to solve it.

Regards

**Comment by ryn1x** [comment]
I can get to https://packagecloud.io/ just fine. I can also curl https://packagecloud.io/ from Pengwin.

**Comment by sirredbeard** [comment]
The offending code is [here](https://github.com/WhitewaterFoundry/pengwin-base/blob/master/debian/postinst#L49). Can you copy and paste lines 49-54 into your terminal and share the results? Thank you.

**Comment by sirredbeard** [comment]
Closing to due to no response.

**Comment by ryn1x** [comment]
Sorry. I honestly just ended up installing Linux on bare metal. Too many headaches with WSL for my specific use cases.

**Comment by sirredbeard** [comment]
Maybe WSL2 will address those issues? It is still in Fast Ring and not recommended for production, but perhaps you could revisit it in a few months or try it in Gnome Boxes?

**Comment by KiranMohan** [comment]
I was facing this issue on WSL2.
But adding the corporate proxy to `/root/.curlrc` solved the issue for me.

`proxy = <proxy_host>:<proxy_port>`

**Comment by crramirez** [comment]
Thanks for sharing
