### ISSUE TITLE
Build 18945 breaks cmd-exe in /etc/profile.d/00-pengwin.sh on WSL2

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/Pengwin#497]
See Twitter thread here: https://twitter.com/toktech/status/1154995860972998656

See WSL bug report here: https://github.com/microsoft/WSL/issues/4337

Independent reproduction here: https://twitter.com/sferquel/status/1154876510408327168?s=20

**Comment by sirredbeard** [comment]
"Possible workaround is to edit /etc/profile.d/00-pengwin.sh to comment the lines containing cmd-exe or similar  references." - Tobias Kohlbau

**Comment by patrick330602** [comment]
Also, `pengwin-setup` is not working with the same reason. people who need work with Pengwin on this build should switch to WSL 1 temporarily.

**Comment by hMounir** [comment]
I have the same exact issue, but I tried to click on Ctrl + C and you will see you will get the prompt command, now, try to comment these lines inside the 00-pengwin.sh and it will work 
```
#wHomeWinPath=$(cmd-exe /c 'echo %HOMEDRIVE%%HOMEPATH%' | tr -d '\r')
#export WIN_HOME=$(wslpath -u "${wHomeWinPath}")
```

**Comment by kalanyuz** [comment]
@hMounir I tried your work around but there are still a lot of things that won't work after upgrading to wsl2. For example `code .` no longer works.

Tried upgrading vanilla Ubuntu-18.04 to wsl2 and it doesn't seem to have this issue.

**Comment by ConAntares** [comment]
>  00-pengwin.sh

Where is  00-pengwin.sh?
I can't find it via search file...

**Comment by crramirez** [comment]
`/etc/profile.d/00-pengwin.sh`

**Comment by sirredbeard** [comment]
@kalanyuz 

We are doing some environment interop stuff on launch and pengwin-setup that has been broken in WSL2 recent Insider builds.

Ubuntu doesn't do that so it's going to work for now. Sorry.

**Comment by ConAntares** [comment]
> 
> 
> `/etc/profile.d/00-pengwin.sh`
what's the parent directory? I donnot know where is /etc/....

**Comment by Biswa96** [comment]
Can anyone proivde a good `strace -ff` output? Or point out the exact syscall issue after running that faulty command or shell script?

**Comment by sirredbeard** [comment]
This has been patched in upstream.
