### ISSUE TITLE
Installing Red Hat Enterprise Linux on Pengwin (or WSL)

### ISSUE THREAD

**Issue by bugfinders** [WhitewaterFoundry/Pengwin#501]
Ive looked through and although the default is redhat like, is it properly possible to install red hat on this (as it suggested) as Im trying to buid a practice lab

**Comment by sirredbeard** [comment]
Pengwin is optimized for a Debian base.

We do make Pengwin Enterprise for Red Hat Enterprise Linux deployments along with customization and deployment consulting.

You visit https://www.pengwin.dev/pengwin-enterprise to learn more.

Please get in touch at enterprise@whitewaterfoundry.com.
