### ISSUE TITLE
How to display the GUI with X410 in the version of WSL2？

### ISSUE THREAD

**Issue by ConAntares** [WhitewaterFoundry/Pengwin#506]
The GUI with X410 worked well before upgraded to WSL2.
After I fixed the issue https://github.com/WhitewaterFoundry/Pengwin/issues/497
and use WSL2.
The GUI program doesn't work with:
```
Error: Can't open display: :0
```

**Comment by crramirez** [comment]
Hello,

Exit X410 and execute :

    X410.exe /Public
    export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0

Inside pengwin

Regards

**Comment by ConAntares** [comment]
> 
> 
> Hello,
> 
> Exit X410 and execute :
> 
> ```
> X410.exe /Public
> export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
> ```
> 
> Inside pengwin
> 
> Regards

Thank you very very very much,
It works well after I set X410 with Allow Public Access.

**Comment by crramirez** [comment]
You are welcome. For more information:

https://www.pengwin.dev/blog/2019/6/12/enable-wsl2-and-convert-existing-pengwin-installations

We are working to make it transparent to the user.

Regards

**Comment by ConAntares** [comment]
> 
> 
> You are welcome. For more information:
> 
> https://www.pengwin.dev/blog/2019/6/12/enable-wsl2-and-convert-existing-pengwin-installations
> 
> We are working to make it transparent to the user.
> 
> Regards

While, when I use another computer.
The GUI program also doesn't display without any export.
Then, I restart Pengwin, and run GUI program, it still doesn't work and notices me
```
Error: Can't open display: :0
```
ε=(´ο｀*)))

**Comment by obar1** [comment]
@Photonico  use
```
export DISPLAY=:0

```
