### ISSUE TITLE
One-click LAMP stack apache not starting

### ISSUE THREAD

**Issue by webmasterfcn** [WhitewaterFoundry/Pengwin#511]
Hello, i run the One-click LAMP stack. Apache didn't start. How can i make run?

sudo service apache2 restart
[....] Restarting Apache httpd web server: apache2(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Action 'start' failed.
The Apache error log may have more information.
 failed!

**Comment by webmasterfcn** [comment]
Now i got it working. I used Advanced_Port_Scanner_2.5.3869 to figure out which App is using port 80. It was IIS. The i unistalled IIS. after a reboot it works now for me. 
But i really missed a documentation of the scripts LAMP install and how to work with it.
I hope there would be soon a better documentation. But for now without any documentation i find 10$ is to much. You can find many super howtos on google how get LAMP stack under wsl working.

But i didn't find any for the pengwin.

**Comment by sirredbeard** [comment]
Did you try pengwin-setup?

We are working on a large documentation project. We have an issue open for it. https://github.com/WhitewaterFoundry/Pengwin/issues/493

Thank you for your patience.
