### ISSUE TITLE
permission denied when i execute apt-get clean or apt-get install

### ISSUE THREAD

**Issue by kikan321** [WhitewaterFoundry/Pengwin#515]
permission denied when i run apt-get clean

when i run from console (as administrator) the following command

apt-get clean

and i get this error:

W: Problem unlinking the file /var/cache/apt/pkgcache.bin.O2PYcC - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin.QCWmGT - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin.jC5dYg - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin.4ZWSD3 - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin.BPsz59 - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin.f2FYUY - RemoveCaches (13: Permission denied)
root@cruiz:~#

i also got the same problem 'permision denied' running ubuntu in WSL when i wanted to install new packets packages using apt-get

Even now when i run apt-get in the pengwin console i got a lot of permission denied errors even if i run the pengwin console as administrator

i am running windows 10 professional version 1809

**Comment by Biswa96** [comment]
Try `sudo rm -rf /var/cache/apt` command.

**Comment by Biswa96** [comment]
Run those command with `sudo`.

**Comment by kikan321** [comment]
> 
> 
> Run those command with `sudo`.

Hi Biswa96

I have just tried with sudo and i got the same results
just in case i was already root when i run the commands but i tried sudo anyway following your advice

Thanks

**Comment by Biswa96** [comment]
Then try to delete those files manually.

**Comment by kikan321** [comment]
> 
> 
> Then try to delete those files manually.
Hi
I tried to remove the files manually (even as root) but the same result

root@cruiz:/tmp# sudo rm -f /var/cache/apt/pkgcache.bin.*
rm: cannot remove '/var/cache/apt/pkgcache.bin.51F90V': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin.eub8QO': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin.g0k8Yn': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin.M8WByW': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin.yYslWG': Permission denied
root@cruiz:/tmp# sudo rm -f /var/cache/apt/pkgcache.bin.*
rm: cannot remove '/var/cache/apt/pkgcache.bin.51F90V': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin.eub8QO': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin.g0k8Yn': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin.M8WByW': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin.yYslWG': Permission denied

**Comment by sirredbeard** [comment]
Unable to reproduce here.

Did you try resetting Pengwin? Did it continue after resetting?

Do you have any third-party security software running on your computer?

**Comment by kikan321** [comment]
> 
> 
> Unable to reproduce here.
> 
> Did you try resetting Pengwin? Did it continue after resetting?
> 
> Do you have any third-party security software running on your computer?

Hi
I closed the console and i open it again. Now i could erase the files but when i try to do an upgrade with apt-get i get a lot of errors like tehese ones



root@cruiz:~# apt-get update
Hit:1 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian buster InRelease
Ign:2 https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian buster InRelease
Ign:3 https://packagecloud.io/whitewaterfoundry/wslu/debian buster InRelease
Ign:4 https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian bullseye InRelease
Err:5 https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian buster Release
  Could not open file /var/lib/apt/lists/partial/packagecloud.io_whitewaterfoundry_pengwin-setup_debian_dists_buster_Release - open (5: Input/output error) [IP: 99.86.61.103 443]
Err:9 https://packagecloud.io/whitewaterfoundry/wslu/debian buster Release
  Could not open file /var/lib/apt/lists/partial/packagecloud.io_whitewaterfoundry_wslu_debian_dists_buster_Release - open (5: Input/output error) [IP: 99.86.61.2 443]
Err:11 https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian bullseye Release
  404  Not Found [IP: 52.8.147.134 443]
Ign:6 https://cdn-aws.deb.debian.org/debian testing InRelease
Ign:7 https://cdn-aws.deb.debian.org/debian testing-updates InRelease
Ign:8 https://cdn-aws.deb.debian.org/debian-security testing-security InRelease
Ign:10 https://cdn-aws.deb.debian.org/debian unstable InRelease
Err:12 https://cdn-aws.deb.debian.org/debian testing Release
  Could not open file /var/lib/apt/lists/partial/deb.debian.org_debian_dists_testing_Release - open (5: Input/output error) [IP: 99.86.58.95 443]
Err:13 https://cdn-aws.deb.debian.org/debian testing-updates Release
  Could not open file /var/lib/apt/lists/partial/deb.debian.org_debian_dists_testing-updates_Release - open (5: Input/output error) [IP: 99.86.58.83 443]
Err:14 https://cdn-aws.deb.debian.org/debian-security testing-security Release
  Could not open file /var/lib/apt/lists/partial/deb.debian.org_debian-security_dists_testing-security_Release - open (5: Input/output error) [IP: 99.86.58.113 443]
Err:15 https://cdn-aws.deb.debian.org/debian unstable Release
  Could not open file /var/lib/apt/lists/partial/deb.debian.org_debian_dists_unstable_Release - open (5: Input/output error) [IP: 99.86.58.28 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://packagecloud.io/whitewaterfoundry/wslu/debian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://deb.debian.org/debian testing Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://deb.debian.org/debian testing-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://deb.debian.org/debian-security testing-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://deb.debian.org/debian unstable Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I think it is something related with the repositiory but i can't find any information which helps me to resolve this

**Comment by ahsantfw** [comment]
sudo apt-get update && sudo apt-get upgrade -y

**Comment by Whitehacker44** [comment]
ANYONE HAVE SOLUTION



apt-get clean
E: Could not open lock file /var/cache/apt/archives/lock - open (13: Permission denied)
E: Unable to lock directory /var/cache/apt/archives/
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
                                                                             
┌──(kali㉿kali)-[~]
└─$ sudo apt-get update && sudo apt-get upgrade -y                     100 ⨯
Reading package lists... Done
E: Could not get lock /var/lib/apt/lists/lock. It is held by process 19993 (apt-get)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to lock directory /var/lib/apt/lists/
                                                                             
┌──(kali㉿kali)-[~]
└─$

**Comment by crramirez** [comment]
Hello @Whitehacker44

In your case run `wsl.exe --terminate WLinux`, open Pengwin then run `sudo apt update`

**Comment by crramirez** [comment]
Hello @Whitehacker44

In your case run wsl.exe --terminate kali, open Kali Linux then run sudo apt update

**Comment by tanboys** [comment]
i got same problem 
im fix this with 
sudo apt-get update
