### ISSUE TITLE
Can't create /root/winhome (permission denied)

### ISSUE THREAD

**Issue by kikan321** [WhitewaterFoundry/Pengwin#517]
Hi

when i start pengwin console as admnistrator i got this error

Welcome to Pengwin. Type 'pengwin-setup' to run the setup tool. You will only see this message on the first run
ln: failed to create symbolic link '/root/winhome': Permission denied
root@cruiz:~#

i don't why i got this error because i am root and i am running the console as administrator

Another stranger thing is that when i check the permissions on /root/winhome i have 0 permissions

root@cruiz:~# ls -l /root/winhome
---------- 1 root root 18 Aug 18 00:37 /root/winhome

Thanks

**Comment by crramirez** [comment]
Hello,

We will check. Thank you for reporting. 

Regards

**Comment by kikan321** [comment]
> 
> 
> Hello,
> 
> We will check. Thank you for reporting.
> 
> Regards

Hi

I don't know if this is related with the problem but when i run pengwin.exe from a powershell console i get this

PS C:\WINDOWS\system32> pengwin.exe
Unpacking Pengwin, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070424
Error: 0x80070424 Le service spÚcifiÚ n?existe pas en tant que service installÚ.

Press any key to continue...
PS C:\WINDOWS\system32>


Just in case the "Windows Subsystem for Linux" checkbox is checked in the windows features

**Comment by kikan321** [comment]
> 
> 
> > Hello,
> > We will check. Thank you for reporting.
> > Regards
> 
> Hi
> 
> I don't know if this is related with the problem but when i run pengwin.exe from a powershell console (as administrator) i get this:
> 
> PS C:\WINDOWS\system32> pengwin.exe
> Unpacking Pengwin, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x80070424
> Error: 0x80070424 Le service spÚcifiÚ n?existe pas en tant que service installÚ.
> 
> Press any key to continue...
> PS C:\WINDOWS\system32>
> 
> Just in case the "Windows Subsystem for Linux" checkbox is checked in the windows features

i also tried to run pengwin from this path 
C:\Users\cruiz\AppData\Local\Microsoft\WindowsApps\WhitewaterFoundryLtd.Co.16571368D6CFF_kd1vv0z0vy70w

and i got the same message

Unpacking Pengwin, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070424
Error: 0x80070424 Le service spÚcifiÚ n?existe pas en tant que service installÚ.

Press any key to continue...

**Comment by sirredbeard** [comment]
Error: 0x80070424 is a different issue than the winhome issue, please open a new issue.

Be sure to follow the error message on launch issue template: https://github.com/WhitewaterFoundry/Pengwin/issues/new?template=WSL_error.md

**Comment by sirredbeard** [comment]
Can you please provide steps to reproduce your winhome error?

Are you using any third party security software?

**Comment by kikan321** [comment]
> 
> 
> Can you please provide steps to reproduce your winhome error?
> 
> Are you using any third party security software?

I always disabled the antivirus before executing the pengwin console
but i always got the same result
the steps to repoduce the problem are just execute the pengwin console as administrator, after the console loads i see that message
it seems that the root's enviroment variable is not charged when i call the console
i suspected that maybe i had to map  the same user that i have in windows with the user in pengwin. But when i try to add my user from the pengwin console i get this error

root@cruiz:~# adduser cruiz
Adding user `cruiz' ...
Adding new group `cruiz' (1000) ...
groupadd: /etc/group.lock: No such file or directory
groupadd: cannot lock /etc/group; try again later.
adduser: `/usr/sbin/groupadd -g 1000 cruiz' returned error code 10. Exiting.
root@cruiz:~#

**Comment by sirredbeard** [comment]
Why are you running the console as administrator? Can you reproduce these errors as a normal user?

**Comment by kikan321** [comment]
hi

I executed the pengwin console again but this time with my windows user 'cruiz' and i got the same error  

Welcome to Pengwin. Type 'pengwin-setup' to run the setup tool. You will only see this message on the first run
ln: failed to create symbolic link '/root/winhome': Permission denied
root@cruiz:~# pwd
/root

**Comment by crramirez** [comment]
In cmd.exe run:
```
pengwin.exe config --default-user cruiz
pengwin.exe
```

Regards
