### ISSUE TITLE
Go not accessible after installing in pengwin-setup

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/Pengwin#524]
We need to find a way to make Go executable immediately after installing in pengwin-setup.

![Annotation 2019-08-26 114831](https://user-images.githubusercontent.com/33820650/63703778-a6c09800-c7f7-11e9-9c5d-7ebb270b076b.png)

**Comment by grufwub** [comment]
see https://github.com/WhitewaterFoundry/Pengwin/issues/523#issuecomment-526849919

**Comment by crramirez** [comment]
The only way I have found for this due to it affects many many installations like docker, Java, etc. Is to call a shell from pengwin-setup instead of exiting. It will pass al variables to the sub shell. 

What do you think?

**Comment by sirredbeard** [comment]
Closing as duplicate of #523
