### ISSUE TITLE
Windows Server Semi-annual? Desktop environment?

### ISSUE THREAD

**Issue by ImportTaste** [WhitewaterFoundry/Pengwin#527]
I'm not sure how practical a request and/or question this is, but I'm curious about the possibility of getting Pengwin running on Windows Server's Semi-Annual channel (i.e. no Windows desktop environment), as well as possibly getting a Linux desktop environment going on it. Is the first one doable, and if so, is the second?

**Comment by Biswa96** [comment]
You can run any GNU/Linux distribution (without GUI) that Windows build has WSL support. Read more here: https://docs.microsoft.com/en-us/windows/wsl/install-on-server

**Comment by Biswa96** [comment]
If that Windows build has WSL support you can run any GNU/Linux distribution (but without GUI). Read more here: https://docs.microsoft.com/en-us/windows/wsl/install-on-server
