### ISSUE TITLE
Same xfce4 problem as closed issue #92

### ISSUE THREAD

**Issue by OttoDidac** [WhitewaterFoundry/Pengwin#533]
How was issue #92 resolved? I have the same problem.

**Comment by crramirez** [comment]
Hello,

Run pengwin-setup and install GUILIB from the GUI menu. Also install: sudo apt install xfce4-session

Also be sure that your xserver is configured for full desktop instead of each window per application. 

Regards

**Comment by OttoDidac** [comment]
Greetings,

Thank you for the prompt reply. That resolved much of the problem. FYI, I also had to set the flag dbus_enable="YES" to completely eliminate errors when running the xfsettingsd command. 

I still get errors running the xfce4-panel command that also involve wrapper-2.0, but I have the same issues on the Ubuntu distro. I'm waiting for a response from Choung Networks to see if it has anything to do with X410, since the Applications button is missing from the xfce4 panel in both Pengwin and Ubuntu. I will post again after I hear back from them.

Kind Regards

**Comment by crramirez** [comment]
Excellent. Where did you put dbus_enable="YES" ? In /etc/rc.conf ?

**Comment by OttoDidac** [comment]
I'm glad you asked. All my internet searches indicated that the dbus_enable line goes in /etc/rc.conf, but it wasn't there. A "whereis rc.conf" search turned up nothing, so I put it in ~/.bashrc and it worked.

As for the missing applications button, I'm not sure why the xfce panel looked different from the tutorial on the Choung Networks site that myself and ket000 (who opened issue #92) followed. Buttons are easily added using the panel preferences, though, so everythings working fine now.

Thanks again for your help. I'm going to close this issue out now.

KInd Regards

**Comment by crramirez** [comment]
Looks like offering install Xfce and KDE in pengwin-setup could be something to consider shortly.
