### ISSUE TITLE
Replace docker bridge with official Docker on Windows integration with WSL2

### ISSUE THREAD

**Issue by khuongduybui** [WhitewaterFoundry/Pengwin#539]
Docker Edge channel how has experimental context that delegates to dockerd / containerd in a Ubuntu 18.04 WSL2 distro (instead of using the docker VM in Hyper-V).

Currently, the feature only works with an exact Ubuntu 18.04 distro (it checks `lsb_release -a`). More information can be found here: https://docs.docker.com/docker-for-windows/wsl-tech-preview/

If we can reach out to Docker directly and have their support for to bake this feature as built-in within Pengwin, it could be a huge appeal to developers.

**Comment by patrick330602** [comment]
This issue is closed as the latest Docker beta supports Pengwin.
