### ISSUE TITLE
Manually download the paid version? 

### ISSUE THREAD

**Issue by camilorojasguzman** [WhitewaterFoundry/Pengwin#540]
Is there a way to manually download the paid version? I purchased your product via the MS store but my work has all MS store apps blocked. I've downloaded other WSL distros manually (https://docs.microsoft.com/en-us/windows/wsl/install-manual) but they were all free versions. 

Order details October 23, 2019
Order number 1258389547
Completed
Paid with
Visa **x713
Billing
address
866 nxxxx
Subtotal $9.99
Tax $0.62
Total $10.61

**Comment by camilorojasguzman** [comment]
Carlos,

Thanks for the quick response. I sent you an email from @xxxxxxxroepartners domain.

**Comment by reifnir** [comment]
Hi @camilorojasguzman, did Whitewater Foundry get back to you about the download link? I emailed them yesterday and today about this same issue and still haven't heard back yet.

**Comment by crramirez** [comment]
Hello @reifnir,

We answered him and also you some minutes ago with basically the same answer. But we haven't received his response, I wonder if our emails are arriving. Could you confirm please if you received an email from us?

Regards

**Comment by reifnir** [comment]
For anyone else looking to purchase and sideload Pengwin from an appx file, Whitewater Foundry cannot currently support this capability. Hopefully that changes in the future.

**Comment by Biswa96** [comment]
One can create a project in any CI that supports Windows and Debian/Ubuntu image both and build pengwin there. Create the whole Appx or only the tarball as wish.
