### ISSUE TITLE
Failed loading QtWebEngine in Qt5 applications

### ISSUE THREAD

**Issue by eliranwong** [WhitewaterFoundry/Pengwin#544]
**Describe the bug**
Pengwin failed to load QtWebEngine in Qt5 applications.  I tried to run several different Qt5 applications which use QtWebEngine, every time it returns the following errors.

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-eliran'
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
shared memfd open() failed: Function not implemented
Trace/breakpoint trap (core dumped)

**To Reproduce**
1. Install and Run "falkon", a Qt5-based web browser
> sudo apt install falkon
> falkon

2. The step above comes with "error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory" [I think it may be another bug in pengwin's distribution]

I run the following for a temporary fix

> sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

3. Run "falkon" again, and I get these errors:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-eliran'
Failed to connect to session bus!
Failed to connect to session bus!
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
shared memfd open() failed: Function not implemented
Trace/breakpoint trap (core dumped)

4. The "Failed to connect to session bus!" is obviously another bug in pengwin, which as already reported by someone.  To temporarily deal with it, I ran

> dbus-launch falkon

5. Run AGAIN "falkon" and get the following errors, which I don't have a solution yet.

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-eliran'
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context
shared memfd open() failed: Function not implemented
Trace/breakpoint trap (core dumped)

The above error does NOT only appear in running falkon.  I tried some other Qt5 applications.  I myself have an Qt5 application [https://github.com/eliranwong/UniqueBible], running straightforward and smooth in other Linux distributions.  Pengwin is the only exception, producing same errors above.

**Expected behavior**
I expect Qt5 applications, which use QtWebEngine can run with pengwin

**Basic Troubleshooting Checklist**

* I have searched Google for the error message.
* I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
* I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
* I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
* I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
* I have disabled and re-enabled WSL in Windows Features.
* I have run Windows 10 updates and restarted.

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here:

1.2.8.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

Host Name:                 DESKTOP-FOSO727
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Microsoft Corporation 1.1.12, 6/24/2019
Logon Server:              \\DESKTOP-FOSO727

**Comment by sirredbeard** [comment]
Did you try running the GUI option in pengwin-setup? Pengwin installs and does some things there can address some of these issues.

**Comment by eliranwong** [comment]
I tried ALL the GUI options in pengwin-setup, but none of them helps on this issue.

**Comment by eliranwong** [comment]
pengwin consistently fails launching applications, which use QtWebEngine.

**Comment by crramirez** [comment]
Hello,

You need to install mesa-utils and disable the OpenGL pass-through in the Xserver.

Regards

**Comment by eliranwong** [comment]
@crramirez Thanks for help.  I installed mesa-utils, but I don't know how to disable OpenGL passthrough.  What is the best way to do so in pengwin?

**Comment by eliranwong** [comment]
> Hello,
> You need to install mesa-utils and disable the OpenGL pass-through in the Xserver.
> Regards

It does NOT work.  Following your advice, I installed mesa-utils.  To disable OpenGL, I added the following content to /etc/X11/xorg.conf.d/disable-gpu.conf

> Section "Extensions"
>     Option "OpenGL" "Disable"
> EndSection

Running an app, which uses QtWebEngine, still comes up with the same errors:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-eliran'
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context
shared memfd open() failed: Function not implemented
Trace/breakpoint trap (core dumped)

**Comment by crramirez** [comment]
Call this: https://github.com/WhitewaterFoundry/Pengwin/issues/322#issuecomment-467185294

**Comment by eliranwong** [comment]
I tried both "export -n LIBGL_ALWAYS_INDIRECT" and "env -u LIBGL_ALWAYS_INDIRECT ..." suggested in the post above, but they don't work for this issue.

The error message is very consistent.

> WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
> QGLXContext: Failed to create dummy context
> shared memfd open() failed: Function not implemented
> Trace/breakpoint trap (core dumped)

**Comment by crramirez** [comment]
Well, tomorrow I will try to reproduce the error and get back to you.

**Comment by crramirez** [comment]
Hello,

I couldn't make Falkon work, Konqueror also won't.

With the following commands, you can run most QT applications including Dolphin:

Run pengwin-setup and choose GUI-GUILIB

Then

```
sudo sed -i 's/export LIBGL_ALWAYS_INDIRECT=1/unset LIBGL_ALWAYS_INDIRECT/' /etc/profile.d/00-pengwin.sh
sudo apt install binutils
sudo apt install dolphin # Or any other Qt app
sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
sudo apt install mesa-utils
```

Close and open pengwin. Then

`dolphin #Or your Qt installed app`

If you want to see KDE icons:

```
sudo apt install plasma-desktop
echo "export QT_QPA_PLATFORMTHEME='kde'" >>~/.bashrc

```
Close and open pengwin

Regards

**Comment by eliranwong** [comment]
Hello @crramirez ,

  I am grateful to your help, much appreciated.  I will try script.

  I would also like to share a solution to falkon and other apps using QtWebEngine.

  I convert wsl to version 2, I use the following script to run all gui applications.
  https://github.com/eliranwong/Chrome-OS-Linux/blob/master/others/gui.sh

  Falkon, others apps using google web engine work perfectly.  A very useful line, export -n LIBGL_ALWAYS_INDIRECT, which you advised earlier help me to git rid of QtWebEngine error under WSL2.

  In additions, apps, like gthumb, mailsprings, etc, which didn't work in WSL1 now work in WSL2 with pengwin.

  fcitx, however, is broken in WSL2, as I already mentioned in other posts.  ibus work perfectly in WSL2.

  I can now enjoy pengwin for daily work in WSL2.  Thanks for your great works.

Blessings,
Eliran

**Comment by crramirez** [comment]
Glad it worked and thank you for your script we are working in improving Pengwin on WSL 2 and it will help.

Regards
