### ISSUE TITLE
Windows Explorer Context Menu Icon is Missing for WSL2

### ISSUE THREAD

**Issue by validatedev** [WhitewaterFoundry/Pengwin#545]
**Describe the bug**
I installed Windows Explorer context menu setting in pengwin-setup, but it looks like the icon doesn't display right on WSL2.

**To Reproduce**
1. Right click on desktop or anywhere else.

**Expected behavior**
We should see the Pengwin logo on context menu.

**Screenshots**
<img width="189" alt="pengwin_bug" src="https://user-images.githubusercontent.com/29679552/69609847-87761880-103b-11ea-93d0-86fdf6f96f1e.png">

**Additional context**

**Basic Troubleshooting Checklist**

[.] I have searched Google for the error message.
[.] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[.] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[.] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[.] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[.] I have disabled and re-enabled WSL in Windows Features.
[.] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here: Reinstalling Windows completely (that is not directly related with that issue but I did it)

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: 1.2.8.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19025 N/A Build 19025
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              HUAWEI 1.19, 12/08/2019

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Thank you for reporting. To confirm it works but the icon is not shown?

**Comment by patrick330602** [comment]
I can actually confirm this issue, I think this is the issue that the icon locates under WSL folder but after WSL conversion it is no longer in the location. I will try to solve this issue. @crramirez

**Comment by crramirez** [comment]
We can include the icon in the appx so we can access it after the app is installed

**Comment by validatedev** [comment]
> Thank you for reporting. To confirm it works but the icon is not shown?

Yeah it absolutely is. Thanks for the response.
