### ISSUE TITLE
Bundle "ibus" with pengwin?

### ISSUE THREAD

**Issue by eliranwong** [WhitewaterFoundry/Pengwin#549]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is that fcitx bundled with pengwin is very broken in many applications, though it works in some application.  The problem get worse under wsl2.

ibus works perfectly so far I tested under pengwin.

**Describe the solution you'd like**
I installed ibus in pengwin, which works perfectly.  My notes on the installation is posted at https://github.com/eliranwong/Chrome-OS-Linux/blob/master/others/windows_wsl.md#ibus

I hope it is bundled with pengwin so that I can install under pengwin-setup in the future.

**Describe alternatives you've considered**
Fix the brokenness of fcitx, where fcitx is not opened or word candidate panel does not show up.

**Comment by crramirez** [comment]
Thank you for reporting we will put it into our roadmap

**Comment by hanubeki** [comment]
I tried ibus in Debian but not working in WSL1, and uim does.
I didn't tried in Pengwin though.

**Comment by eliranwong** [comment]
@hanubeki can you share instructions on installing uim, so I may try it with pengwin?  

So far, iBus works perfectly to me.  It wirks with Qt5 apps, terminal, and all gui apps I tried.  but I am open to try some others.

**Comment by eliranwong** [comment]
> I tried ibus in Debian but not working with WSL1.
> uim, an another input method is worked in Debian with WSL1.
> I didn't try both in Pengwin though.

Hello @hanubeki , I wonder why ibus didn't work in your Debian with WSL1 but works perfectly in pengwin on my side.  I think pengwin uses Debian.

so, out of curiosity, I installed Debian with WSL1 on my device and take a look.  iBus actually works as expected.  Just Debian takes more steps for the installation than pengwin.  

I would like to share how below how I install on Debian WSL1 and do some comparison with pengwin later:

First, I need to set up Chinese locale first, I guess to you it should be replaced with Japanese.  I will talk a little bit on this as I can see the beauty of pengwin in saving me from a few steps here.

> sudo dpkg-reconfigure locales

In my case, I selected "zh_CN.UTF8 UTF8"

Second, I installed Chinese fonts

> sudo apt install xfonts-wqy ttf-wqy-zenhei ttf-wqy-microhei fonts-arphic-bkai00mp fonts-arphic-bsmi00lp fonts-arphic-gbsn00lp fonts-arphic-gkai00mp xfonts-intl-chinese xfonts-intl-chinese-big

Third, install ibus

> sudo apt install zenity dbus-x11
> sudo apt install ibus ibus-libpinyin ibus-table-cangjie5 ibus-gtk* ibus-qt*
> im-config

select "OK"
select "Yes" to question "Do you explicitly select the user configuration?"
select "ibus"
select "OK"
select "OK"

Fourth, setup ibus

> dbus-launch ibus-daemon -x -d
> dbus-launch ibus-setup

Fifth, restart dbus service

> pkill ibus-daemon
> dbus-launch ibus-daemon -x -d

Sixth, set variables,

> export DISPLAY=127.0.0.1:0.0
> export LC_CTYPE="zh_CN.UTF-8"
> export XIM=ibus
> export XIM_PROGRAM=/usr/bin/ibus
> export QT_IM_MODULE=ibus
> export GTK_IM_MODULE=ibus
> export XMODIFIERS=@im=ibus
> export DefaultIMModule=ibus

Last, run a gui to test,

> sudo apt install geany
> dbus-launch geany

It woks as expected.  Below is a screenshot.

[https://github.com/eliranwong/Chrome-OS-Linux/blob/master/others/Clipboard01.png](url)

Comparison to running ibus in pengwin:

pengwin requires fewer steps for installation.  In case you are interested, my notes on installation in pengwin is available at: https://github.com/eliranwong/Chrome-OS-Linux/blob/master/others/windows_wsl.md#ibus

One thing I found it good to use ibus in pengwin is that I don't need to change the default locale to Chinese.  I didn't tried further in Debian, but it seems ibus works only if I change the locale.

I wonder what tricks pengwin had done to pengwin distribution, so I can use Chinese input method while keeping English as default locale in pegnwin?

**Comment by hanubeki** [comment]
Okay, I tried ibus again in Debian with WSL1, it worked as expected.
I don't know why is was not working before.

for uim in Debian, I installed that from task-japanese-desktop, but it is for Japanese user.

**Comment by eliranwong** [comment]
I would like to add one more observation, in case you may consider in future testings.

I had just took off my physical keyboard from my Windows tablet.

I am really surprised when I started to use Windows virtual keyboard to type on a Linux app.  As I type with the Windows virtual keyboard, ibus works PERFECTLY to input Chinese texts in my Linux app.  pressing Ctrl + space on the virtual keyboard switches ibus input methods too.
