### ISSUE TITLE
Defender has identified a trojan in Pengwin, breaks sudo

### ISSUE THREAD

**Issue by JRansomed** [WhitewaterFoundry/Pengwin#557]
**Describe the bug**
Just did an install onto a new Windows machine today and sudo is broken.  This makes it so you can't install or configure anything.  Get the following error:

`sudo: error while loading shared libraries: libsudo_util.so.0: cannot open shared object file: No such file or directory`

It appears Defender is quarantining your sudo library.  It doesn't do this to the Ubuntu container, so there is something in your sudo library that is considered a trojan and therefore blocked.  This is really unsettling.

From Defender:
![Defender and Pengwin](https://user-images.githubusercontent.com/24248315/70476038-dc864580-1aa3-11ea-894e-5f245f3f082f.png)

**To Reproduce**
1. Install Penwin on a new computer
2. Complete the user setup
3. Attempt to use sudo

**Expected behavior**
For sudo to work and Defender to not quarantine parts of Pengwin with a trojan message.

**Screenshots**

**Additional context**

**Basic Troubleshooting Checklist**

[ ] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?
- Reset Penwin
- Uninstall and Re-install Penwin
- Installed Ubuntu and sudo works as expected.  Definitely something in Penwin's build.

**Pengwin Version** 
1.2.8

**Windows Build**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19037 N/A Build 19037

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by JRansomed** [comment]
Just saw someone else posted the same issue.  I'm not in the fast ring, but same issue.  Closing this as it is essentially the same thing.

**Comment by crramirez** [comment]
See: https://github.com/WhitewaterFoundry/Pengwin/issues/555#issuecomment-564266189
