### ISSUE TITLE
Penguin GUI apps not working with VcXsrv

### ISSUE THREAD

**Issue by Thorocaine** [WhitewaterFoundry/Pengwin#558]
**Describe the bug**
Trying to run a GUI app returns:
```
Error: Can't open display: :0
```

**To Reproduce**
1. run `penguin-setup`
2. install emacs and VcXsrv
2. use apt to install x11-apps
3. restart computer
4. open terminal, and open wsl (to make sure it is running)
5. from the start menu try open emacs GUI (nothing happens)
6. from the terminal, try run xeyes (get Error: Can't open display: :0)
7. check system tray (VcXsrv is running version 1.20.1.4)

**Expected behavior**
I expect the programs to run, and not give an error

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[x] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

**Pengwin Version**
1.2.8.0

**Windows Build**
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19035 N/A Build 19035
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Alienware 1.8.0, 5/30/2019
```

**Comment by crramirez** [comment]
Hello, 

By any chance you are using WSL2? It should work in WSL1 for WSL2 we are working on this.

Regards

**Comment by Thorocaine** [comment]
It is WSL2.
Thank you for the quick update.

**Comment by crramirez** [comment]
Follow this PR: https://github.com/WhitewaterFoundry/pengwin-base/pull/61/files. You'll need to replace your /etc/profile.d/00-pengwin.sh with the file in this PR and be sure that VcxSrv accepts connections from anywhere: vcxsrv -ac

**Comment by Thorocaine** [comment]
@crramirez That worked as well, thank you, it just needs AC Disabled, I might be able to create a default config.

**Comment by Thorocaine** [comment]
For anyone who stubles accross this:
After replacing `00-pengwin.sh` as per @crramirez you want to edit the file `/etc/profile.d/vcxsrv.sh`.
you can add `-ac` to the command that is run from there.

**Comment by f-liva** [comment]
Also to me XServer doesn't work, from the Windows tray icon it tells me 0 clients connected and trying to open any application from Pengwin nothing happens.

**Comment by crramirez** [comment]
Hello @f-liva ,

I need some information to help you. First, what does this command? `echo $DISPLAY` which is the output?

What happen when you start a GUI app from the command line? which is the output?

Regards

**Comment by f-liva** [comment]
localhost:0.0

The error is Cannot open display

![2021-07-30_18-41-18](https://user-images.githubusercontent.com/346224/127684926-a55d0233-9e3d-46b1-952b-8f5393749181.gif)

**Comment by crramirez** [comment]
Now please execute :

wsl.exe --list --verbose

**Comment by f-liva** [comment]
C:\Users\fede9>wsl --list --verbose
  NAME                   STATE           VERSION
* docker-desktop         Stopped         2
  docker-desktop-data    Stopped         2
  WLinux                 Stopped         2

Il giorno ven 30 lug 2021 alle ore 19:50 Carlos Rafael Ramirez <
***@***.***> ha scritto:

**Comment by crramirez** [comment]
Looks like you are in WSL 2 but the configuration in Pengwin is for WSL1. Could you please execute:

`cat /etc/os-release `

and

`cat /etc/profile.d/00-pengwin.sh`

and send me the results?

Regards,
Carlos

**Comment by f-liva** [comment]
cat /etc/os-release

PRETTY_NAME="Pengwin"
NAME="Pengwin"
VERSION_ID="11"
VERSION="11 (bullseye)"
ID=debian
ID_LIKE=debian
HOME_URL="https://github.com/whitewaterfoundry/Pengwin"
SUPPORT_URL="https://github.com/WhitewaterFoundry/Pengwin/issues"
BUG_REPORT_URL="https://github.com/WhitewaterFoundry/Pengwin/issues"
VERSION_CODENAME=bullseye
PENGWIN_VERSION="21.7.1"

cat /etc/profile.d/00-pengwin.sh

#!/bin/sh

# Only the default WSL user should run this script
if ! (id -Gn | grep -c "adm.*sudo\|sudo.*adm" >/dev/null); then
  return
fi

setup_display() {

  if [ -n "${XRDP_SESSION}" ]; then
    return
  fi

  # WSL2 Environment variable meaning:
  # WSL2=0: WSL1
  # WSL2=1: WSL2 (Type 1)
  # WSL2=2: WSL2 (Type 2)
  # WSL2=3: WSL2 (Type 3)
  if [ -n "${WSL_INTEROP}" ]; then

    if [ -n "${DISPLAY}" ]; then
      # check if the type is changed
      sudo /usr/local/bin/wsl_change_checker 3 "WSL2" "${DISPLAY}"
      sudo /usr/local/bin/wsl2_ip_checker "$(echo "$DISPLAY" | cut -d : -f
1)"
      #Export an enviroment variable for helping other processes
      export WSL2=3

      return
    fi

    # enable external x display for WSL 2
    ipconfig_exec=$(wslpath "C:\\Windows\\System32\\ipconfig.exe")
    if (command -v ipconfig.exe >/dev/null 2>&1); then
      ipconfig_exec=$(command -v ipconfig.exe)
    fi

    wsl2_d_tmp="$(eval "$ipconfig_exec 2> /dev/null" | grep -n -m 1
"Default Gateway.*: [0-9a-z]" | cut -d : -f 1)"

    if [ -n "${wsl2_d_tmp}" ]; then

      wsl2_d_tmp="$(eval "$ipconfig_exec" | sed "$((wsl2_d_tmp -
4))"','"$((wsl2_d_tmp + 0))"'!d' | grep IPv4 | cut -d : -f 2 | sed -e
"s|\s||g" -e "s|\r||g")"
      export DISPLAY=${wsl2_d_tmp}:0

      # check if the type is changed
      sudo /usr/local/bin/wsl_change_checker 2 "WSL2" "${wsl2_d_tmp}:0\.0"
      sudo /usr/local/bin/wsl2_ip_checker "$wsl2_d_tmp"
      #Export an enviroment variable for helping other processes
      export WSL2=2

    else
      wsl2_d_tmp="$(grep </etc/resolv.conf nameserver | awk '{print $2}')"
      export DISPLAY=${wsl2_d_tmp}:0

      # check if we have wsl.exe in path
      sudo /usr/local/bin/wsl_change_checker 1 "WSL2" "$DISPLAY"
      sudo /usr/local/bin/wsl2_ip_checker "$wsl2_d_tmp"
      #Export an enviroment variable for helping other processes
      export WSL2=1
    fi

    unset ipconfig_exec
    unset wsl2_d_tmp

  else

    # enable external x display for WSL 1
    export DISPLAY=localhost:0

    # check if we have wsl.exe in path
    sudo /usr/local/bin/wsl_change_checker 0 "WSL1" "localhost:0"

    # Export an enviroment variable for helping other processes
    unset WSL2

  fi
}

setup_display

# enable external libgl if mesa is not installed
if (command -v glxinfo >/dev/null 2>&1); then
  unset LIBGL_ALWAYS_INDIRECT
  sudo /usr/local/bin/libgl-change-checker 0
else
  export LIBGL_ALWAYS_INDIRECT=1
  sudo /usr/local/bin/libgl-change-checker 1
fi

# speed up some GUI apps like gedit
export NO_AT_BRIDGE=1

# Fix 'clear' scrolling issues
alias clear='clear -x'

# Custom aliases
alias ll='ls -al'
alias winget='powershell.exe winget'

# Check if we have Windows Path
if (command -v cmd.exe >/dev/null); then

  # Execute on user's shell first-run
  if [ ! -f "${HOME}/.firstrun" ]; then
    echo "Welcome to Pengwin. Type 'pengwin-setup' to run the setup tool.
You will only see this message on the first run."
    touch "${HOME}/.firstrun"
  fi

  # shellcheck disable=SC1003
  if (! wslpath 'C:\' >/dev/null 2>&1); then
    # shellcheck disable=SC2262
    alias wslpath=legacy_wslupath
  fi

  # Create a symbolic link to the windows home

  # Here have a issue: %HOMEDRIVE% might be using a custom set location
  # moving cmd to where Windows is installed might help: %SYSTEMDRIVE%
  wHomeWinPath=$(cmd.exe /c 'cd %SYSTEMDRIVE%\ && echo
%HOMEDRIVE%%HOMEPATH%' 2>/dev/null | tr -d '\r')

  if [ ${#wHomeWinPath} -le 3 ]; then #wHomeWinPath contains something like
H:\
    wHomeWinPath=$(cmd.exe /c 'cd %SYSTEMDRIVE%\ && echo %USERPROFILE%'
2>/dev/null | tr -d '\r')
  fi

  # shellcheck disable=SC2155
  export WIN_HOME=$(wslpath -u "${wHomeWinPath}")

  win_home_lnk=${HOME}/winhome
  if [ ! -e "${win_home_lnk}" ]; then
    ln -s -f "${WIN_HOME}" "${win_home_lnk}" >/dev/null 2>&1
  fi

  unset win_home_lnk
fi


Il giorno dom 1 ago 2021 alle ore 23:11 Carlos Rafael Ramirez <
***@***.***> ha scritto:

**Comment by crramirez** [comment]
Everything looks fine. Have you defined WSLENV variable from Windows with the DISPLAY value?

**Comment by f-liva** [comment]
Other than installing Pengwin, I haven't done anything else. I don't know
anything about this variable, maybe I missed some documentation for the
installation? Were there any steps to do?

Il lun 2 ago 2021, 11:46 Carlos Rafael Ramirez ***@***.***>
ha scritto:

**Comment by crramirez** [comment]
You don't need to do anything else for it to work. It should be working. 

Did you install Pengwin in WSL2 ? or you migrated from WSL1

**Comment by crramirez** [comment]
@f-liva Could you please edit the file /etc/environment:

sudo nano /etc/environment

And delete this line if exist?

DISPLAY=localhost:0.0

Then save, close and open Pengwin

Regards

**Comment by f-liva** [comment]
The only thing that allowed me to fix it was to run this command:

export DISPLAY=$(route.exe print | grep 0.0.0.0 | head -1 | awk '{print
$4}'):0.0

Do you have any idea why?

Il giorno mar 3 ago 2021 alle ore 06:47 Carlos Rafael Ramirez <
***@***.***> ha scritto:

**Comment by crramirez** [comment]
Yes, /etc/profile.d/00-pengwin.sh should do this automatically. And I am breaking my head trying to figure out why it is not working in your case. 

And all my questions are looking for if you made a modification, but as you only installed Pengwin from scratch and nothing else, I cannot figure out why it is not working.

**Comment by crramirez** [comment]
you can add this command to `/etc/profile.d/00-a.sh` and it will be globally applied. Be sure to delete it when you upgrade to Windows 11 and use WSLg

**Comment by f-liva** [comment]
Thanks for the tip!







On Tue, Aug 3, 2021 at 10:32 AM Carlos Rafael Ramirez ***@***.***> 
 wrote:


you can add this command to /etc/profile.d/00-a.sh  and it will be globally
applied. Be sure to delete it when you upgrade to Windows 11 and use WSLg

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS  or Android.

**Comment by wsargent** [comment]
Ran into the same problem, where X410 stopped working.  Using 

```
export DISPLAY=$(route.exe print | grep 0.0.0.0 | head -1 | awk '{print $4}'):0.0
```

and then running commands worked for a workaround.

**Comment by f-liva** [comment]
Is it known why we have to do this every time to get Pengwin working?

**Comment by crramirez** [comment]
Sadly no. We don't understand why it is not working out of the box in your configuration.  /etc/profile.d/00-pengwin.sh does exactly that, grab your host ip and export DISPLAY variable with this value.

**Comment by crramirez** [comment]
Hello @f-liva 

I can reproduce the issue if I manually disable the interop. If I add the following lines to /etc/wsl.conf:

```
[interop]
enabled=false
```
But again Pengwin has it enabled by default.

**Comment by herrlegno** [comment]
> Ran into the same problem, where X410 stopped working. Using
> 
> ```
> export DISPLAY=$(route.exe print | grep 0.0.0.0 | head -1 | awk '{print $4}'):0.0
> ```
> 
> and then running commands worked for a workaround.

Same Issue here with VcXsrv, this solution worked for me.  But I noticed one thing:
* Default Pengwin Display: 172.25.208.1:0
* Display after running such command: 192.168.1.57:0.0

Seems like the automatic IP detection might be wrong. Also if I run "code ." it opens but if I use the shortcut created for visual studio code in the start menu it doesn't show up.

**Comment by f-liva** [comment]
Maybe this wrong behaviour happens when there is more than one network card
enabled to the host system? It makes sense?

Il gio 9 set 2021, 18:36 Alejandro González Alonso ***@***.***>
ha scritto:

**Comment by wsargent** [comment]
I have both a wireless card and ethernet connected so that checks out.

**Comment by crramirez** [comment]
Hello,

We will release a new version using the "export DISPLAY=$(route.exe print" method. Because one of the flaws of the ipconfig method is that it only works if Windows is on English, and maybe some of you have windows in another language.

I will post here when it is ready so you can test.

Thanks for the suggestions

Regards,
Carlos

**Comment by f-liva** [comment]
Great thank! I've windows in Italian

Il gio 9 set 2021, 20:54 Carlos Rafael Ramirez ***@***.***>
ha scritto:

**Comment by herrlegno** [comment]
I did a fresh install again to test other PC with only one network card and it is still failing to get the right address. But I do have both PC on Spanish, so that could be really the problem.

Thanks @crramirez for answering so fast!

**Comment by f-liva** [comment]
@crramirez in answer to your last question, if I print the veriable $WSL_INTEROP I get an empty answer.

```bash
fede9@DESKTOP-VCCNQ3E:~$ echo $WSL_INTEROP

fede9@DESKTOP-VCCNQ3E:~$
```

**Comment by crramirez** [comment]
@f-liva you have the Interop disabled and nothing in Pengwin will work as expected. Check your /etc/wsl.conf

For example if you type notepad.exe nothing should happens. With Interop enabled it should open notepad.

**Comment by f-liva** [comment]
Actually in the file there is no trace of interop. How can I manually enable it so that the GUIs work?

**Comment by crramirez** [comment]
It should be working. My only guess is that you have a misconfiguration of wsl. I would recommend disabling it in Windows Features and install it again using wsl --install. You can make a backup of your pengwin installation

**Comment by f-liva** [comment]
Hello!

Why issue closed?

**Comment by crramirez** [comment]
Hello @f-liva,

This issue was opened and closed two years ago. Since then, nobody has reopened it. The reason why it is failing in your case is entirely different from the original reason for this ticket.

In your case, the interop is not working well, and my recommendation is to disable and enable wsl again. 

Regards,
Carlos

**Comment by f-liva** [comment]
I will investigate thanks
