### ISSUE TITLE
SDKMAN is not working on ZSH

### ISSUE THREAD

**Issue by kamalhm** [WhitewaterFoundry/Pengwin#560]
**Describe the bug**

**To Reproduce**
1. Install pengwin
2. run pengwin-setup
3. install jdkman and zsh shell
4. restart
5. try `sdk` command on zsh, not found

**Expected behavior**
`sdk` command should list all the command available for SDKMAN

**Screenshots**
On bash
![image](https://user-images.githubusercontent.com/15316378/70914943-8ab56080-204b-11ea-9aac-c1b23dfeb406.png)
On zsh
![image](https://user-images.githubusercontent.com/15316378/70914966-93a63200-204b-11ea-9751-170a77beed53.png)

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: 1.2.8.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here: 19041

**Comment by crramirez** [comment]
We will put it on the roadmap. Thank you for reporting

**Comment by crramirez** [comment]
Hello,

Be sure that you set ZSH as your default shell, then install again SDKMAN from pengwin-setup.

The order is important here. Sdkman installs its configuration in the default shell.

Regards

**Comment by kamalhm** [comment]
Do I have to reinstall everything? 

Because right now, even with ZSH as my default shell, when I attempt to install SDKMAN again, it says that SDKMAN already installed

**Comment by crramirez** [comment]
Run the following command and restart pengwin:

`echo source "${HOME}/.sdkman/bin/sdkman-init.sh">>"${HOME}/.zshrc"`

Regards

**Comment by kamalhm** [comment]
It works! Thanks!

**Comment by FabianLoRs** [comment]
> Run the following command and restart pengwin:
> 
> `echo source "${HOME}/.sdkman/bin/sdkman-init.sh">>"${HOME}/.zshrc"`
> 
> Regards

Works, thanks
