### ISSUE TITLE
Linux browsers under pengwin cannot log in in websites

### ISSUE THREAD

**Issue by eliranwong** [WhitewaterFoundry/Pengwin#561]
**Describe the bug**
Just got a new laptop to setup pengwin and Linux webbrowsers.  Browsing is ok, but cannot login with Linux browsers under pengwin.  Windows browsers can login.

**To Reproduce**
1) install pengwin (1.3.4)
2) convert to WSL2
3) install firefox-esr and google-chrome
4) go to https://github.com or https://gmail.com
5) try login in, username and password entered
6) cannot login to GitHub and gmail with both firefox and google-chrome
7) firefox display the following errors:

Secure Connection Failed

An error occurred during a connection to github.com. SSL peer reports incorrect Message Authentication Code. Error code: SSL_ERROR_BAD_MAC_ALERT

**Comment by eliranwong** [comment]
I can confirm that the errors is specific to pengwin.

Login works on Windows side.  Also, ...

I had just installed Debian on the same Windows laptop.

Login in with firefox in gmail and github works perfectly.

However, going back to pengwin, I have no success for any login.  please fix it, I do need to log in my account with Linux browser under pengwin.  many thanks in advance.

**Comment by eliranwong** [comment]
for your information, my old surface go works perfectly with login under pengwin wsl2, but I am not sure if I were using pengwin version 1.3.4.  now I am using pengwin version 1.3.4 in Lenovo S730, it seems everything works the same as before, except website login not working.

**Comment by patrick330602** [comment]
Interesting. My local testing shows it works. Could you provide what you have installed with pengwin-setup?
<img width="1152" alt="Screenshot 2019-12-22 at 12 50 41 AM" src="https://user-images.githubusercontent.com/15316889/71310927-16b4f700-2455-11ea-9c1e-305c6d79881f.png">

**Comment by eliranwong** [comment]
@patrick330602 thanks for checking.  did you try in WSL2?

I converted back to WSL1, firefox can login in GitHub and gmail.  However, after I converted to WSL2 again, login does not work.  As google-chrome can run only in WSL2 not WSL1, I cannot even try in WSL1 with google-chrome.

In my old microsoft surface go, I can login with both github and gmail with both firefox-esr and google-chrome under WSL2.  It is very strange I can no longer do that with my new laptop in WSL2.

answering your question, I installed the following items.  I did the same with my old surface go, so it should not introduce a difference with these options:

GUI > GUILIB
GUI > SYNAPTIC
PROGRAMMING > GO
PROGRAMMING > PYTHONPI
SETTINGS > EXPLORER
SETTINGS > COLORTOOL

**Comment by eliranwong** [comment]
one more finding,

I just checked my old surface go, I updated pengwin to version 1.3.4.  I opened google-chrome and signed out an account.  I can log in again.

the problem is that old surface go and new laptop have the same network setup, the only difference is that my surface go has a LTE option.  I do not expect they would behave differently for internet access.

**Comment by patrick330602** [comment]
Interesting. I will do some testing now.

**Comment by eliranwong** [comment]
a solution found!

apology, it is not an issue specific to pengwin.

after reading the post at https://github.com/microsoft/WSL/issues/4253

https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html

and installed "Intel Driver & Support Assistant"

and updated the wifi driver.

I can now login github and gmail under WSL2.

[Remarks: Microsoft "Windows Update" does not tell about the newer version of wifi driver.]

thanks once again for your help @patrick330602
