### ISSUE TITLE
pengwin-setup missing

### ISSUE THREAD

**Issue by aladd134** [WhitewaterFoundry/Pengwin#563]
**Describe the bug**
the system cannot find the `pengwin-setup` script. 
running the script downloaded from the github page gives me a user error

                    pengwin-setup was ran with the user "[my- user]".                 │
                   │                                                                                                │
                   │ Run pengwin-setup from the default user and without sudo

**Expected behavior**
Pengwin-setup should run 

**Screenshots**
![image](https://user-images.githubusercontent.com/6111735/71376347-1de02000-258f-11ea-8dbf-1ee264131771.png)

![image](https://user-images.githubusercontent.com/6111735/71376389-3ea87580-258f-11ea-950f-5163669c90db.png)

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

I am running in fish, and have uninstalled and reinstalled pengwin-setup using apt
I have downloaded the bash script from https://github.com/WhitewaterFoundry/pengwin-setup and run that manually
I have not reset WSL as I am hoping to preserve my file structure

Insert here:

**Pengwin Version**

1.2.8.0

**Windows Build**

10.0.18362 N/A Build 18362

**Comment by crramirez** [comment]
Hello,

Looks like you have a problem with your PATH variable. Can you send please the output of: echo $PATH

Regards

**Comment by aladd134** [comment]
`$echo $PATH` yields
`/home/aaron/.pyenv/bin /mnt/c/Users/{WinUser}/AppData/Local/atom/bin /home/aaron/driver /home/aaron/Documents/git/python/bin /home/aaron/Documents/git/python/bin /home/aaron/pydir/bin/ /usr/bin /bin`

**Comment by dmitrij-drandarov** [comment]
I started getting the same error today

echo $PATH:
/home/dmitr/.pyenv/plugins/pyenv-virtualenv/shims:/home/dmitr/.pyenv/shims:/home/dmitr/.pyenv/bin:/home/dmitr/.sdkman/candidates/java/current/bin:/home/dmitr/.sdkman/candidates/gradle/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/WhitewaterFoundryLtd.Co.16571368D6CFF_1.4.0.0_x64__kd1vv0z0vy70w:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/w/Tools/choco/bin:/mnt/w/Tools/lxrunoffline:/mnt/w/Tools/NirLauncher/Nirsoft:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/PowerShell/7-preview:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/dmitr/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/dmitr/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/w/Tools/git/bin:/mnt/c/Users/dmitr/AppData/Roaming/npm

**Comment by aladd134** [comment]
I am not running docker, and the issue persists through terminating the environment

**Comment by aladd134** [comment]
it does seem that my virtualenv is deleting portions of my path variable on startup. removing the invocation from my config.fish file fixes the issue, and leaves me with a much more complete PATH variable 

<pre>`/home/aaron/.rbenv/shims /home/aaron/.rbenv/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /mnt/c/WINDOWS/system32 /mnt/c/WINDOWS /mnt/c/WINDOWS/System32/Wbem /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/ /mnt/c/WINDOWS/System32/OpenSSH/ /mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR /mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common /mnt/c/Program Files (x86)/Paragon Software/LinuxFS for Windows/ /mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL /mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL /mnt/c/Users/{WinUser}/AppData/Local/Microsoft/WindowsApps /mnt/c/Program Files (x86)/FAHClient /mnt/c/Users/{WinUser}/AppData/Local/atom/bin`</pre>
