### ISSUE TITLE
Missing pengwin icon from Windows right-click context menu.

### ISSUE THREAD

**Issue by eliranwong** [WhitewaterFoundry/Pengwin#565]
**Describe the bug**
Missing pengwin icon from Windows right-click context menu.

**To Reproduce**
1. Right-click a folder on Windows Explorer
2. "Open with Pengwin" appears on the context menu, but icon is a blank white squre

From Windows registry editor, I found that the icon path is set to:

> C:\Users\elira\AppData\Local\Packages\WhitewaterFoundryLtd.Co.16571368D6CFF_kd1vv0z0vy70w\LocalState\rootfs\usr\local\lib\pengwin.ico

However, I cannot find this file on my computer.

**Expected behavior**
I expect a nice official pengwin icon.

**Screenshots**
You can see the blank white squre icon from a screenshot at:

https://github.com/eliranwong/wsl2/blob/master/file_manager/thunar.md#launch-thunar-from-windows-context-menu

sorry, I don't know how to post an image here.

**Comment by patrick330602** [comment]
Thank you for reporting. This is a known bug, And we will fix it as soon as possible.

**Comment by eliranwong** [comment]
thanks, to fill in the gap before the fix, I downloaded the icon at https://github.com/WhitewaterFoundry/Pengwin/blob/master/DistroLauncher/images/icon.ico and correct the registry manually.

**Comment by patrick330602** [comment]
The issue is fixed. You can re-run to fix the issue.
