### ISSUE TITLE
Cannot start synaptic and cannot install firefox

### ISSUE THREAD

**Issue by zwwi** [WhitewaterFoundry/Pengwin#568]
**Describe the bug**

Synaptic could not be started. `sudo synaptic` leads to the following message:

```
Unable to init server: Could not connect: Connection refused
Failed to initialize GTK.

Probably you're running Synaptic on Wayland with root permission.
Please restart your session without Wayland, or run Synaptic without root permission
```
When I tried to install firefox, then I got the following message:
```
The following packages have unmet dependencies:
 firefox : Depends: libnss3 (>= 2:3.47.1~) but 2:3.45-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
`sudo apt update; sudo apt upgrade` did not help.

**Additional context**

I tried both wsl and wsl2, reset pengwin and reinstalled it. But still could not make it work.

On the other hand, both synaptic and firefox run very well in the Ubuntu WSL on the same laptop.

**Basic Troubleshooting Checklist**

[ *] I have searched Google for the error message.
[* ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[* ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[* ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here:  `1.4.0.0`

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Microsoft Corporation 389.2837.768, 8/21/2019
```

**Comment by patrick330602** [comment]
Hi zwwi,

Sorry for the inconvenience caused. Could you provide what items you have installed from `pengwin-setup`?

**Comment by zwwi** [comment]
Thank you for the prompt response!
I installed many:
For the GUI part, I installed FCITX, GUILIB, HIDPI, STARTMENU, SYNAPTIC, VCXSRV. 

I managed to start synaptic after further  installing `tklib` and `perl-tk` using `sudo apt` . 

Could you tell me how I can install firefox? It seems that libnss3 is outdated for firefox.

**Comment by crramirez** [comment]
Hello @zwwi 

For Firefox try this : 

`sudo apt install firefox-esr`

For synaptic install via pengwin-setup GUI->GUILIB

Regards,
Carlos

**Comment by zwwi** [comment]
Thanks! Firefox has been installed following your suggestion.
