### ISSUE TITLE
Pengwin only uses "unstable" and "testing" sources?

### ISSUE THREAD

**Issue by SturmB** [WhitewaterFoundry/Pengwin#569]
**Describe the bug**
Pengwin uses unstable and testing sources?

**To Reproduce**
1. Install Pengwin with default settings
2. See that the `sources.list` file includes only "unstable" and "testing"

**Expected behavior**
I expected Pengwin to use stable packages or at least something _other than_ unstable ones.

**Screenshots**
A small section of the result after doing `sudo apt update`:
![image](https://user-images.githubusercontent.com/6216224/71836278-babbb680-3081-11ea-8b02-c0d43a2237b4.png)

**Additional context**
After a modicum of research, I see that the [sources.list](https://github.com/WhitewaterFoundry/pengwin-base/blob/master/sources.list) file only lists "unstable" and "testing". Is this normal? I admit that I'm still a newbie with Linux, but this seems wrong to me.

**Basic Troubleshooting Checklist**

[✔] I have searched Google for the error message.
[✔] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[✔] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[✔] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[**(not necessary; this is on a virgin install.)**] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[**(not necessary; this is not a WSL issue.)**] I have disabled and re-enabled WSL in Windows Features.
[✔] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here: None needed.

**Pengwin Version**

Insert here: 1.4.0.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here: 
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Microsoft Corporation 531.2758.768, 6/6/2019
```

**Comment by crramirez** [comment]
Yes in fact Pengwin uses only testing and unstable. In Debian stable packages in general are too old for development and good for production. We decided to give priority in Pengwin to the newest packages assuming some broken ones.

We have Pengwin Enterprise and Fedora Remix which uses more stable packages. Also the Debian for WSL is based on stable. 

Regards

**Comment by SturmB** [comment]
Okay, thank you for the clarification, @crramirez.
