### ISSUE TITLE
Ignorefile for pengwin-backup

### ISSUE THREAD

**Issue by buehler** [WhitewaterFoundry/Pengwin#570]
**Is your feature request related to a problem? Please describe.**
During backup of the pengwin wsl distribution when using `pengwin-setup`, it does backup all files (which is as intended ;) in the $HOME directory.

Problem is now, as a developer, you'd likely have multiple folders, that should be excluded.

This would (for example) be:
- `.nvm` (node version manager) -> this folder has a cache for node modules, which definitely don't need to be backuped.
- `.cache` distribution cache folder

this are some examples among others.

**Describe the solution you'd like**
It would be nice to have a file in the $HOME directory (maybe `.backup-ignore` or something like that) in which one can exclude folders (and / or files) from backup. 

What do you think about this?

Regards and thanks for your effort

**Comment by crramirez** [comment]
Excellent suggestion. We will add it to the roadmap. It is useful for me also, but I didn't figure out the solution before your proposal.

**Comment by buehler** [comment]
Hey @crramirez 
Do you have any timeline about this feature? I still think it's a good idea to exclude those particular folders from the backup since it's just not practical without :-)

I'm really looking forward to this.

**Comment by crramirez** [comment]
Sorry I forgot telling you. This was included in our last release. 20.10.3

**Comment by buehler** [comment]
No worries, but is there some documentation? :-)

**Comment by crramirez** [comment]
No :-(

The file is ${HOME}/.pengwinbackupignore, and it is used directly as input to the tar command:

-X, --exclude-from=FILE
exclude patterns listed in FILE

**Comment by buehler** [comment]
So, as I understand; this is done right?
Can we close the issue?

**Comment by buehler** [comment]
or do you close it when documentation is done?

**Comment by crramirez** [comment]
It is done. We will create a separate task for the documentation.
