### ISSUE TITLE
subscription cancel

### ISSUE THREAD

**Issue by a-plain** [WhitewaterFoundry/Pengwin#572]
**Is your feature request related to a problem? Please describe.**
Cancel Sub-Script
RaftWSL

**Describe the solution you'd like**
Cancel Sub-Script

**Comment by crramirez** [comment]
Hello,

You can do it in your Microsoft account page. Go to the link that is inside the email that you received when you acquired the subscription.

We can't do anything from our side.

Regards

**Comment by a-plain** [comment]
thanks
