### ISSUE TITLE
Wrong user

### ISSUE THREAD

**Issue by a-plain** [WhitewaterFoundry/Pengwin#573]
**Is your feature request related to a problem? Please describe.**
pengwin-setup was ran with the user "root".
Run pengwin-setup from the defalt user and without sudo

**Describe the solution you'd like**
What should I do?
I did reinstall after uninstall.

**Comment by crramirez** [comment]
Hello,

Run pengwin-setup without sudo. Could you please send a screenshot of your command line window to verify?

Regards

**Comment by a-plain** [comment]
I did visudo.
root and username deleted.
I did reinstall after uninstall.
And then i can`t visudo.
What should I do?

**Comment by crramirez** [comment]
What happens when you execute `sudo visudo` ?

**Comment by WSLUser** [comment]
Honestly, I feel if you're already root, you should be able to run pengwin-setup and not just have to be a normal user. You can run sudo as root even though it does nothing.

**Comment by crramirez** [comment]
Indeed the problem is the Windows Path. If you run the distribution with root initially pengwin-setup will work: `wsl -d WLinux -u root`. But when you use sudo or su - you lose the environment and many of the installation scripts relly on the Windows Path

**Comment by WSLUser** [comment]
Ah that makes sense. So basically we need to append the Windows paths to the root user so it won't matter if a user already did `sudo su`. The path will be able to be read either way.
