### ISSUE TITLE
NodeJS LTS via Apt not working in pengwin-setup

### ISSUE THREAD

**Issue by elmima-michael** [WhitewaterFoundry/Pengwin#575]
**Describe the bug**
When I try to install NodeJS LTS via apt using pengwin-setup I get the error:
## Your distribution, identified as "bullseye", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**To Reproduce**
1. start pengwin-setup
2. chose Programming
3. Chose "NodeJS"
4. Chose "Yes"
5. Chose LTS and OK

Doesn't seem to be a PengWin issue but NodeJS not being ready for Debian 11.
It worked ok for me after temporarily setting "VERSION_CODENAME" to buster in /etc/os-release

**Comment by crramirez** [comment]
Thank you for reporting we will take a look

**Comment by crramirez** [comment]
Fox is coming please test: https://github.com/WhitewaterFoundry/pengwin-setup/pull/221
