### ISSUE TITLE
cannot launch a gui app via Windows PowerShell

### ISSUE THREAD

**Issue by eliranwong** [WhitewaterFoundry/Pengwin#577]
**Describe the bug**
cannot launch a gui app via Windows PowerShell running either wsl.exe or pengwin.exe run

**To Reproduce**
I can run on pengwin console or other Linux terminal, e.g.

> google-chrome

But when I tried the followings on Windows PowerShell, I got errors:

> wsl.exe google-chrome

> pengwin.exe run google-chrome

Error received on Windows PowerShell:
Failed to initialize Xfconf: Cannot autolaunch D-Bus without X11 $DISPLAY

remarks: I am using wsl2

**Expected behavior**
I hope I can launch gui app from PowerShell.

**Comment by crramirez** [comment]
Hello,

You need to login into bash so /etc/profile get executed:

`pengwin.exe run "bash -l -c google-chrome"`

Test it and tell me if it work.

Regards,
Carlos

**Comment by eliranwong** [comment]
Thanks Carlos,  It works, appreciate your help.  Thanks.
