### ISSUE TITLE
Installing Python using pyenv creates an error in .bashrc

### ISSUE THREAD

**Issue by Kalaschnik** [WhitewaterFoundry/Pengwin#578]
**Describe the bug**
I was performing a clean install of 20H1 (19041) and installing Pengwin. I chose to install Python using pyenv. After installation I noticed the bash showing:

`.bashrc: line 116: syntax error: unexpected end of file`

I found the error, when inspecting the .bashr: notice the third line from the bottom:

```
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fiexport PATH="/home/steven/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

Line breaking `fiexport PATH="/home/steven/.pyenv/bin:$PATH"` into

```
fi
export PATH="/home/steven/.pyenv/bin:$PATH"
```
was fixing the issue when loading the .bashrc, and it would likely fix issues regarding pyenv.

**Pengwin Version**

1.4.1.0

**Windows Build**

19041.21

**Comment by crramirez** [comment]
Excellent,

Thank you for reporting

**Comment by crramirez** [comment]
I couldn't reproduce but added a blank line just in case
