### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by SturmB** [WhitewaterFoundry/Pengwin#579]
**Describe the bug**
`PWD` from the home folder returns `/home/<username>`, which appears to be incompatible with Docker Desktop.

**To Reproduce**
1. Install Docker Desktop.
2. Install Pengwin.
3. Run `pengwin-setup` and install the Docker "secure bridge."
4. Create a simple docker image.
  a. From the home folder, `mkdir test`.
  b. Navigate to it: `cd test`.
  c. Give it a `dockerfile` with the following contents:
```
FROM alpine:3.9.5

RUN mkdir /app
WORKDIR /app

COPY . .

CMD sleep 1h
```
  d. Create a Docker image with `docker image build -t test1 .`.
5. Run a container of the image with a volume mapping of the current folder to the `/app` folder inside the container: `docker container run -it --rm --name test1 -d -v $PWD:/app test1`. (This container will just sleep detached for an hour.)
6. Connect to the container: `docker container exec -it test1 sh`.
7. In a new terminal window, `cd test` and create a new file, `touch hi.txt`.
8. Back in the previous terminal window, `ls -la` to notice that the new file is **not** showing.

**Expected behavior**
I would expect that using `$PWD` from the home folder as a part of any volume mapping with a Docker container would be picked up by the bridge that `pengwin-setup` created to Docker Desktop and mapped correctly to the Pengwin home folder. Or I could just be not understanding the Docker/bridge process at all. Either way, I need something (`$PWD` or otherwise) to point Docker to the Pengwin home folder for volume mapping purposes.

**Screenshots**
Probably not needed, but available upon request.

**Additional context**
I'm trying to go through Nick Janetakis' [Dive into Docker](https://nickjanetakis.com/courses/) tutorial series and am stuck on Chapter 6, Lesson 7: "Live Code Reloading With Volumes".

**Basic Troubleshooting Checklist**

[✔] I have searched Google for the error message.
[❌] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
**This is not a WSL-specific problem, as far as I can tell.**
[✔] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[✔] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[❌] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset.
**I refuse to "reset" Pengwin after I have carefully gotten it set up the way I need it. WAAAAAAY too much trouble for what I am almost 100% sure won't make a difference.**
[❌] I have disabled and re-enabled WSL in Windows Features.
**Again, this is not a WSL-specific problem.**
[✔] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?
Nick himself uses WSL and wsltty, so I've reached out to him for help with this as well. In addition, I am consulting the aforementioned course's forum.

Insert here:

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: **1.4.1.0**

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here: **18362**

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello,

Don't your Linux home with docker, instead use your Windows one. Remember docker is running in windows. 

Regards

**Comment by SturmB** [comment]
Yeah, this is the conclusion to which I am rapidly coming. That didn't sound right, despite being grammatically correct. Anyway…

The Docker tutorial course I mentioned in my original post even did touch on the issue, but only briefly and didn't mention WSL, so I figured that Pengwin and its Docker "secure bridge" would allow me to get around the idea of using an absolute path with container volume mappings. Long story short: it doesn't. (I've no idea if WSL2 will address this when it is released later this year. I doubt it.)

Thanks for taking the time to respond, crramirez.

**Comment by crramirez** [comment]
You are welcome. Docker for WSL2 resolves this beautifully and it is 100% compatible with Pengwin or at least how it is working in Insider versions.
