### ISSUE TITLE
CLion doesn't recognize Pengwin authentication

### ISSUE THREAD

**Issue by magneticflux-** [WhitewaterFoundry/Pengwin#581]
**Describe the bug**

When using WSL support in CLion with Pengwin, it says "Credentials are not valid for this WSL distribution (Pengwin)" even after running `ssh-copy-id` and double-checking my password.

**To Reproduce**
1. Start Pengwin and set up SSH access according to Intellij docs [here](https://www.jetbrains.com/help/clion/how-to-use-wsl-development-environment-in-clion.html).
2. Add a WSL toolchain in CLion
3. Insert the correct credentials
4. Test the toolchain

**Expected behavior**

The toolchain connects.

**Screenshots**

![image](https://user-images.githubusercontent.com/9124288/73598855-d7250480-4502-11ea-9b78-9bdb45eaf532.png)

**Additional context**

N/A

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[x] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

- I am able to connect with an SSH client.
- I am able to use the Ubuntu WSL toolchain.
- I am able to use the "Remote" toolchain over SSH.

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: `1.4.1.0`

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

```
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.19551 N/A Build 19551
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Insyde Corp. V1.22, 3/15/2019
```

This is being tracked on the JetBrains side here: https://youtrack.jetbrains.com/issue/CPP-18842

**Comment by crramirez** [comment]
Hello,

Thank you for reporting. The error is in a file that JetBrains products have to list the distributions. They just need to change a file commit and push. At least is what I think. They need to raise the priority of this. 

Meanwhile we made a workaround in pengwin-setup. Run pengwin-setup -> PROGRAMMING -> C++ it will patch your wsl.distributions.xml and also enable ssh and install cmake. Do it every time you install a major version of CLion.

Regards 
Carlos

**Comment by magneticflux-** [comment]
That appears to have fixed it, thank you!

![image](https://user-images.githubusercontent.com/9124288/73611319-7a7b2580-45a6-11ea-98ce-7e3bd73341f8.png)

**Comment by wyattsmcall1** [comment]
I don't understand where pengwin-setup is

**Comment by crramirez** [comment]
Just run from Pengwin command prompt the following command:

`pengwin-setup install PROGRAMMING C++`

Regards

**Comment by wyattsmcall1** [comment]
Sorry.  How do I get to the Pengwin command prompt?

**Comment by wyattsmcall1** [comment]
I installed penguin from the windows store and ran the command and the issue still appears in clion.

**Comment by crramirez** [comment]
OK that's strange it should have fixed it.

Run this :

pengwin-setup install PROGRAMMING JETBRAINS

if this doesn't solve the issue, probably you are experiencing another one and I will request from you more information.

Regards

**Comment by wyattsmcall1** [comment]
It still does not fix it. However, I think that I need to enable virtualization in my BIOS. I am asking my IT department to help with this (I am on my work PC).

**Comment by wyattsmcall1** [comment]
I turned on virtualization and I still have the issue.

**Comment by crramirez** [comment]
Hello @wyattsmcall1

I need more information in order to help you. Can you please write me to contact@whitewaterfoundry.com

Regards
