### ISSUE TITLE
pengwin-setup does not install node via nvm

### ISSUE THREAD

**Issue by haodeon** [WhitewaterFoundry/Pengwin#584]
**Describe the bug**
When installing nodejs via nvm in pengwin-setup, one of the steps is (line 169)

`nvm install "$(nvm ls-remote | tail -1 | sed -e 's|^\s||g')" --latest-npm`

This does not appear to work. No version of node is installed after setup finishes.
Running this command manually produces an error about "version not found" or similar.
Running the command manually and inserting the result of `nvm ls-remote` does produce expected behaviour.

**To Reproduce**
pengwin-setup
select Ok
select Yes
enter password
select programming
select Ok
select nodejs
select Yes
select nvm
select no (to install yarn)

**Expected behavior**
node to be installed after running pengwin-setup

**Additional context**
I would suggest, instead of fixing what is broken, to simply replace the command with

`nvm install --lts --latest-npm`

This is far more useful IMO.

**Basic Troubleshooting Checklist**

Yes I have google-fu'ed

**What other troubleshooting have you attempted?**

Manually running the nvm command which is broken - I have reported on this above

**Pengwin Version**

1.4.1.0

**Windows Build**

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. E16Q4IMS.116, 7/10/2019

**Comment by patrick330602** [comment]
Hi,
Sorry for the inconvenience caused. We will look into it and fix it
