### ISSUE TITLE
Pengwin with X410 not working

### ISSUE THREAD

**Issue by thargy** [WhitewaterFoundry/Pengwin#586]
**Describe the bug**
On a clean install of freshly purchased pengwin on WSL 2, with clean install of X410 running (purchased because it was recommended by pengwin).  Installed everything in GUI sub-menu of `pengwin-setup`.  When installing Windows 10 theme get `Error: cannot open display:`.  When running `lxappearance` from command line, just hangs for a while before reporting same error.  

Installed VSCode, typing `code .` returns but didn't open VSCode!

 `glxgears` gives `Error: couldn't open display 192.168.86.35:0.0` error.

This gave me the hint that it was configured to the external IP address and not 127.0.01.  Enabling 'Allow Public Access' on X410 (note this is disabled on X410 on a clean install) then allowed the above allowed VSCode and glxgears to work.  However, running `lxappearance` gave:
```
(lxappearance:14921): GLib-GIO-CRITICAL **: 01:27:16.705: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(lxappearance:14921): GLib-GIO-CRITICAL **: 01:27:16.705: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed`
```
But did run the window.

I appreciate these are 'noob' issues, but I paid for Pengwin and X410 to get an easy setup experience, and it left me struggling for a good couple of hours.

How do I setup to avoid having X410 needing to 'Allow Public Access'?

Thanks

**Comment by thargy** [comment]
Also should mention that having needed to reinstall after following bug submission guidelines, I again got the error `run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/ipconfig.exe` on first boot.

**Comment by patrick330602** [comment]
Hi,

This is the limitation of WSL2. If you use WSL2, you have to use 'Allow Public Access', regardless of which X server you are using. 

For the error, it is the limitation of WSL/WSL2 itself. It is normal and can be ignored.

For the `run-detectors` problem, we will try to investigate the problem.

**Comment by thargy** [comment]
Thanks! Is there a way to surface this in the setup app?  For example, during setup of GUI check if an external IP is configured and/or if WSL 2, and if a connection to an XClient isn’t found warn/recommend X410 and mention the setting?  Or at least put it as a warning on the link for X410 recommendation when running under WSL 2.

It really wasn’t obvious what was going on.

**Comment by patrick330602** [comment]
Thanks for the suggestion, it would be a great idea

**Comment by crramirez** [comment]
Hello,

Starting X410 with Allow Public Access is something that was kindy fixed by one collaborator and will be available soon: https://github.com/WhitewaterFoundry/pengwin-setup/pull/222

Any case it is described here in the X410 page https://token2shell.com/howto/x410/using-x410-with-wsl2/

The run-detectors problem it is an upstream issue of wsl2 can be solved running wsl --shutdown in Windows command line.

Do you know? It is very annoying reading descriptions remembering us that you paid.

Regards

**Comment by thargy** [comment]
Hi @crramirez, thanks for the links.

> Do you know? It is very annoying reading descriptions remembering us that you paid.

I raised the issue because I found Pengwin through a Scott Hanselmann video recommending it and going to the MS Store, not through GitHub and I didn't initially realise it was Open Source.  I paid _because_ it promised to be _"the first Linux distribution optimized for Windows Subsystem for Linux (WSL)."_ on the store and _"Pengwin is the easiest to use Linux distribution on Windows Subsystem for Linux."_ on the web page; and I was willing to put cash down to have things 'just work'.  I had previously just installed Ubuntu and VcXsrv without too many issues but wanted to be sure I had my environment configured optimally.

I then bought X410 because throughout the install it was recommended, and the [Pengwin website](https://www.whitewaterfoundry.com/) explicitly says _"Many Linux GUI applications run on Pengwin with a third-party X server installed on Windows. Choose from X410, VcXsrv, Xming, or Xmanager. **We recommend X410**. Pengwin ships with custom settings to improve GUI application performance on Windows."_

All this is _important context_, because, you will note from my issue, _I fixed the problems myself_ and so I felt I needed to explain why I was raising the bug reports.  I raised the bug reports because the experience I had with Pengwin was counter to what I believed was the developers intent - that I would have an easy, seamless, curated setup.  It was inferior to the experience I had with the recommended _free_ approach; and as such would rapidly lead to annoyed customers leaving bad reviews on the MS Store.  Rather than doing that (leaving terrible reviews), I sought out the project site and tried to leave some _constructive feedback_ - not least in the hope that someone else might find the issue and fix the problem themselves more quickly than I had.

In all that I wrote I mention paying for it _exactly once_ and I still think that context was important.  It wasn't a passive-aggressive dig, it was an important context and would not be obvious that I paid for the app, without stating it - this being an Open Source project.

Finally, I have reread the bug submission guidelines and there is no embargo on mentioning paying for the software.  If it is annoying, maybe you should consider adding something there?

In the meantime, I apologise for having caused you offence, albeit was unintentional, and will refrain from mentioning paying in future.
