### ISSUE TITLE
No Update Capability Found

### ISSUE THREAD

**Issue by robomac** [WhitewaterFoundry/Pengwin#593]
PengWin does not support the Windows standard mechanism for updates.  Cannot update from the Store, and no clear way to do so from the app.

The HowTo page (https://github.com/WhitewaterFoundry/Pengwin/wiki/HowTo%E2%80%99s) is empty, as is the FAQ.  (Sort of makes me wonder why you have them.)

**To Reproduce**
Install a version several months ago.  Note new version listed in store.  No ability to update.

To Fix: I presume the solution is to run pengwin-setup and let it do its thing.  But this isn't obvious, especially long after you've installed.  This should be linked elsewhere.

**Comment by crramirez** [comment]
Hello,

As you can see in the following tweet, we just launched the how-to page. So, for you, the answer is that we are filling it and it is not fair for the community if we make it available some years after when it is full. Right?

![image](https://user-images.githubusercontent.com/8397379/76708450-2744d880-66f7-11ea-8976-6456c2ffa8ad.png)

To update Pengwin as any other WSL just use the distro built-in mechanism for updates:

`sudo apt update && sudo apt upgrade` this works for Pengwin, Ubuntu, Debian, and Kali.

As per your suggestion, we will update our How-To page with a topic regarding the update.

Thank you for reporting.

**Comment by robomac** [comment]
> Hello,
> 
> As you can see in the following tweet, we just launched the how-to page. So, for you, the answer is that we are filling it and it is not fair for the community if we make it available some years after when it is full. Right?
> 
> ![image](https://user-images.githubusercontent.com/8397379/76708450-2744d880-66f7-11ea-8976-6456c2ffa8ad.png)
> 
> To update Pengwin as any other WSL just use the distro built-in mechanism for updates:
> 
> `sudo apt update && sudo apt upgrade` this works for Pengwin, Ubuntu, Debian, and Kali.

Good grief.  Seriously?

**Pro-Tips:**

1. "Tweets" are not a form of documentation.  I don't use Twitter.  But the Pengwin blog (yes, you have one) didn't mention this.  
2. Windows Store users are likely less linux-ey than general Linux users, and may not even think about apt update.  I didn't assume it would cover Pengwin.  You still should link it from the Store.

**Comment by crramirez** [comment]
https://www.whitewaterfoundry.com/blog/2019/6/5/pengwin-125-released-see-whats-new-and-whats-coming-next and in many other, we mention how to update.

![image](https://user-images.githubusercontent.com/8397379/76708914-ebac0d80-66fa-11ea-9687-5b4fbfffd484.png)

We will take your suggestions into consideration and out this information more visible in Windows Store, probably at the head of "What's new"

Regards

**Comment by crramirez** [comment]
Update: We added this message on top of What's new in Microsoft Store to increase the visibility of the procedure:

![image](https://user-images.githubusercontent.com/8397379/77422112-3b5e9900-6dcd-11ea-919e-d37b3eb0f3e8.png)
