### ISSUE TITLE
Basic features broken. Cannot use it as intended (development tool). I want a refund.

### ISSUE THREAD

**Issue by clockelliptic** [WhitewaterFoundry/Pengwin#594]
Basic features are broken. Had to fix missing command `apt-add-repository` immediately. Multiple installed packages are not being recognized by my build tools. All of these things work flawlessly on Ubuntu for WSL. 

Respectfully, I want a refund, as I simply don't have time to clean up broken fundamental features of an operating system at this point in my career.

Thank you for your time. Installation was very easy. 

I will happily purchase Pengwin when it works as flawlessly for WSL dev purposes as Pop_OS (Ubuntu variant maintained by System76) does as a standalone linux distro.

**Comment by crramirez** [comment]
Hello,

For a refund forward your Store confirmation e-mail to contact@whitewaterfoundry.com. Include your email attached to your Paypal account.

As per your suggestion, we will consider adding apt-add-repository as preinstalled. 

Best wished in your career,
Regards,
Carlos
