### ISSUE TITLE
Extend GUILIBS to install libnss3 and libegl1-mesa

### ISSUE THREAD

**Issue by Kalaschnik** [WhitewaterFoundry/Pengwin#596]
I had a hard time to get RStudio running in WSL 2 [see my gist](https://gist.github.com/Kalaschnik/177a30bd02c9438fee1a93686fe60735). Eventually, I need to install two packages (after installing GUILIB) to get RStudio running (as pointed out [here](https://gist.github.com/Kalaschnik/177a30bd02c9438fee1a93686fe60735#install-other-gui-dependencies-pengwin)):
- libnss3
- libegl1-mesa

It might be the case that there are other GUI applications out there, which also require these packages. Thus, adding them to the GUILIB installations might save some time for users.

**Comment by crramirez** [comment]
Great suggestion. Thank you

**Comment by crramirez** [comment]
OK after reading your gist. Probably if you run GUILIB again on WSL1 it will work with RStudio because it patch the libqt5. But probably the performance could be bad.

We can also if you wish include an RStudio installer in pengwin-setup or at least add your instructions in our how to page.

**Comment by Kalaschnik** [comment]
I actually tested it in WSL 1 before converting to WSL 2 using the same steps.... anyway WSL 1 is past :) Feel free to use the instructions.
