### ISSUE TITLE
How to install Certbot / ppa

### ISSUE THREAD

**Issue by jimmerk** [WhitewaterFoundry/Pengwin#597]
I've tried installing Certbot for Nginx, but I was unsure about instructions that mentioned the Canonical 'universe' repo. Is there an equivalent repo that I should be using to install Certbot on Pengwin? And is there a simple way to install Certbot?

**Comment by crramirez** [comment]
Hello,

For Pengwin use the instructions for Debian/testing:

![image](https://user-images.githubusercontent.com/8397379/77806293-9bcb3000-7084-11ea-96f9-51934e1f9138.png)

I will test and be right back.

Regards

**Comment by crramirez** [comment]
Run:

`sudo apt-get install certbot python3-certbot-nginx`

**Comment by jimmerk** [comment]
Thank you! That worked. I hadn't thought of using python3. duh.
