### ISSUE TITLE
Logging in as root Pengwin shows "Updated configuration for WSL1" message

### ISSUE THREAD

**Issue by DubbleClick** [WhitewaterFoundry/Pengwin#599]
**To Reproduce**
1. Type `su -`
2. Enter password
3. Be presented with `Updated configuration for WSL1. Restart Pengwin to apply changes.`
4. Restarting Pengwin gives `Updated configuration for WSL2. Restart Pengwin to apply changes.`

**Expected behavior**
It says on WSL2 even when logging in as root.

**Screenshots**
![image](https://user-images.githubusercontent.com/7896469/78005681-36a16400-733c-11ea-94a2-f127d04d7bb7.png)

**Comment by crramirez** [comment]
Got it. Thanks for reporting. But don't worry it won't switch you to WSL1 this is only a message.

**Comment by crramirez** [comment]
We released a fix for this. Please test.

**Comment by DubbleClick** [comment]
Can't see an update in the Windows Store, do I have to update manually?

**Comment by crramirez** [comment]
Hello just do a:

`sudo apt update &&  sudo upgrade`

Yes you need to upgrade manually or reset the distribution and create it again. 

Regards

**Comment by DubbleClick** [comment]
Understood, works fine now. #closed
