### ISSUE TITLE
using ubuntu 18.04lts its unable to locate package libgnutls-openssl it is still unable to clone git on the terminal it outputs ........error in the push function what should i do pliz 

### ISSUE THREAD

**Issue by biggy970** [WhitewaterFoundry/Pengwin#607]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by crramirez** [comment]
Please describe better the issue I don't understand anything that is happening to you

**Comment by ThatWeirdAndrew** [comment]
I believe that they are having the same issue as #153

**Comment by crramirez** [comment]
Looks like. I haven't had this problem, as I understand this is due to and antivirus or an internet connection? They mention ubuntu, git clone and push in the same sentence, so  let's wait if they can describe it better :S
