### ISSUE TITLE
Connection Error on Startup

### ISSUE THREAD

**Issue by jimmerk** [WhitewaterFoundry/Pengwin#608]
Getting this error in WSL2...

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

[process exited with code 4294967295]

**Comment by jimmerk** [comment]
Removed some unnecessary entries from my PATH and restarted...works fine now.

**Comment by crramirez** [comment]
This is the first time I see this error. Happy that you could solve it
