### ISSUE TITLE
Mariadb not getting installed from pengwin-setup with latest updates

### ISSUE THREAD

**Issue by theandrewb** [WhitewaterFoundry/Pengwin#614]
**Describe the bug**
Hello, love the distro but I've found my first bug. When starting a fresh install and using pengwin-setup to install a LAMP stack, mariadb is not getting installed properly if you do the suggested updates (or apt-get update) first. I've tried this a few times now, and have only gotten it working by declining the updates.

**To Reproduce**
1. Install
2. pengwin-setup
3. Select "yes" when asked to update
4. Choose "Services," then "Install LAMP stack"
5. Notice that you will not be prompted for a mariadb version
6. Once finished, "sudo service mariadb" will give "unrecognized service" error

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: 20.6.2.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here: 
Microsoft Windows [Version 10.0.18363.900]                                                                              (c) 2019 Microsoft Corporation. All rights reserved.                                                                                                                                                                                            C:\Users\Andrew>systeminfo | findstr /C:"OS"                                                                            OS Name:                   Microsoft Windows 10 Home                                                                    OS Version:                10.0.18363 N/A Build 18363                                                                   OS Manufacturer:           Microsoft Corporation                                                                        OS Configuration:          Standalone Workstation                                                                       OS Build Type:             Multiprocessor Free                                                                          BIOS Version:              American Megatrends Inc. 1502, 6/26/2019 

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello,

Thank you for reporting. I will take a look.

Regards,
Carlos

**Comment by crramirez** [comment]
Hello,

We submitted a patch. Could you make a test?

Regards,
Carlos

**Comment by theandrewb** [comment]
Hi Carlos,

I just tested it. Looks like it works now. That was quick!

Thanks,
Andrew B.
