### ISSUE TITLE
Problem running Docker on WSL2

### ISSUE THREAD

**Issue by symbiont-val-melamed** [WhitewaterFoundry/Pengwin#616]
**Describe the bug**
I am not sure if this is a bug or I did something incorrectly but the problem was that running any docker command would display an error, e.g.
`docker run hello-world`
**docker: Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?.
See 'docker run --help'.**
After digging around I found out that if I `unset DOCKER_HOST` the problem goes away and `docker run hello-world` displays the usual **Hello from Docker! ... etc**

I have the feeling that this is related to the "small" problem during `pengwin-setup`: when it comes to installing docker it always displays:
```
Please go to Docker Desktop -> Settings -> General and enable 'Expose
daemon on tcp://localhost:2375 without TLS' or upgrade your Windows
version and run this script again.
```
But both Windows (Pro Insider) and Docker Desktop are the latest version. Also 'Expose
daemon on tcp://localhost:2375 without TLS' is checked.

**Expected behavior**
I don't need to `unset DOCKER_HOST` or it should not be defined at all.

**Additional context**
As a workaround for now, how do I remove the emv.variable `DOCKER_HOST` to begin with. I do not see it in .zprofile or .zshrc?

**Basic Troubleshooting Checklist**

[* ] I have searched Google for the error message.
[* ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[* ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[* ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?
See description

**Pengwin Version**

20.6.2.0

**Windows Build**

OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.20161 N/A Build 20161
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 1.16.2, 4/21/2020

**Comment by crramirez** [comment]
Hello,

Did you upgrade your distro from WSL1 to WSL2? If it is the case go to pengwin-setup and uninstall Docker. Then use the built in integration in Docker Desktop.

If you are in WSL1 uninstall doxker with pengwin-setup and install it again.

Regards

**Comment by symbiont-val-melamed** [comment]
Yes, I have a fresh WSL2 + pengwin - just a few days old.
I uninstalled docker (could not find how to uninstall things with `pengwin-setup`...?) by:

```bash
sudo apt-get purge docker-engine
sudo apt-get autoremove --purge docker-engine
rm -rf /var/lib/docker
```
Restarted WSL but I still need to `unset DOCKER_HOST` to make it work. Am I doing something wrong here?

I am sorry for the "support question" but is there any documentation for `pengwin-setup`. I was trying to figure out how to uninstall docker with it but couldn't find it and had to do it manually as above. A document that describes where in the menu is installed what component, what not to install with WSL2 (like docker and vscode) would be very helpful and :) probably would save you guys a lot of silly questions like mine here.

**Comment by crramirez** [comment]
Hello,

No problem it is a support forum, so your support questions are welcome.

Look again in pengwin-setup main menu there is a UNINSTALL. Then scroll until you find docker.

Regards

**Comment by symbiont-val-melamed** [comment]
Thank you! That did it.

**Comment by aborruso** [comment]
Hi @crramirez ,
if I run `docker run hello-world` I have

```
docker: Cannot connect to the Docker daemon at tcp://localhost:2375.
```

If I run `unset DOCKER_HOST` I solve it.
I have already uninstalled docker using pengwin-setup.

I have `PENGWIN_VERSION="21.2.0"`.

How to solve it?

Thank you

```
WSL Version: 2
Locale: it_IT
Release Install Date: Wed Jun  3 16:19:27 CEST 2020
Branch: vb_release
Build: 19042
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 1
Windows Theme: light
Windows Uptime: 0d 1h 53m
WSL Uptime: 0d 1h 52m
WSL Release: Pengwin
WSL Kernel: Linux 4.19.104-microsoft-standard
Packages Count: 1129
```

**Comment by aborruso** [comment]
I have solved. I had in ~/.zshrc

```
export DOCKER_HOST=tcp://localhost:2375
```

I have commented it
