### ISSUE TITLE
pengwin-setup, apt-get, man apt-get, nothing works in Pengwin Enterprise

### ISSUE THREAD

**Issue by PengwinEnterpriseUser** [WhitewaterFoundry/Pengwin#617]
So, I enable WSL,, pay for and install Pengwin Enterprise from the Microsoft Store, bring up the Pengwin Enterprise command window, type in pengwin-setup at the prompt and I get "-bash: pengwin-setup: command not found" as a response.  Then I type in apt-get, and the response is, "-bash: apt-get: command not found".  Then I type in man apt-get and the response is, "No manual entry for apt-get".  So shouldn't something work on this?  Am I missing something here?

Thanks.

**Comment by crramirez** [comment]
Yes, you should have read the description for Pengwin Enterprise which says that it is  based on Scientific Linux so it is a Red Hat compatible distribution. For install packages you must use yum. Also in the description it says that it doesn't include pengwin-setup.

Forward us your Microsoft purchase email to contact@whitewaterfoundry.com and we can help.

Regards,
Carlos

**Comment by PengwinEnterpriseUser** [comment]
Actually, I did read a lot of stuff.  It is not so well organized as it is distributed across various GitHub pages.  Sometimes I miss top level obvious things.

 

So I was actually looking for that sort of info, whether it is more of the Red Hat family or the Debian Family.  So you are basicially saying that Pengwin is a Debian type disto and Pengwin Enterprise is Red Hat type disto .  Where exactly does  it say that?  I was looking at a YouTube video by the founder and he was saying that it is a Debian type disto.  The company should really publish a book or a user guide or something.

 

I really don't have a problem working with either.  Actually I think I'd prefer a Red Hat family distro other than the fact that it looks like the Debian family looks to be better supported with applications.

 

Asking for an email huh?  Well, I think I deleted it.  Here's (below) a cut and paste from the microsoft store account page.

 

By the way, I put Penguin Enterprise on my work desktop, on my personal notebook and on my personal desktop.  I only paid $9.99 for the first copy a few days ago but the other two cost about $100.00 each.  I already opened a support case with out IT department as I can't get the \\wsl$ <file:///\\wsl$>  folder to show up in explorer.  I figure that they have some sort of network restriction going on.  Right now I’m working with my home desktop, the one that I purchased today.

 

Thanks!

 

Roger

 

 

 



 

Thanks!

 

Roger

**Comment by crramirez** [comment]
Sorry for the confusion. The information that I mentioned is in the description of the page of Pengwin Enterprise in the Microsoft Store page.

The founder is working on a book that soon will be released. And you are right that we need to work in a user guide.

We need to make it clear that Pengwin and Pengwin Enterprise are not the same in more places.

I answered your email.

Hope it helps.

**Comment by crramirez** [comment]
Check that your Windows version is 1903 or newer the \\wsl$ is anything related to network issues.

**Comment by PengwinEnterpriseUser** [comment]
Thanks.  Actually, I don't think the work desktop is.  I looked at that before I installed Pengwin Enterprise.

 

Roger
