### ISSUE TITLE
pengwin-setup not installing powershell

### ISSUE THREAD

**Issue by juliosegarra** [WhitewaterFoundry/Pengwin#620]
When using the pengwin-setup tool and trying to install PowerShell, I get this error:
![image](https://user-images.githubusercontent.com/42501108/88321308-f0a64c80-ccec-11ea-9616-e035be2415d9.png)

I also tried installing through apt and I got this: 
![image](https://user-images.githubusercontent.com/42501108/88321407-1f242780-cced-11ea-9b8f-eb558d42f0ff.png)

**To Reproduce**
1. Go to 'pengwin-setup'
2. Click on 'tools'
3. Scroll down and select 'powershell'
4. Enter and yes to install
4. See error when it cancels and loops back to menu

**Expected behavior**
Install powershell.

**Basic Troubleshooting Checklist**

[ ] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

I've taken these basic troubleshooting steps along with trying to go through apt and searching for the problems there but to no avail.

**Pengwin Version**

![image](https://user-images.githubusercontent.com/42501108/88321812-c7d28700-cced-11ea-8c4e-ce7f1c593641.png)

**Windows Build**

![image](https://user-images.githubusercontent.com/42501108/88321761-ad98a900-cced-11ea-942d-a71c330d08bd.png)

**Comment by crramirez** [comment]
Hello,

We will check. Thank you for reporting

**Comment by crramirez** [comment]
Hello,

The patch is coming. Meanwhile, execute the following and install powershell again from pengwin-setup:

`echo 'deb https://deb.debian.org/debian stable main' | sudo tee /etc/apt/sources.list.d/stable.list`

Regards,
Carlos

**Comment by juliosegarra** [comment]
@crramirez worked great, thank you very much.
