### ISSUE TITLE
Unable apt-get install binutils

### ISSUE THREAD

**Issue by doggy8088** [WhitewaterFoundry/Pengwin#621]
**Describe the bug**

I can't install most of the apt packages.

**To Reproduce**

1. Just run the following command:

    ```sh
    sudo apt-get install binutils -y
    ```

2. See error

    ```txt
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    You might want to run 'apt --fix-broken install' to correct these.
    The following packages have unmet dependencies:
    binutils : Depends: binutils-common (= 2.34.90.20200706-1) but it is not going to be installed
                Depends: libbinutils (= 2.34.90.20200706-1) but it is not going to be installed
                Depends: binutils-x86-64-linux-gnu (= 2.34.90.20200706-1) but it is not going to be installed
    libc-bin : Depends: libc6 (< 2.31) but 2.31-1 is to be installed
                Recommends: manpages but it is not going to be installed
    locales : Depends: libc-bin (> 2.31) but 2.30-8 is to be installed
    E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
    ```

**Expected behavior**

Install packages successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/88981/88396577-4ebe5700-cdf5-11ea-8178-1bec3aa386d3.png)

**Additional context**

It's a fresh installed Pengwin on my WSL 2.

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[x] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here: https://stackoverflow.com/a/61697214/910074

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: `20.6.2.0`

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

```log
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. 0401, 2018/8/31
```

**Comment by crramirez** [comment]
Hello,

Thank you for reporting. We are actively working to provide the best solution for this. This is caused by an upstream change in Debian that affects WSL1. I see you have Windows 10 2004, if you can switch Pengwin to WSL2 this problem gets solved.

`wsl.exe --set-version WLinux 2`

https://docs.microsoft.com/es-es/windows/wsl/install-win10#update-to-wsl-2

Hope it helps

**Comment by doggy8088** [comment]
It works. Thanks! 👍
