### ISSUE TITLE
libc6 Update Breaks libc6-dev and Associated Libraries

### ISSUE THREAD

**Issue by PeteSL** [WhitewaterFoundry/Pengwin#623]
The just released libc6 2.31-1.wsl which apparently fixes the script error in the libc6 2.31-1 package installer breaks all dependencies.  This includes (but not limited to) libc6-dev and all associated development libraries.
`The following packages have unmet dependencies:
 libc6-dev : Depends: libc6 (= 2.31-1) but 2.31-1.wsl is to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by crramirez** [comment]
Thanks a lot for reporting. We have uploaded more packages. Could you try again after a `sudo apt update` ?

Regards

**Comment by PeteSL** [comment]
libc-dev-bin libc6 libc6-dev updated to the 2.31-1.wsl version and looks correct.  I had changed to WSL2 to accommodate the sleep issue and will report here after converting back to WSL1. (BTW, I am running Win 10 2004).

**Comment by PeteSL** [comment]
WSL1 working as well. "sleep" in /bin is also now working properly in WSL1.  Sure would be nice for MS to fix this in the WSL1 (they say they have but you have to be on the fast track OS for the fix).  Maybe the next CU for Windows 10 will include it...

**Comment by crramirez** [comment]
Excellent thanks for testing. We are still generating the packages for ARM64
