### ISSUE TITLE
Where is dotnet?

### ISSUE THREAD

**Issue by symbiont-val-melamed** [WhitewaterFoundry/Pengwin#625]
**Describe the bug**
In `pengwin-setup` checked install DOTNET and NuGET but after that when I try to execute `dotnet` I get `zsh: command not found: dotnet`.

**To Reproduce**
1. Go to 'pengwin-setup'
2. Click on 'PROGRAMMING -> DOTNET'
3. When finished, execute `dotnet`

**Expected behavior**
The command should display usage, options, etc.

**Screenshots**
N/A

**Additional context**
Curiously `nuget` is installed and seems to be working fine.
Seems to be related to https://github.com/WhitewaterFoundry/Pengwin/issues/483 - I was getting the same in VSCode.
Also https://github.com/WhitewaterFoundry/Pengwin/issues/337.

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here:
20.7.0.0
`zshell`

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

```
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.20180 N/A Build 20180
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 1.2.1, 6/1/2020
```
For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello,

Thanks for reporting. We will check it.

Regards,
Carlos

**Comment by crramirez** [comment]
Hello,

The patch is comming. Meanwhile, execute the following and install dotnet again from pengwin-setup:

`echo 'deb https://deb.debian.org/debian stable main' | sudo tee /etc/apt/sources.list.d/stable.list`

Regards,
Carlos
