### ISSUE TITLE
Npm / Yarn cannot find modules inside docker

### ISSUE THREAD

**Issue by mjmaix** [WhitewaterFoundry/Pengwin#627]
**Describe the bug**
There are errors when running dockerized application. I tried it on WSL2 Ubuntu 20.04 and it was working. Error only happens on Pengwin. I installed latest NodeJS stable and npm. I can run the application outside docker just fine so NPM installation is ok.

Error from docker logs

```
/home/node/app/node_modules/resolve/lib/sync.js:76
app        |     throw err;
app        |     ^
app        |
app        | Error: Cannot find module './src/main.ts' from '/home/node/app'
app        |     at module.exports (/home/node/app/node_modules/resolve/lib/sync.js:74:15)
app        |     at module.exports (/home/node/app/node_modules/ts-node-dev/lib/resolveMain.js:15:14)
app        |     at module.exports (/home/node/app/node_modules/ts-node-dev/lib/index.js:29:14)
app        |     at Object.<anonymous> (/home/node/app/node_modules/ts-node-dev/bin/ts-node-dev:102:1)
app        |     at Module._compile (internal/modules/cjs/loader.js:1139:30)
app        |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
app        |     at Module.load (internal/modules/cjs/loader.js:988:32)
app        |     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
app        |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
app        |     at internal/main/run_main_module.js:17:47 {
app        |   code: 'MODULE_NOT_FOUND'
app        | }
app        | npm ERR! code ELIFECYCLE
app        | npm ERR! errno 1
app        | npm ERR! nestjs-graphql-boilerplate@1.0.0 start:dev: `ts-node-dev --respawn --transpileOnly ./src/main.ts`
app        | npm ERR! Exit status 1
app        | npm ERR!
app        | npm ERR! Failed at the nestjs-graphql-boilerplate@1.0.0 start:dev script.
app        | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app        |
app        | npm ERR! A complete log of this run can be found in:
app        | npm ERR!     /home/node/.npm/_logs/2020-08-08T13_09_27_282Z-debug.log
```

**To Reproduce**
1. Checkout https://github.com/fernandohenriques/nestjs-graphql-boilerplate
2. cd to project and `npm install`
3. create `.env` file based on `.env.sample`
4. `docker-compose up`
5. See error

**Expected behavior**
NestJS application should start (Tested working on Ubuntu 20.04 WSL2 and Macos)

**Basic Troubleshooting Checklist**

[/] I have searched Google for the error message.
[/] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[/] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[/] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[/] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[/] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

20.7.0.0

Insert here:

**Windows Build**

```
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. UX391UA.304, 6/28/2019
```

**Comment by crramirez** [comment]
Hello,

/home/node is inside the distribution or inside the docker container?

Regards,
Carlos

**Comment by mjmaix** [comment]
> Hello,
> 
> /home/node is inside the distribution or inside the docker container?
> 
> Regards,
> Carlos

It's from the docker logs.

**Comment by crramirez** [comment]
Hello,

I saw the instructions and looks like everything is inside the container. Even in their instructions with docker, you don't need to install node or do npm install.

Check if the docker is able to access your file system as volumes and if docker for windows is correctly configured with pengwin. There it is called WLinux.

I don't see that your problem is related to pengwin but how the project is configured.

Regards,
Carlos
