### ISSUE TITLE
MS SQL ODBC driver install fails

### ISSUE THREAD

**Issue by cwstanton** [WhitewaterFoundry/Pengwin#629]
**Describe the bug**
In order to use SQLAlchemy in Python to connect to SQL Server databases, I am attempting to install the ODBC driver from Microsoft following the instructions here:

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#debian17

(I understand that the options only go up to Debian 10, and Pengwin appears to be "Bullseye," which is pre-11.  I ran into that trying to install Elixir/Erlang, as well..)

It fails with unsatisfied dependency and "uninstallable" comments:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libodbc1 : PreDepends: multiarch-support but it is not installable
 odbcinst1debian2 : PreDepends: multiarch-support but it is not installable
E: Unable to correct problems, you have held broken packages.

```
**To Reproduce**
1. Add the Microsoft source to sources:
deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main

2. sudo apt-get upgrade

3. sudo ACCEPT_EULA=Y apt-get install msodbcsql17

**Expected behavior**
The ODBC driver would be installed.

**Screenshots**

**Additional context**

**Basic Troubleshooting Checklist**

[ x ] I have searched Google for the error message.
[ x ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ x ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ x ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: 
20.7.0.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO N2NET38W (1.23 ), 6/4/2020

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello,

Thanks for reporting. Try this:

`echo 'deb https://deb.debian.org/debian stable main' | sudo tee /etc/apt/sources.list.d/stable.list`

Regards,
Carlos

**Comment by cwstanton** [comment]
Running that, then repeating the update and the install worked.  Thank you!
