### ISSUE TITLE
uname processor reporting as unknown

### ISSUE THREAD

**Issue by plttn** [WhitewaterFoundry/Pengwin#631]
**Describe the bug**
`uname -p` reports as unknown, when Ubuntu reports properly as x86_64 (also occurs with `-i`)
**To Reproduce**
1. run `uname -p`

**Expected behavior**
Expected output of x86_64

**Additional context**
Not sure why it'd be broken in Pengwin but not Ubuntu 20.04

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[x] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: 20.8.3.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here: 19041

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Yes it is strange. Thanks you for reporting we will take a look.

**Comment by crramirez** [comment]
Hello,

The issue was reproduced. As a workaround use `uname -m`.

I've checked with a Debian installation and it reports **unknown** also. So we need to figure out where Ubuntu is taking those values. I'll tell you here when we find something.

Regards

**Comment by crramirez** [comment]
I found this: https://unix.stackexchange.com/questions/307955/uname-p-i-are-unknown

Looks like even in bare metal Debian returns unknown for -p and -i.

I confirmed that the answer there is true for Fedora. Fedora Remix correctly returns a value for -p and -i
