### ISSUE TITLE
WSL2 Remote Procedure Call Failed 

### ISSUE THREAD

**Issue by mattmazer0397** [WhitewaterFoundry/Pengwin#634]
**Describe the bug**
Windows 10 insider Build# 20201.rs_prerelease.200822-1922

When I try to run "wsl --set-version WLinux 2" I get a "remote procedure call failed. 

**To Reproduce**
1. Open powershell, with administrator privileges
2. Run "wsl --list --verbose" to verify pengwin installation. Currently running version 1.
3. Run "wsl --set-default-version 2" to make WSL2 the default iteration
4. Reboot and reopen powershell (admin privileges)
5. Run "wsl --list --verbose" to verify pengwin installation. Still running version
6. Run "wsl --set-version WLinux 2" to 'force' wsl2 to work.
7. Powershell displays "Conversion in progress, this may take a few minutes..." after a few seconds PS then reads "remote procedure call failed"

**Expected behavior**
Pengwin should run WSL2 as outlined here https://www.whitewaterfoundry.com/blog/2019/6/12/enable-wsl2-and-convert-existing-pengwin-installations

**Basic Troubleshooting Checklist**
Everything is up to date

[Y] I have searched Google for the error message.
[Y] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[Y] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[Y] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[Y] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[Y] I have disabled and re-enabled WSL in Windows Features.
[Y] I have run Windows 10 updates and restarted.

**Pengwin Version**
20.8.3.0

**Windows Build**

OS Name:                   Microsoft Windows 10 Home Insider Preview
OS Version:                10.0.20201 N/A Build 20201
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              AMI F.18, 07-Nov-19

**Comment by crramirez** [comment]
Hello,

Have you tried `wsl --shutdown`? Also, if you upgrade your Insider version to the latest to see if it was solved?

Regards

**Comment by mattmazer0397** [comment]
Thanks for the quick response!

I did have an update coming in yesterday (latest version of windows insider) which has now been installed, and there is no change. I tried the wsl --shutdown as you mentioned too, to no avail.

It didn't occur to me yesterday, but I do have a problem where my WSL update 4.19.128 cannot install, if that's what my problem could be.

Would it be worth it to uninstall pengwin, install a different flavor of linux, and see if the problem persists?

**Comment by crramirez** [comment]
Hello @mattmazer0397,

What wsl --set-version WLinux 2 does internally is a wsl --export then creates it in WSL2 and --import.

You can try first to see if the problem is with the export. wsl --export WLinux destinationpath

You can then import it specifying --version 2. This is basically the process done manually.

If you don't care about your distribution content, you can simply delete Pengwin using wsl --unregister WLinux, set the default version to WSL2: wsl --set-default-version 2 and then run pengwin.exe. It will create the distribution in WSL2.

Before that maybe you want to make a home backup. Go to pengwin-setup -> MAINTENANCE -> HOMEBACKUP

Tel me the route that you want to take and I can guide you.

**Comment by mattmazer0397** [comment]
"If you don't care about your distribution content, you can simply delete Pengwin using wsl --unregister WLinux, set the default version to WSL2: wsl --set-default-version 2 and then run pengwin.exe. It will create the distribution in WSL2."

**Comment by crramirez** [comment]
Before that, maybe you want to make a home backup. Go to pengwin-setup -> MAINTENANCE -> HOMEBACKUP

**Comment by mattmazer0397** [comment]
got the backup, failed to specify. My apologies

**Comment by mattmazer0397** [comment]
still no luck

**Comment by yazdipour** [comment]
i am facing the same problem

**Comment by mattmazer0397** [comment]
I hope you're still checking this. I believe it was windows insider that broke something. I reset my laptop to factory default, ran the updates, joined the insider program again (this time with the most stable version) and then worked on initiating WSL/2. It went flawlessly. Thank you for assistance earlier with my issues.

**Comment by crramirez** [comment]
Thank you for commenting on your findings. Some presenters in WSLConf last week also faced problems with WSL2 and their insider versions
