### ISSUE TITLE
Ability to use pengwin-setup while using "appendWindowsPath = False"

### ISSUE THREAD

**Issue by maple3142** [WhitewaterFoundry/Pengwin#636]
**Is your feature request related to a problem? Please describe.**
`pengwin-setup` doesn't seem to work if you set `appendWindowsPath = False` is wsl.conf, but it is necessary to remove unnecessary Windows PATH so that oh-my-zsh can perform at a resonable performance (https://github.com/microsoft/WSL/issues/4256#issuecomment-586798255).

**Describe the solution you'd like**
I can using "appendWindowsPath = False" without sacrificing `pengwin-setup`, or Pengwin isn't really different from Debian.

**Describe alternatives you've considered**

**Additional context**

Zsh performance when disabling Windows PATH:
![image](https://user-images.githubusercontent.com/9370547/93709475-f7c4cc00-fb70-11ea-8315-84697a20b3e9.png)
Zsh performance with Windows PATH enabled:
![image](https://user-images.githubusercontent.com/9370547/93709485-04e1bb00-fb71-11ea-8869-d9905bd07091.png)

**Comment by crramirez** [comment]
Hello,

We have considered some options like cache the windows path or empirically guest where reg.exe and cmd.exe are.

There are features of pengwin-setup that can be used without the windows path, but the vast majority and the most useful need the windows oath.

I can suggest as a workaround only to activate the windows path when you plan to use pengwin-setup and then disable again.

We will put some options on the table to deal with this issue.

Regards,
Carlos

**Comment by maple3142** [comment]
Okay, I have a workaround by delaying those Windows PATH in `.zshrc`.

https://github.com/maple3142/dotfiles/blob/fcca7bb024c7d3ed8205a90cfa1d81ade9b46300/.zshrc#L54-L57
