### ISSUE TITLE
crashing updating libc-bin

### ISSUE THREAD

**Issue by asemblR** [WhitewaterFoundry/Pengwin#637]
**Describe the bug**
apt seg-faults when updating libc-bin 

**To Reproduce**
Happens when I try to install or remove anything now!

**Expected behavior**
to work properly 

**Screenshots**
  
https://drive.google.com/file/d/1d0FkNWtRGkKxNviYCnZGBwr6qihYNKp-/view?usp=sharing

**Additional context**

**Basic Troubleshooting Checklist**

[ ] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: 20.8.3.0

**Windows Build** 

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:    
OS Version:                10.0.19041 N/A Build 19041.508

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello @asemblR ,

I asked you in the other issue https://github.com/WhitewaterFoundry/Pengwin/issues/619 if you run apt-get update before. I see that the problem became worse, and I am not able to reproduce it. Could you give me more information?

- Is it a new pengwin installation?
- Is it WSL1 or 2, which is the output of wsl.exe --list --verbose

Any other strange thing that you noticed before?

Regards

**Comment by asemblR** [comment]
Sorry I didn't get notified that You replied to the other thread, as for age of the install about 3 months old and I am runn wsl 1 because other software Im running will not run will virtualization on.
