### ISSUE TITLE
python http server unreachable

### ISSUE THREAD

**Issue by aborruso** [WhitewaterFoundry/Pengwin#647]
Hi,
when I run `python3 -m http.server` I have `Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/)`.

But If I open the `http://0.0.0.0:8000/` or `http://localhost:8000/` in the browser I have "connection failed" (below it's in Italian).

![image](https://user-images.githubusercontent.com/30607/96425014-d270bf80-11fb-11eb-902e-0e3e7d9ed677.png)

No problem to pinging it via shell. Could it be some win firewall setting? How to set it?

![image](https://user-images.githubusercontent.com/30607/96424972-c71d9400-11fb-11eb-94ae-808969555b55.png)

I'm using `PENGWIN_VERSION="20.10.3"`

```
WSL Version: 2
Locale: it_IT
Release Install Date: Wed Jun  3 16:19:27 CEST 2020
Branch: vb_release
Build: 19041
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 1
Windows Theme: light
Windows Uptime: 4d 3h 10m
WSL Uptime: 3d 1h 56m
WSL Release: Pengwin
WSL Kernel: Linux 4.19.104-microsoft-standard
Packages Count: 1021
```

Thank you

**Comment by crramirez** [comment]
Hello @aborruso ,

Try to connect to the WSL2 IP instead of localhost. Run `ip address` to get your IP. Then use this IP in your browser.

Regards, 
Carlos

**Comment by aborruso** [comment]
Hello @crramirez it works.

Do you have some tips to to automate it? Or do I must run everytime `ip address` to check my ip?

As usual thank you very much

**Comment by crramirez** [comment]
I have seen some scripts out there. I can find one and make a how-to guide or even include it in pengwin-setup

**Comment by aborruso** [comment]
It would be great, thank you

**Comment by WSLUser** [comment]
In `.wslconfig` there's `enable localhost forwarding.` I think this scenario is what's enabled by enabling it.

**Comment by aborruso** [comment]
> In `.wslconfig` there's `enable localhost forwarding.` I think this scenario is what's enabled by enabling it.

Do I must create .wslconfig  file in ~ and add the below row?

```
enable localhost forwarding
```

**Comment by WSLUser** [comment]
You create it in your Windows home user. See the WSL release notes. There's a template you can copy/paste. Change this option to true

**Comment by crramirez** [comment]
https://www.bleepingcomputer.com/news/microsoft/windows-10-wsl2-now-allows-you-to-configure-global-options/

**Comment by kastoestoramadus** [comment]
`localhostForwarding= # Boolean specifying if ports bound to wildcard or localhost in the WSL2 VM should be connectable from the host via localhost:port (default true).`
Default is true :/
I've lost this forwarding after upgrading to WSL2. I wanted docker integration :/
Any other hints?

**Comment by WSLUser** [comment]
There's a WSL2 backend for Docker Desktop for Windows. If you enable that,  do you still have an issue?

**Comment by kastoestoramadus** [comment]
> 
> 
> There's a WSL2 backend for Docker Desktop for Windows. If you enable that, do you still have an issue?

As you wrote it is for WSL 2. Upgrading to 2 creates connectivity with host problem.

**Comment by WSLUser** [comment]
You have to enable it yourself. By default Docker uses Hyper-V/Moby VM.

**Comment by DevDorrejo** [comment]
hello, some advance on this?

**Comment by crramirez** [comment]
> hello, some advance on this?

Hello @DevDorrejo,

This discussion is quite long, so tell me what issue you are facing?

Regards,
Carlos
