### ISSUE TITLE
Installing Golang through pengwin-setup doesn't export PATH vars

### ISSUE THREAD

**Issue by FraCart** [WhitewaterFoundry/Pengwin#650]
**Describe the bug**
When installing the Golang programming language with pengwin-setup, it just downloads and extract the .tar in /usr/local/go, without actually exporting the go environment variables to the $PATH.
When finishing the "installation" it says it's doing that, but `go which` doesn't resolve to anything and when inspecting `echo $PATH` there are no Go vars exported.

**Additional context**

I've ran pengwin-setup while using Fish, I don't know if it has to do with that. I've exported the path by myself and all is working fine.

It would be also nice if when creating the go/ workspace directory in the home, to add the _pkg_, _src_ and _bin_ dirs.

**Pengwin Version**

20.10.5

Insert here:

**WSL general info**

```
WSL Version: 2
Locale: it_IT
Release Install Date: Thu Oct  8 13:31:14 CEST 2020
Branch: vb_release
Build: 19041
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 1
Windows Theme: dark
Windows Uptime: 17d 22h 41m
WSL Uptime: 0d 0h 22m
WSL Release: Pengwin
WSL Kernel: Linux 4.19.128-microsoft-standard
Packages Count: 493
```

**Comment by crramirez** [comment]
Hello,

It should work with fish. Thanks for reporting we will take al look.

Regards,
Carlos

**Comment by crramirez** [comment]
Fixed check this PR: https://github.com/WhitewaterFoundry/pengwin-setup/pull/292

**Comment by FraCart** [comment]
aaaand it works, nice!
