### ISSUE TITLE
Can't use X410 with Pengwin WSL2

### ISSUE THREAD

**Issue by CedricMi** [WhitewaterFoundry/Pengwin#651]
Hello,
I've seen the other closed issues with X410 on WSL2, but it still doesn't work:
xfce4-session
_Unable to init server: Could not connect: Connection refused
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage._

X410.exe /Public
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
Changed ssh_config with ForwardX11 yes
sudo apt install xbase-clients xauth
Made sure the app had public access in the Windows Firewall

Any ideas?
Windows: Windows 10 Pro 64 version 2004 (19041.610)
Pengwin: 4.19.128-microsoft-standard

**Comment by CedricMi** [comment]
It was indeed a strange Firewall issue, since I authorized the 410.exe for both public & private networks.
I added and removed the authorizations a few times before a popup windows asked if the app was athorized for public and private networks.

**Comment by crramirez** [comment]
Hello @CedricMi,

Please close Pengwin and open it again. Then cat /etc/environment. It should output the DISPLAY variable with the IP of your PC. Pengwin configures it automatically so you don't need to alter this variable. The error indicates that X410 is not running. 

Try something simpler first execute xfce4-terminal:

```
pengwin-setup autoinstall GUI GUILIB
pengwin-setup autoinstall TERMINAL XFTERM
```

Then execute xfce4-terminal. it should show the terminal if X410 is running.

These 3 steps are not necessary in Pengwin:

> export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
> Changed ssh_config with ForwardX11 yes
> sudo apt install xbase-clients xauth
> 

Regards,
Carlos

**Comment by crramirez** [comment]
Ah, well ignore my answer 😊
