### ISSUE TITLE
libc Update Error

### ISSUE THREAD

**Issue by PeteSL** [WhitewaterFoundry/Pengwin#652]
apt upgrade produced following error this morning (WSL1)

Processing triggers for libc-bin (2.31-1.wsl) ...
Aborted (core dumped)
ldconfig: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
ldconfig: Path `/lib/x86_64-linux-gnu' given more than once
ldconfig: Path `/usr/lib/x86_64-linux-gnu' given more than once
/usr/lib/x86_64-linux-gnu/libfakeroot:
        libfakeroot-0.so -> libfakeroot-tcp.so
/usr/local/lib:
/lib/x86_64-linux-gnu:
Aborted (core dumped)
dpkg: error processing package libc-bin (--configure):
 installed libc-bin package post-installation script subprocess returned error exit status 134
Errors were encountered while processing:
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by crramirez** [comment]
Hello @PeteSL ,

Try this command:

```
sudo apt update
sudo apt -y reinstall libc6=2.31-1.wsl libc-bin=2.31-1.wsl libc6-dbg=2.31-1.wsl libc6-dev=2.31-1.wsl locales=2.31-1.wsl libc-dev-bin=2.31-1.wsl calendar ncal
```

Regards,
Carlos

**Comment by PeteSL** [comment]
sudo apt -y reinstall libc6=2.31-1.wsl libc-bin=2.31-1.wsl libc6-dbg=2.31-1.wsl libc6-dev=2.31-1.wsl locales=2.31-1.wsl libc-dev-bin=2.31-1.wsl calendar ncal
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  libc6-dbg
0 upgraded, 1 newly installed, 7 reinstalled, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 14.6 MB/17.4 MB of archives.
After this operation, 12.0 MB of additional disk space will be used.
Get:1 https://deb.debian.org/debian bullseye/main amd64 calendar amd64 12.1.7 [132 kB]
Get:2 https://deb.debian.org/debian bullseye/main amd64 ncal amd64 12.1.7 [29.9 kB]
Get:3 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian bullseye/main amd64 locales all 2.31-1.wsl [4,077 kB]
Get:4 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian bullseye/main amd64 libc-dev-bin amd64 2.31-1.wsl [283 kB]
Get:5 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian bullseye/main amd64 libc6-dbg amd64 2.31-1.wsl [7,665 kB]
Get:6 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian bullseye/main amd64 libc6-dev amd64 2.31-1.wsl [2,398 kB]
Fetched 14.6 MB in 6s (2,450 kB/s)
E: Internal Error, No file name for libc-bin:amd64

**Comment by crramirez** [comment]
If you have already the latest Windows updates installed you can try to use the latest libc6 from Debian, with this command:

switch2dev

**Comment by PeteSL** [comment]
Note I am not using WSL2 as this installation is just for limited testing that does not require a VM.
After switch2dev (same error regarding the gnu directory as originally seen):
Preparing to unpack .../libc-bin_2.31-4_amd64.deb ...
Unpacking libc-bin (2.31-4) over (2.31-1.wsl) ...
Setting up libc-bin (2.31-4) ...
Aborted (core dumped)
ldconfig: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
ldconfig: Path `/lib/x86_64-linux-gnu' given more than once
ldconfig: Path `/usr/lib/x86_64-linux-gnu' given more than once
/usr/lib/x86_64-linux-gnu/libfakeroot:
        libfakeroot-0.so -> libfakeroot-tcp.so
/usr/local/lib:
/lib/x86_64-linux-gnu:
Aborted (core dumped)
dpkg: error processing package libc-bin (--configure):
 installed libc-bin package post-installation script subprocess returned error exit status 134
Errors were encountered while processing:
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by PeteSL** [comment]
I placed a symbolic link to the gnu library in /usr/local/lib and got the following:
Preparing to unpack .../libc-bin_2.31-4_amd64.deb ...
Unpacking libc-bin (2.31-4) over (2.31-1.wsl) ...
Setting up libc-bin (2.31-4) ...
Aborted (core dumped)
ldconfig: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
ldconfig: Path `/lib/x86_64-linux-gnu' given more than once
ldconfig: Path `/usr/lib/x86_64-linux-gnu' given more than once
/usr/lib/x86_64-linux-gnu/libfakeroot:
        libfakeroot-0.so -> libfakeroot-tcp.so
/usr/local/lib:
/lib/x86_64-linux-gnu:
Aborted (core dumped)
dpkg: error processing package libc-bin (--configure):
 installed libc-bin package post-installation script subprocess returned error exit status 134
Errors were encountered while processing:
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)

Looks like the latest release is looking in /usr/local/lib where there is nothing but the pengwin.ico and then there are multiple references elsewhere when there shouldn't be.

**Comment by crramirez** [comment]
Yes I saw that you are using WSL1 and it is fine. Microsoft fixed the libc6 problem for WSL1  some updates ago.

Think if you can backup for example your home using pengwin-setup and install it from scratch, because I am out of ideas.

**Comment by PeteSL** [comment]
Ok, I will work on that later today and report back.  Thanks!

**Comment by PeteSL** [comment]
I uninstalled/reinstalled and it is working now.
