### ISSUE TITLE
Add app to STARTMENU in pengwin-setup

### ISSUE THREAD

**Issue by PeteSL** [WhitewaterFoundry/Pengwin#654]
I have added a GUI app to my Pengwin installation using make and make install.  All good.

The app works with the runHidden.vbs script under WSL1.

How do I tell STARTMENU that the app has been added and what its icon is?

**Comment by crramirez** [comment]
If the application installed a Desktop file, just run pengwin-setup startmenu

**Comment by PeteSL** [comment]
Not sure what a Desktop file is but apparently not since pengwin-setup startmenu is not seeing it.

**Comment by crramirez** [comment]
OK you can use wslusc directly it will put the shortcut on the desktop :

```
wslusc -I #Interactive 
```

Then it will ask you the icon, command, etc.

Regards,
Carlos

**Comment by PeteSL** [comment]
Almost, and this might be changed to a bug report.  The program is started from the command line as xastir.  The desktop shortcut was correctly created except:

C:\Windows\System32\wscript.exe {removed}\runHidden.vbs "pengwin.exe" run "/usr/share/wslu/wslusc-helper.sh /usr/local/bin/xastir"

"pengwin.exe" was missing causing an "app not found" error.  Added it to the shortcut command and works fine.

**Comment by crramirez** [comment]
Which is the result for this:

`cat $HOME/.config/wslu/baseexec`

**Comment by PeteSL** [comment]
There is no baseexec file.  There are only 2 files in that directory, oemcp and triggered_time.  I did see that pass by when it was creating links that the file did not exist.  That said, the Start Menu shortcuts created from pengwin-setup STARTMENU do have "pengwin.exe" before the run verb.

**Comment by crramirez** [comment]
It should have created it. If you wish please delete `$HOME/.config/wslu` and try again, it should create this file.

**Comment by PeteSL** [comment]
If I delete that folder, do I lose anything else?  Are you saying that file should be created by the wslusc program?  Sorry for my denseness but just ensuring I understand.

**Comment by crramirez** [comment]
This folder is regenerated by wslu in general. You won't lose anything. But to be safe rename the folder, just in case.

**Comment by PeteSL** [comment]
That worked and the 2 files that were in there were regenerated with baseexec added.  I note that the full path to pengwin.exe was used vs. just pengwin.exe as was used in the other shortcuts.  Just a note.  I will close this but these idiosyncrasies are worth noting.

**Comment by crramirez** [comment]
Glad it worked. This is because pengwin-setup and wslusc don't use the same methods to generate the shortcuts. wslusc is more generic.

I just found this: https://tools51.nasqueron.org/generators/GNOME/desktop-file 

If you put the generated file in /usr/share/applications with a .desktop extension, pengwin-setup will be able to put it in the start menu
