### ISSUE TITLE
mount: /proc: proc already mounted on /proc. ERROR at Pengwin startup

### ISSUE THREAD

**Issue by wjm1191** [WhitewaterFoundry/Pengwin#656]
**Note**

These WSL error messages occur from time to time and can tricky to troubleshoot short of reinstalling WSL.

They are usually not an issue with Pengwin itself but a glitch with the underlying Windows Subsystem for Linux in Windows 10.

You can help us help you and Microsoft improve WSL and address these if you can provide us some debugging information.

[x] I have read the above statement.

**Basic Troubleshooting**

Please check:

[x] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched Google for the error message.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[x] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted to date?

**Error Code**

Insert here: mount: /proc: proc already mounted on /proc.

Please check:

[x] This error code is not one listed below.

Known Error Codes
0x80040306 Fix: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80040306-on-installation
0x80040154 Fix: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80040154-after-windows-update

**Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: 20.11.0.0

**Screenshot**

Insert here: 
![image](https://user-images.githubusercontent.com/70824000/100102251-3faaec80-2e5b-11eb-929b-840d77301d76.png)

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**WSL Debug Data**

Please collect and attach .etl files by following this guide: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#starting-bash-gives-an-error-code

A similar issue has been reported on https://github.com/microsoft/WSL/issues/5800.

**Comment by crramirez** [comment]
Hello,

One question did you install Cassandra from pengwin-setup? If the answer is yes. Do you use it?

Regards

**Comment by wjm1191** [comment]
> Hello,
> 
> One question did you install Cassandra from pengwin-setup? If the answer is yes. Do you use it?
> 
> Regards

Hi,

I did not install Cassandra from pengwin-setup. It may relate to the font. It takes about 40 seconds to show the normal bash command line. But the Ubuntu 20.04 lts starts up immediately. After I uninstalled all the fcitx languages, the start takes only about 5 seconds now.

Best.

**Comment by saigkill** [comment]
Related to [pengwin-setup](https://github.com/WhitewaterFoundry/pengwin-setup/issues/308)
