### ISSUE TITLE
Enable "regular" use of PPAs by removing some pinning rules

### ISSUE THREAD

**Issue by davclark** [WhitewaterFoundry/Pengwin#658]
**Is your feature request related to a problem? Please describe.**
I just spent way too much time trying to get nodejs LTS installed (which is now 14.x, NOT what's installed by your installer - hence my approach to install manually). Turns out you have these pinning rules set up in `/etc/apt/preferences`:

```
Package: *
Pin: release a=testing
Pin-Priority: 990

Package: *
Pin: release a=bullseye
Pin-Priority: 991
```

These rules cause apt and friends to disregard sources at the default priority, which is 500.

**Describe the solution you'd like**
Get rid of those lines.

**Describe alternatives you've considered**
Leave it as you like - users continue to struggle with PPAs.

Thanks for all the great work otherwise! I really like the way you support Node now, actually - just want to get latest LTS via apt...

**Comment by ThatWeirdAndrew** [comment]
I just created a pull request to pengwin-setup that updates both the current and LTS versions of Node.js. Hopefully it is merged soon. I don't know the reasons for the apt pinning rules so I can't help with that.

**Comment by crramirez** [comment]
Thank you @ThatWeirdAndrew for the contribution

The /etc/apt/preferences are how we control the versions of the packages that we find incompatible with WSL. We will revisit this configuration to see if is too strict.


Thanks for reporting.

**Comment by davclark** [comment]
I think I understand what you're going for. Definitely, you should keep the pinning rules for your own repositories higher than 500. The issue I have arises from the fact that you are also elevating the priority of the testing source.

I can of course set the priority of manually added PPAs... at a minimum, you might leave some "space" in between testing and bullseye to be able to pin my PPAs in there?

But I realize there is another perhaps more appropriate option, which would be to have specialized tooling for PPAs in pengwin. Perhaps in `pengwin-setup`? This could insert PPAs at an appropriate priority...

**Comment by crramirez** [comment]
Pengwin 21.2.1 includes the change that you requested

**Comment by davclark** [comment]
I noticed and came here to say thank you!

**Comment by crramirez** [comment]
You are very welcome
