### ISSUE TITLE
ss -a answers invalid argument

### ISSUE THREAD

**Issue by plttn** [WhitewaterFoundry/Pengwin#660]
**Describe the bug**
Running `ss -a` (as used by https://github.com/BlackReloaded/wsl2-ssh-pageant) results in an output of `RTNETLINK answers: Invalid argument` as well as the appropriate output
**To Reproduce**
1. enter `ss -a`
2. output results in regular output as well as the error

**Expected behavior**
For `RTNETLINK` error to not appear.

**Additional context**
This issue did not previously appear on Pengwin. https://github.com/BlackReloaded/wsl2-ssh-pageant/issues/17

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[x] I have run Windows 10 updates and restarted.
[x] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

What other troubleshooting have you attempted?

Per https://github.com/BlackReloaded/wsl2-ssh-pageant/issues/17, v5.5.0 of iproute was fine, 5.10.0 causes the issue. 

Insert here:

**Pengwin Version**

Run `grep "PENGWIN_VERSION" /etc/os-release` in Pengwin.

Insert here: `20.12.1`

**WSL general info**

Run `wslsys` in Pengwin.

Insert here:
```
WSL Version: 2
Locale: en_US
Release Install Date: Tue Aug  4 17:12:57 PDT 2020
Branch: vb_release
Build: 19042
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 1
Windows Theme: light
Windows Uptime: 3d 23h 48m
WSL Uptime: 1d 9h 35m
WSL Release: Pengwin
WSL Kernel: Linux 4.19.104-microsoft-standard
Packages Count: 866
```

**Comment by crramirez** [comment]
Hello,

Thank you for the report. Looks like we need to limit this package version until WSL gets fixed.

We will investigate it

Regards,
Carlos

**Comment by plttn** [comment]
I've gone ahead and downgraded it to 4.9 on my end for now, and that has resolved the problem for now.

**Comment by plttn** [comment]
Was this package ever held back, or should I continue manually downgrading it for now?

**Comment by crramirez** [comment]
Hello,

We haven't worked on it yet. Sorry for the inconvenience and thank you for the reminder. We will work on it today or tomorrow.

Regards,
Carlos

**Comment by ferrazpedro** [comment]
Just to add some more information. I was having the exact same problem with FedoraRemix 33, and downgrading iproute to 5.8.0 was my solution.

**Comment by crramirez** [comment]
Very useful information, becuse we need to do the same to fedora remix at least until Microsoft upgrades the kernel

**Comment by crramirez** [comment]
Hello, 

The fix will ship in the next pengwin release. To fix it now just run:

`sudo apt-get install -q -y --allow-downgrades iproute2=5.8.0-1`

The package was uploaded to whitewater foundry repos. So you don't need to do anything further.

Regards

**Comment by crramirez** [comment]
For Fedora the change is already in upgrade.sh and a new image is being generated

**Comment by melink14** [comment]
I noticed this error only recently and updated after seeing it should be fixed but still see the error when running `ss -a`.

I tried to run teh command above but the package is not found:
```terminal
🕙 08:06:43 ❯ sudo apt-get install -q -y --allow-downgrades iproute2=5.8.0-1
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '5.8.0-1' for 'iproute2' was not found
```

**Comment by crramirez** [comment]
Hello @melink14,

The error was fixed in the latest kernel from Microsoft, this is why pengwin-setup no longer locks the iproute2 package to 5.8. 

Be sure you have the latest kernel running `wsl.exe --update`

Regards,
Carlos
