### ISSUE TITLE
Documentation for starting services at boot time

### ISSUE THREAD

**Issue by edfalis** [WhitewaterFoundry/Pengwin#661]
Is there a single comprehensive explanation? I've exhausted my search options.

Thanks!

**Comment by crramirez** [comment]
Hello,

Tomorrow I will post here a link with information. Would you like that the services start when Windows boot or when Pengwin boot?

Regards,
Carlos

**Comment by crramirez** [comment]
Hello,

Following the instructions for installing a Linux service that starts at Windows logon. In this example we will set up an apache webserver:

1. Install apache in Pengwin: `sudo apt install apache2`
2. Create the script to run the service: `/usr/bin/start-apache`
```bash
#! /bin/bash

apachectl -D FOREGROUND
```
3. Change the permissions: `sudo chmod 700 /usr/bin/start-apache`
4. Add it to sudoers: `echo "%sudo   ALL=NOPASSWD: /usr/bin/start-apache" | sudo EDITOR='tee -a' visudo --quiet --file=/etc/sudoers.d/start-apache`
5. Create a bat file in your home folder: `apache.bat`
```batch
C:\Windows\System32\wsl.exe -d WLinux sudo /usr/bin/start-apache
```
6. Download and expand NSSM: https://nssm.cc/download
7. Run it to install the service `nssm.exe install Apache`
8. Fill the basic parameters
![image](https://user-images.githubusercontent.com/8397379/103645711-c4a81c00-4f58-11eb-82d3-3b9c86afb137.png)
![image](https://user-images.githubusercontent.com/8397379/103645998-3aac8300-4f59-11eb-9d2e-710f941a53f6.png)
9. It is important to specify your user account as the logon account
![image](https://user-images.githubusercontent.com/8397379/103646238-a42c9180-4f59-11eb-966c-5ad50dce3d1f.png)
10. Click **Install Service**

This should start apache in pengwin.

Hope it helps

**Comment by edfalis** [comment]
Carlos,

Thanks. Will give it a try later on, likely later today.

Unfortunately, when I first set up Windows I took a default and set up a user account that is different than the one I use on Pengwin. So in the instructions do you mean the Windows or the Pengwin user account?

Thanks!

- Ed

**Comment by crramirez** [comment]
They are the credentials that you use to log in on Windows

**Comment by edfalis** [comment]
Will reopen if necessary once I have a chance to try it out. Thanks again!
