### ISSUE TITLE
Failure to install the PowerShell via pengwin-setup 

### ISSUE THREAD

**Issue by masa-koz** [WhitewaterFoundry/Pengwin#662]
**Describe the bug**
I cannot install the PowerShell via pengwin-setup.

**To Reproduce**
1. launch pengwin-setup
2. Toggle TOOLS/POWERSHELL
3. See error

**Expected behavior**
I would succeed in installing the PowerShell. 

**Error messages**
After the finish of pengwin-setup, I saw the following error message.

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 powershell : Depends: libssl1.0.0 but it is not installable
              Depends: libicu60 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Pengwin Version**
PENGWIN_VERSION="21.1.1"

**WSL general info**
WSL Version: 1
Locale: ja_JP
Release Install Date: Tue May 26 20:01:22 JST 2020
Branch: vb_release
Build: 19041
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 1
Windows Theme: light
Windows Uptime: 9d 16h 57m
WSL Uptime: 8d 12h 30m
WSL Release: Pengwin
WSL Kernel: Linux 4.4.0-19041-Microsoft
Packages Count: 887

**Comment by crramirez** [comment]
Hello,

Thank you for reporting. We will check.

Regards,
Carlos

**Comment by saigkill** [comment]
Hello @masa-koz,
thanks for reporting. Currently i'm trying to reproduce, what happens.
Could you please send us the output of `cat /etc/apt/sources.list.d/microsoft.list` ?

**Comment by crramirez** [comment]
Also, if you can send us the directory list: ls -l /etc/apt/sources.list.d

We are looking for some old configuration because these dependencies are old, and the latest PowerShell installer looks for newer ones.

Regards

**Comment by masa-koz** [comment]
Hello @saigkill and @crramirez 

The following is the output on my encironment.

➜  ~ cat /etc/apt/sources.list.d/microsoft.list
deb https://packages.microsoft.com/repos/microsoft-debian-buster-prod buster main
➜  ~ ls -l /etc/apt/sources.list.d
total 4
-rw-r--r-- 1 root root  64 Aug  4 22:42 azurecli.list
-rw-r--r-- 1 root root  82 Jan 15 11:50 microsoft.list
-rw-r--r-- 1 root root  78 Jan  3  2019 microsoft-prod.list
-rw-r--r-- 1 root root 489 Apr 10  2020 whitewaterfoundry.list

**Comment by crramirez** [comment]
Hello @masa-koz ,

Excellent with this information we can see the problem. Please delete the file **microsoft-prod.list**. Then `sudo apt update` and install again PowerShell from pengwin-setup. And please tell us the results.

Regards,
Carlos

**Comment by masa-koz** [comment]
Hello @crramirez 

I've tried and succeed in installing pwsh! Thanks!

**Comment by crramirez** [comment]
Excellent
