### ISSUE TITLE
Pengwin install fails on ARM64 WoS build 21292

### ISSUE THREAD

**Issue by domcote** [WhitewaterFoundry/Pengwin#663]
Worked fine a few preview builds ago, fails now. Setup: Surface Pro X, running build 21292. Hyper-V and WSL installed.

Error message: _"WslRegisterDistribution failed with error: 0x800701bc
Error: 0x800701bc WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel"_

When I try to install https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_arm64.msi as suggested at aka.ms/wsl2kernel, I get this error: _"A later version of WSL is already installed. Setup will now exit"_.

I'm not a dev, but it looks like there is some hard version checking going on, instead of minimum version checking?

Happy to help troubleshoot!

**Comment by domcote** [comment]
Just tried _wsl --install -d ubuntu_ for good measure, same error. Looks like a bug in 21292. Heading over to Feedback Hub now...

**Comment by domcote** [comment]
Just tried _wsl --install -d ubuntu_ for good measure: same error and failure as above. Looks like a bug in build 21292. Heading over to Feedback Hub now...

**Comment by crramirez** [comment]
Hello,

I faced this error before on insider versions. First try to restart the PC. If it doesn't work go to Apps in Settings and uninstall something like WSL Upgrade. Restart and try again.

Regards,
Carlos

**Comment by domcote** [comment]
Great tip - worked! Thanks. 👍
