### ISSUE TITLE
[Feature request] Use Prezto to manage Zsh

### ISSUE THREAD

**Issue by Smithienious** [WhitewaterFoundry/Pengwin#667]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
The dialog to choose a framework should be shown before installing Zsh.
Eg:
 [x] Oh My Zsh
 [ ] Prezto
 [ ] No framework

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by crramirez** [comment]
Sounds good we will put it in the roadmap

**Comment by ThatWeirdAndrew** [comment]
I can work on this if you'd like.

**Comment by ThatWeirdAndrew** [comment]
Prezto support is done, just waiting on the pr to get merged.

**Comment by Peredery** [comment]
is it still in progress?

**Comment by Smithienious** [comment]
Yes, it's still pending https://github.com/WhitewaterFoundry/pengwin-setup/pull/316

**Comment by crramirez** [comment]
We need to make some changes in the menu. This week we can work on this, and have it ready.
