### ISSUE TITLE
How to change input language in GUI apps?

### ISSUE THREAD

**Issue by Peredery** [WhitewaterFoundry/Pengwin#671]
I install RU_RU_UTF8 from pengwin-setup, but I don't know how to change input language in GUI apps, windows hotkeys doesn't work here :(

**Comment by crramirez** [comment]
Hello,

In pengwin-setup->GUI select NLI ->IBus

![image](https://user-images.githubusercontent.com/8397379/109673017-e519de80-7b75-11eb-819c-66a136fd0fc1.png)
![image](https://user-images.githubusercontent.com/8397379/109673074-f19e3700-7b75-11eb-8322-6beae31d809a.png)

Regards,
Carlos

**Comment by Peredery** [comment]
done it, but it wont help :( Doesn't work for Russian language

**Comment by crramirez** [comment]
OK something to implement

**Comment by Peredery** [comment]
solution: 

`
setxkbmap us,ru -option grp:ctrl_shift_toggle
`
