### ISSUE TITLE
Environment Problem - The Windows PATH is not available

### ISSUE THREAD

**Issue by laurin1** [WhitewaterFoundry/Pengwin#675]
I do "sudo pengwin-setup update" weekly on all of my machines that have it (3, all Windows 10 Pro, 20H2). Today, 1 of the 3 did this:

![image](https://user-images.githubusercontent.com/75857/111485580-ba4a9100-8704-11eb-8c1e-606e7da2b57d.png)

I've made no changes to this machine's WSL2 (or anything really) since last week when this command ran successfully. I searched Google for this error and found nothing.

![image](https://user-images.githubusercontent.com/75857/111486287-5b394c00-8705-11eb-8a19-54e69f53e569.png)

**Comment by crramirez** [comment]
Hello @laurin1 ,

Do not use sudo, just run:

`pengwin-setup update`

Regards

**Comment by laurin1** [comment]
Oh, yea, that is so odd, I don't know why I suddenly started doing that on this one machine. Thanks and sorry for the trouble.

**Comment by crramirez** [comment]
You are very welcome, and this is the purpose of the forum, to help users.

**Comment by gneissguise** [comment]
@crramirez Thanks, I ventured over searching for this answer, I did the same exact thing as @laurin1 
d'oh!
