### ISSUE TITLE
buy problem

### ISSUE THREAD

**Issue by foxhacker0000** [WhitewaterFoundry/Pengwin#681]
hi i was buy raft wsl (L) with this email

**Comment by crramirez** [comment]
Hello,

Your question is not complete so I assume that you need to download the proper Raft WSL (L)

ms-windows-store://pdp/?productid=9ND3HNW6PNDK
https://www.microsoft.com/store/apps/9ND3HNW6PNDK

Regards

**Comment by foxhacker0000** [comment]
i was buy raft wsl (L)
but the program said me i should buy it again !

i was buy it with gift card 14$

>

**Comment by crramirez** [comment]
Hello,

Download it from the links above and delete the one that you have installed.

Regards

**Comment by foxhacker0000** [comment]
i tried it but i have this problem program said me to buy it

i was buy it

**Comment by crramirez** [comment]
Ok, please forward me the confirmation email sent by Microsoft to contact@whitewaterfoundry.com.
