### ISSUE TITLE
Shell hangs on open everytime, after a bit of time displays "mysql: unrecognized service"

### ISSUE THREAD

**Issue by SLGShark6** [WhitewaterFoundry/Pengwin#682]
**Describe the bug**
Same as title, shell hangs on open everytime, after a bit of time displays "mysql: unrecognized service". Have done about 3 fresh installs, LAMP stack installed with ~~Bundled~~ Builtin MariaDB version.

**To Reproduce**
1. Install LAMP stack
2. Restart shell

**Expected behavior**
Not for the shell to hang, and then throw out an unrecognized service error

**Screenshots**
![image](https://user-images.githubusercontent.com/35613914/113197471-55c22280-922a-11eb-95cb-2d19caac5fa0.png)

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[x] I have run Windows 10 updates and restarted.
[x] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

**Pengwin Version**

PENGWIN_VERSION="21.3.1"

**WSL general info**

WSL Version: 2
Locale: en_CA
Release Install Date: Mon Jan  4 17:07:42 EST 2021
Branch: vb_release
Build: 19042
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 1
Windows Theme: light
Windows Uptime: 4d 17h 58m
WSL Uptime: 0d 0h 47m
WSL Release: Pengwin
WSL Kernel: Linux 5.4.72-microsoft-standard-WSL2
Packages Count: 1259

**Comment by crramirez** [comment]
Hello @SLGShark6 ,

Thanks for reporting. We will try to reproduce it following your steps.

One question if you don't change the default shell from bash you still face the error?

Regards,
Carlos

**Comment by SLGShark6** [comment]
Thanks for the reply @crramirez ,

Can confirm it was after installing fish and setting it as default shell that opening the terminal hangs, did another fresh install to confirm.

**Comment by crramirez** [comment]
OK thank you for testing. Now we have a clear route to work with.

**Comment by SLGShark6** [comment]
Ran fish in debug mode, see the hang up ```<2> fish: sourcing /usr/share/fish/config.fish``` below:

![image](https://user-images.githubusercontent.com/35613914/113397643-fd427080-9362-11eb-909a-c8c8d7a08747.png)

**Comment by crramirez** [comment]
Hello @SLGShark6 ,

We fixed the hang with fish, but we are still testing its interaction with the LAMP installer

**Comment by crramirez** [comment]
Hello,

The release 21.7.0 includes a fix for that. Update with `pengwin-setup update`

Please test it.

Regards,
Carlos
