### ISSUE TITLE
Can't install with apt "qemu-kvm"; Unmet dependencies

### ISSUE THREAD

**Issue by jevvz** [WhitewaterFoundry/Pengwin#699]
Can't install qemu-kvm with apt.

Example: apt install qemu-kvm

It throws the following error:

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qemu-system-x86 : Breaks: qemu-kvm
E: Unable to correct problems, you have held broken packages.

Pengwin Version:

PENGWIN_VERSION="21.5.4"

**Comment by crramirez** [comment]
Hello @jevvz,

The package now is included in qemu-system-x86. Just install:

`sudo apt install qemu-system-x86`

Regards,
Carlos
