### ISSUE TITLE
nvm installs "n"

### ISSUE THREAD

**Issue by wsargent** [WhitewaterFoundry/Pengwin#700]
**Describe the bug**

If I select `nvm` as the nodejs install, then `n` is selected instead, and does not install cleanly.

**To Reproduce**
1. Go to `PROGRAMMING`
2. Click on `NODEJS`
3. Hit "YES"
3. "Choose Node.js install method" and select "NVM" from the list (note `n` is *NOT* selected)
4. See error showing that `n` is installed

**Expected behavior**

Expect `nvm` to be installed.

```
wsargent@GAMNER:~$ nvm
bash: nvm: command not found
```

**Additional context**

```
wsargent@GAMNER:~$ pengwin-setup
Starting pengwin-setup.
Updating package database
[sudo] password for wsargent:
Running upgrade check...
Holding pengwin-base & pengwin-setup to ensure no changes while operating
Selected: PROGRAMMING
PROGRAMMING
NODE
Installing NODE
Offering user n / nvm version manager choice
Saving current directory as $CURDIR
Going to $TMPDIR: /tmp/tmp.TycFkG3XVT
Look for Windows version of npm

Ensuring we have build-essential installed
Reading package lists...
Building dependency tree...
Reading state information...

build-essential is already the newest version (12.9).
0 upgraded, 0 newly installed, 0 to remove and 93 not upgraded.
Installing n, Node.js version manager
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 43212  100 43212    0     0  81225      0 --:--:-- --:--:-- --:--:-- 81225
n-install: ERROR:


  Target directory '/home/wsargent/n' already exists and is not empty.
  Remove it or make sure it is completely empty, then try again.


Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin"

Installing latest node.js release
/usr/local/pengwin-setup.d/nodejs.sh: line 97: n: command not found
```

**Basic Troubleshooting Checklist**

[X] I have searched Google for the error message.
[X] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[X] I have run Windows 10 updates and restarted.
[X] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

What other troubleshooting have you attempted?

None.

**Pengwin Version**

PENGWIN_VERSION="21.5.4"

**WSL general info**

Run `wslsys` in Pengwin.

Insert here:

```
WSL Version: 2
Locale: en_US
Release Install Date: Sat Sep 12 12:48:31 PDT 2020
Branch: vb_release
Build: 19043
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 1
Windows Theme: dark
Windows Uptime: 3d 6h 19m
WSL Uptime: 1d 12h 5m
WSL Release: Pengwin
WSL Kernel: Linux 5.4.72-microsoft-standard-WSL2
Packages Count: 1109
```

**Comment by crramirez** [comment]
Hello @wsargent,

Thank you for reporting. We will take a look and fix it as soon as possible.

Regards,
Carlos

**Comment by crramirez** [comment]
Hello,

The release 21.7.0 includes a fix for that. Update with `pengwin-setup update`

Please test it.

Regards,
Carlos

**Comment by wsargent** [comment]
Works!
