### ISSUE TITLE
CLOUDCLI INSTALL SCRIPTS FAIL TO RUN

### ISSUE THREAD

**Issue by gpaulmc** [WhitewaterFoundry/Pengwin#702]
Selecting TOOLS  CLOUDCLI from the pengwin-setup application fails to run the install scripts and just hangs.

** To Reproduce **
 run pengwin-setup

Select TOOLS

Select CLOUDCLI

**Expected behavior**
I expected to install aws cli, azure cli and terraform

**Screenshots**
Running upgrade check...
Holding pengwin-base & pengwin-setup to ensure no changes while operating
Selected: TOOLS
TOOLS
CLOUDCLI

**Additional context**

**Basic Troubleshooting Checklist**

[ ] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ x ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ x ] I have run Windows 10 updates and restarted.
[ ] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Run `grep "PENGWIN_VERSION" /etc/os-release` in Pengwin.

Insert here:  PENGWIN_VERSION="21.7.1"

**WSL general info**

Run `wslsys` in Pengwin.

WSL Version: 2
Locale: en_GB
Release Install Date: Thu Jun  4 18:34:19 BST 2020
Branch: vb_release
Build: 19043
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 1.25
Windows Theme: light
Windows Uptime: 0d 1h 22m
WSL Uptime: 0d 0h 44m
WSL Release: Pengwin
WSL Kernel: Linux 4.19.104-microsoft-standard
Packages Count: 524

**Comment by crramirez** [comment]
Hello @gpaulmc ,

Thank you for reporting. This is now fixed. You can run pengwin-setup to get the latest version. We also upgraded Terraform to 1.0.3

We have pending to upgrade the aws cli.

Regards,
Carlos
