### ISSUE TITLE
Cannot see the desktop, only the top bar with xfce4-session

### ISSUE THREAD

**Issue by tacnoman** [WhitewaterFoundry/Pengwin#707]
**Describe the bug**
I installed the x410 and a distro Pengwin. I can run desktop apps (like gedit, nautilus, etc),  but I cannot open the desktop.

**To Reproduce**
1. I open x410 in windows
2. Open the pengwin distro
3. Run in terminal: `DISPLAY=:0 sudo xfce4-session` (just worked with sudo)

The top bar open, but the desktop doesnt appear, like the image bellow

The output in terminal is this:

```bash
$ DISPLAY=:0 sudo xfce4-session
Another Window Manager (Weston WM) is already running on screen :0.0
To replace the current window manager, try "--replace"

(xfwm4:602): xfwm4-WARNING **: 15:58:12.491: Could not find a screen to manage, exiting

(xfsettingsd:612): libupower-glib-WARNING **: 15:58:12.519: Couldn't connect to proxy: Could not connect: No such file or directory
xfsettingsd: Another clipboard manager is already running.

(xfsettingsd:612): xfsettingsd-WARNING **: 15:58:12.616: Failed to get the _NET_NUMBER_OF_DESKTOPS property.

(xfce4-panel:615): garcon-CRITICAL **: 15:58:21.093: garcon_gtk_menu_get_desktop_actions_menu: assertion 'actions != NULL' failed

(xfce4-panel:615): garcon-CRITICAL **: 15:58:21.139: garcon_gtk_menu_get_desktop_actions_menu: assertion 'actions != NULL' failed

(xfce4-panel:615): garcon-CRITICAL **: 15:58:21.182: garcon_gtk_menu_get_desktop_actions_menu: assertion 'actions != NULL' failed

(xfce4-panel:615): garcon-CRITICAL **: 15:58:21.222: garcon_menu_item_get_actions: assertion 'GARCON_IS_MENU_ITEM (item)' failed

(xfce4-panel:615): garcon-CRITICAL **: 15:58:21.222: garcon_gtk_menu_get_desktop_actions_menu: assertion 'actions != NULL' failed

(xfce4-panel:615): Wnck-CRITICAL **: 15:58:21.406: wnck_workspace_is_virtual: assertion 'WNCK_IS_WORKSPACE (space)' failed

(xfce4-panel:615): Wnck-CRITICAL **: 15:58:21.407: wnck_workspace_is_virtual: assertion 'WNCK_IS_WORKSPACE (space)' failed

(xfce4-session:568): xfce4-session-WARNING **: 15:58:21.424: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(xfce4-session:568): xfce4-session-WARNING **: 15:58:21.431: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(xfce4-session:568): xfce4-session-WARNING **: 15:58:21.436: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(wrapper-2.0:622): Gtk-WARNING **: 15:58:21.480: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner XfceArrowButton)

```

**Expected behavior**
Open the desktop like this image in x410 website: https://x410.dev/data/wp-content/uploads/layerslider/x410-intro/intro-slide-93-xfce4-desktop-default-panels-scaled.jpg

**Screenshots**

![Captura de tela 2021-09-05 160015](https://user-images.githubusercontent.com/5348316/132138379-5ac5ba09-612b-4601-9105-ee57b2d2a004.png)

**Additional context**

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have run Windows 10 updates and restarted.
[x] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

What other troubleshooting have you attempted?
I installed all xfce4 libs
I tried to run with environment DISPLAY as `127.0.0.1:0.0`

** Windows Version**
11

**Pengwin Version**

PENGWIN_VERSION="21.8.0"

**WSL general info**

WSL Version: 2
Locale: pt_BR
Release Install Date: Sun Sep  5 06:57:37 -03 2021
Branch: rs_prerelease
Build: 22449
Full Build: 22449.1000.amd64fre.rs_prerelease.210827-1350
Display Scaling: 1
Windows Theme: dark
Windows Uptime: 0d 1h 20m
WSL Uptime: 0d 0h 14m
WSL Release: Pengwin
WSL Kernel: Linux 5.10.43.3-microsoft-standard-WSL2
Packages Count: 1309

Can someone help me?

**Comment by crramirez** [comment]
Hello,

Acording to this message "Another Window Manager (Weston WM) is already running on screen :0.0" you have WSLG enabled. You can:

* Disable WSLg and run xfce4-session without specify DISPLAY

or

* Run X410 with another Display port via command line, and specify the DISPLAY=your host ip:the display port

If you need more clarification just tell me.

Regards,
Carlos

**Comment by tacnoman** [comment]
Thanks for this :)))

I added a file called `.wslconfig` in `C:\Users\<myUsername>` with this content:

```
[wsl2]
guiApplications=false
```

And worked :)
