### ISSUE TITLE
Any way to install without the Microsoft store?

### ISSUE THREAD

**Issue by sam-cogan** [WhitewaterFoundry/Pengwin#708]
**Is your feature request related to a problem? Please describe.**
Is there any way to install Pengwin without the MS store? I have. No issue purchasing it through the store, but access to the store is restricted on my work machine which I would
like to install on. 

**Describe the solution you'd like**
A way to download the msix file or similar and install directly without the store.

**Comment by Manu99it** [comment]
Obviusly you can:

0) Enable windows subsystem for linux in optional features and virtual machine platform. Plenty of guides online

1) download the [latest install.tar.gz](https://github.com/whitewaterfoundry/pengwin-rootfs-builds/releases) for your platform
2) put it in a convenient path like C:\Linux
3) open your windows terminal of preference and import the distro as per microsoft docs: 
    `wsl.exe --import Pengwin C:\Linux C:\Linux\your_architecture_rootfs.tar.gz`
4) boot it with `wsl -d Pengwin`

optional:
5) create an user with adduser or useradd command: `adduser USERNAME`
6) put that user in the sudo group with usermod command: `usermod -g sudo USERNAME`
7) make that user the default at boot modifying the wsl conf: `echo -e "[user]\ndefault=$USERNAME" >> /etc/wsl.conf`
8) exit from wsl and terminate it with `wsl --terminate Pengwin`
9) reboot it with `wsl -d Pengwin` or just `wsl` if its the predefined one and make sure that you can use sudo in you user account. If you can't use sudo you can use the root user with `wsl -d Pengwin -u root` and re-trying to add your user to the sudo group or add the current group to visudo
10) if you wish you can add your pengwin installation to the windows terminal .json (if you use it) or simply start it by any terminal with wsl -d Pengwin

**Comment by crramirez** [comment]
Hello @Manu99it,

Excellent answer.

@sam-cogan currently we don't have prebuilt packages to distribute outside Microsoft Store. This is a request that is being asked more and more. We are looking for a solution for this and allow the distribution outside the store. But it won't be ready soon.

Regards,
Carlos

**Comment by crramirez** [comment]
> Obviusly you can:
> 
> 1. Enable windows subsystem for linux in optional features and virtual machine platform. Plenty of guides online
> 2. download the [latest install.tar.gz](https://github.com/whitewaterfoundry/pengwin-rootfs-builds/releases) for your platform
> 3. put it in a convenient path like C:\Linux
> 4. open your windows terminal of preference and import the distro as per microsoft docs:
>    `wsl.exe --import Pengwin C:\Linux C:\Linux\your_architecture_rootfs.tar.gz`
> 5. boot it with `wsl -d Pengwin`
> 
> optional, but recommended (replace `USERNAME` with anything you want):
> 
> 1. create an user with adduser or useradd command: `adduser USERNAME`
> 2. put that user in the sudo group with usermod or adduser command: `usermod -g sudo USERNAME` or `adduser USERNAME sudo`
> 3. make that user the default at boot modifying the wsl conf: `echo -e "[user]\ndefault=USERNAME" >> /etc/wsl.conf`
> 4. exit from wsl and terminate it with `wsl --terminate Pengwin`
> 5. reboot it with `wsl -d Pengwin` or just `wsl` if it's the predefined one and make sure that you can use sudo in your user account. If you can't use sudo you can use the root user with `wsl -d Pengwin -u root` and re-trying to add your user to the sudo group or add the current group to visudo
> 6. if you wish you can add your pengwin installation to the windows terminal .json (if you use it) or simply start it by any terminal with `wsl -d Pengwin`
> 
> At the end you can safely delete the install tar.gz if all is gone well (do not touch the vhd into c:\Linux because that is your Pengwin installation)

Also, run pengwin-setup update to upgrade to the latest.

**Comment by sam-cogan** [comment]
Yep, that all worked fine, thanks.
