### ISSUE TITLE
Pengwin merchandise stickers

### ISSUE THREAD

**Issue by imgrant** [WhitewaterFoundry/Pengwin#717]
**Is your feature request related to a problem? Please describe.**
It's a feature request. Where can I get a Pengwin sticker for my laptop? 😁
![16358776505324490225197657351724](https://user-images.githubusercontent.com/5815412/139923765-13f87b03-9be4-4c18-910f-881d97cd4736.jpg)

**Describe the solution you'd like**
Obviously, as a valued contributor (tiny PR 😂), I should be given a sticker for free. But willing to purchase.

**Describe alternatives you've considered**
My Red Hat sticker was free, don't you know... (Laptop actually runs Windows 11 and WSL, no RHEL in sight...😂)

**Additional context**
Feel free to close/reject.

**Comment by crramirez** [comment]
Hello @imgrant ,

We have a merchandise store here: https://www.redbubble.com/people/carloswwf/shop?artistUserName=carloswwf

And here: https://www.redbubble.com/people/carloswwf/shop?artistUserName=carloswwf&iaCode=all-stickers you can buy stickers. 

Write me at contact@whitewaterfoundry.com with your mail address. I have some for contributors :D but they are sent via regular mail.

Regards,
Carlos

**Comment by imgrant** [comment]
Many thanks for the store link, I didn't spot that on the blog/web site.

**Comment by crramirez** [comment]
> Many thanks for the store link, I didn't spot that on the blog/web site.

Because it is not there. Thank you for the reminder ;)

**Comment by WSLUser** [comment]
@crramirez You should build out that swag store. Alot of popular FOSS projects do so as a way to increase donations as I'm sure you well know (some are mentioned here by the author). For starters, I think an obvious addition would be a mug as you know how much coffee devs end up having (or maybe tea! for those type of people).

**Comment by crramirez** [comment]
Hello @WSLUser ,

I am not sure if you saw the links in my answer above: https://www.redbubble.com/people/carloswwf/shop?artistUserName=carloswwf 

Or you are talking about build it by ourselves selling the products directly?

**Comment by crramirez** [comment]
Here the mugs: https://www.redbubble.com/people/carloswwf/shop?artistUserName=carloswwf&iaCode=u-mugs
