### ISSUE TITLE
Getting Set Up for The Cardano Blockchain Environment ..

### ISSUE THREAD

**Issue by HamishAndrew** [WhitewaterFoundry/Pengwin#720]
Humour Me it'll be to Your Advantage VERY SOON.

Cardano is screaming up behind the Bitcoin and Ethereum Blockchains. IT IS MASSIVE....

They seem to favour Open Sources of Software, and loads of Would Be Developers, like Me, struggle with Linux.

For example I've spent about 4 x 5hr sessions trying to complete the 10 or so Linux instructions in this Doc below.

I nearly bought a Linux Machine after nearly spending $100 of some Software to solve the Windows 10 Visualiation BIOS bug that blocks the likes of UBUNTO and Pengwin being installed.

Luckily a YouTuber SHOUTED OUT Pengwin. It'd be good to have some more .. Do a YouTube on completing the Document I've provided.

IT'D BE A GREAT TEST OF Pengwin.

So so far I can't get these Commands to run .... And the World might end soon too ..

https://testnets.cardano.org/en/virtual-machines/kevm/getting-started/mallet-end-to-end/

H

**Comment by HamishAndrew** [comment]
If you did such a Video you'd get more than 5,000 hit on it I little doubt. I spent about 20 hrs trying to complete it so there will be plenty who quit. Can the Video running the "How to run Cardano Blockchain KEVN Testnets using Pengwin Linux Platform" . Here is a related Video ... 
1/ 
2/ https://www.youtube.com/watch?v=p3ee19mJUOA
H

**Comment by crramirez** [comment]
Spam
