### ISSUE TITLE
no longer able to install Pengwin

### ISSUE THREAD

**Issue by puskyer** [WhitewaterFoundry/Pengwin#721]
Recently had to reinstall windows 10 on my notebook, ROG G750J, 12 Gig memory 1.5 Tarabyte SSD storage.
at first  Pengwin installed great, then at one point it would no longer load. So I uninstalled it and tried to reinstall it again. now I get an  error Code: 0x80070005 when trying to install it via the app store??

EDIT: also, for some reason I still have some remnants from Pengwin, like explorer integration. 

Update:
Have tried:
- WSreset
- rip all Whitewater related registry entries with regedit
- clean temp files
- FileManager Disk cleananup

I was able to install Ubuntu WSL and it works, but I can not install Pengwin any longer??

any assistance would be appreciated

thank you

**Comment by crramirez** [comment]
Hello @puskyer,

This error usually happens when the WSL service is not accessible. The best bet is to restart the PC and see if it solves the issue. Also, you can check if you have any restrictions on your PC, for example, if you are in a corporate one.

Regards,
Carlos

**Comment by puskyer** [comment]
More information

Windows Version
21H2 (OS Build 19044.1415)

I have run the following in an attempt to fix the issue, but they have not worked. Still get the same error Code: 0x80070005

PS C:\Users\pasqu> sfc /scannow

Beginning system scan.  This process will take some time.

Beginning verification phase of system scan.
Verification 100% complete.

Windows Resource Protection found corrupt files and successfully repaired them.
For online repairs, details are included in the CBS log file located at
windir\Logs\CBS\CBS.log. For example C:\Windows\Logs\CBS\CBS.log. For offline
repairs, details are included in the log file provided by the /OFFLOGFILE flag.
PS C:\Users\pasqu> Winmgmt /verifyrepository
WMI repository is consistent
PS C:\Users\pasqu> DISM.exe /Online /Cleanup-image /Restorehealth  /StartComponentCleanup

Deployment Image Servicing and Management tool
Version: 10.0.19041.844

Image Version: 10.0.19044.1415

[==========================100.0%==========================] The restore operation completed successfully.
The operation completed successfully.
PS C:\Users\pasqu> DISM.exe /Online /Cleanup-Image  /AnalyzeComponentStore

Deployment Image Servicing and Management tool
Version: 10.0.19041.844

Image Version: 10.0.19044.1415

[==========================100.0%==========================]

Component Store (WinSxS) information:

Windows Explorer Reported Size of Component Store : 7.07 GB

Actual Size of Component Store : 7.03 GB

    Shared with Windows : 5.34 GB
    Backups and Disabled Features : 1.21 GB
    Cache and Temporary Data : 477.99 MB

Date of Last Cleanup : 2021-12-19 17:55:19

Number of Reclaimable Packages : 0
Component Store Cleanup Recommended : No

The operation completed successfully.

**Comment by crramirez** [comment]
Also, you can try disabling the WSL service and enabling it again.

**Comment by puskyer** [comment]
> Also, you can try disabling the WSL service and enabling it again.

will give that a try.. thank you

**Comment by puskyer** [comment]
> > Also, you can try disabling the WSL service and enabling it again.
> 
> will give that a try.. thank you

No luck, tried "wsl --shutdown" then tried to install Pengwin still same error??

thank you

**Comment by puskyer** [comment]
thought I would check the Application event log and found the following three events 
not sure if this will help?

` Fault bucket , type 0
Event Name: StoreAgentInstallFailure1
Response: Not available
Cab Id: 0

Problem signature:
P1: Acquisition;Microsoft.WindowsStore_8wekyb3d8bbwe
P2: 80070005
P3: 19044
P4: 1415
P5: Windows.Desktop
P6: P
P7: 
P8: 
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\NonCritical_Acquisition;Micr_18482d22d4c0c421bba25e7abfd5bd78ca3689c7_00000000_9abc9d0d-b324-4362-bc26-6d973e4a4404

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9abc9d0d-b324-4362-bc26-6d973e4a4404
Report Status: 4
Hashed bucket: 
Cab Guid: 0`


`Fault bucket , type 0
Event Name: AppxDeploymentFailureBlue
Response: Not available
Cab Id: 0

Problem signature:
P1: 80070005
P2: 22
P3: 3
P4: windows.appExecutionAlias
P5: 10.0.19041.1415
P6: 6801
P7: 
P8: 
P9: 
P10: 

Attached files:

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 8c9bf896-0cd0-436f-853d-9876f553d527
Report Status: 2147483648
Hashed bucket: 
Cab Guid: 0`

and
`Fault bucket 1596905578457782645, type 5
Event Name: StoreAgentInstallFailure1
Response: Not available
Cab Id: 0

Problem signature:
P1: Acquisition;Microsoft.WindowsStore_8wekyb3d8bbwe
P2: 80070005
P3: 19044
P4: 1415
P5: Windows.Desktop
P6: P
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3970.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\NonCritical_Acquisition;Micr_18482d22d4c0c421bba25e7abfd5bd78ca3689c7_00000000_9abc9d0d-b324-4362-bc26-6d973e4a4404

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9abc9d0d-b324-4362-bc26-6d973e4a4404
Report Status: 268435456
Hashed bucket: fdd07ca64f46909716295929afd0d975
Cab Guid: 0`

**Comment by crramirez** [comment]
Try to disable the Windows Subsystem for Linux Windows Feature. Restart. Enable it again and Restart

**Comment by puskyer** [comment]
Tried that and it did not work, after many hours of trouble shooting, found it was somewhere in the User registry, for I deleted my profile and recreated it. It is now working..
Thank you
