### ISSUE TITLE
Modify the language in Pengwin

### ISSUE THREAD

**Issue by Shadow-XT** [WhitewaterFoundry/Pengwin#735]
I want to know how to modify the language of Pengwin. In Pengwin, use dpkg-reconfigure locales to change the language of the system to Chinese. After modification, the language under the default user changes to Chinese, but it is still English under the root user. Even if I use pengwin setup to modify it, it is still English, and the default language of the new user is still English after you use the ‘adduser’ command to create a new user, But in Ubuntu or Kali of WSL, I can modify the language of default user, new user and root user at the same time

**Comment by crramirez** [comment]
Hello @Shadow-XT 

Why did you close it? did you solve the issue?

Regards,
Carlos

**Comment by Shadow-XT** [comment]
Yes, I have solved the problem.

**Comment by Shadow-XT** [comment]
> 你好@Shadow-XT
> 
> 你为什么关闭它？你解决了这个问题吗？
> 
> 问候， 卡洛斯

Yes, I have solved the problem.
