### ISSUE TITLE
Install Pengwin after WSL2 is installed still using WSL1

### ISSUE THREAD

**Issue by laurinkeithdavis** [WhitewaterFoundry/Pengwin#737]
New Windows 10 installation
WSL2 installed
Install Pengwin
Uses WSL1

Why is it not using WSL2 initially? Why do I have to upgrade Pengwin to WSL2?

```
C:\windows\system32>wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop         Running         2
  docker-desktop-data    Running         2
  WLinux                 Running         1
```

**Comment by crramirez** [comment]
Before installing any distro at least the first time you need to set WSL2 as default:

wsl --set-default-version 2

**Comment by laurin1** [comment]
You know, I was thinking about that after I posted this issue. Now, can someone tell me why in the world WSL2 is not the default? Also, why does Docker not have this issue? It automatically uses WSL2 if that is available.

**Comment by crramirez** [comment]
WSL 2 is the default in Windows 11 but not Windows 10. I assume that for backward compatibility they only did that in Windows 11. Docker Desktop uses wsl --import to create their distros and you can pass the desired version to this command
