### ISSUE TITLE
VSCode doesn't launch with code . command. Other solutions have not worked.

### ISSUE THREAD

**Issue by elkirk** [WhitewaterFoundry/Pengwin#742]
**Describe the bug**

VS Code will not launch with `code .` command. Running `top` shows code is running. If I launch vscode from my windows start menu, I can use the "Open a Remote Window" option to open an instance of vscode in my pengwin environment (vscode lists it as WLinux).

x410 is running with Allow Public Access enabled. Windowed Apps is checked, but if I select Floating Desktop an opaque window appears.

I'm not totally clear on why we need to use x410 for vscode, given that Microsoft has the extension for remote windows, but I'd like to resolve this issue so that I can launch code with the `code .` command, which works natively on an Ubuntu WSL instance.

**To Reproduce**
1. clean install
2. `pengwin-setup`
3. install only vscode, base gui tools, and the x410 autostart
4. running `code .` returns nothing, but running `top` shows code is running.

**Expected behavior**
Described above

**Screenshots**

**Additional context**
I have tried:

- [everything mentioned here](https://github.com/WhitewaterFoundry/Pengwin/issues/586)
- [and here](https://github.com/WhitewaterFoundry/Pengwin/issues/541)
- [and also here](https://github.com/WhitewaterFoundry/Pengwin/issues/416#issuecomment-483790205)

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[x] I have run Windows 10 updates and restarted.
[x] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

What other troubleshooting have you attempted?
About half a dozen uninstalls and reinstalls while going through the various other issues I linked.

**Pengwin Version**

PENGWIN_VERSION="22.1.6"

**WSL general info**

Release Install Date: Fri Jun  4 13:29:54 MDT 2021
Branch: vb_release
Build: 19042
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 2.5
Locale (Windows): en_US
Theme (Windows): dark
Uptime (Windows): 0d 0h 5m
Version (WSL): 2
Uptime (WSL): 0d 0h 4m
Release: Pengwin
Kernel: Linux 5.10.16.3-microsoft-standard-WSL2
Packages: 407

**Comment by elkirk** [comment]
Interestingly, I was able to resolve this (kind of) by doing the following:

(This is post `pengwin-setup` with vscode, gui tools, and x410 autostart install)

1. I ran pengwin-setup and uninstalled vscode and x410 autostart.
2. I launched vs code from windows start menu
3. WSL-Remote extension was already installed- disable it
4. When trying to reload, vscode forces an update/reinstall of the extension
5. Once installed, I opened a remote window from this instance of vscode in WLinux
6. Close everything (vscode, pengwin), relaunch pengwin. Now, `code .` works as expected and launches vscode without x410 with a remote session activated.

Not sure what this means, but it sort of seems like using an x-server isn't necessary for vscode and maybe just complicates things?

**Comment by crramirez** [comment]
Hello @elkirk,

From your post and your comment, it looks like you are using Visual Studio Code in Windows and connecting to WSL via WSL Remote. In this case, you don't need to do anything in Pengwin.

The options in pengwin-setup and x410 autostart are needed to install the Linux version of Visual Studio Code, which is required in case of anything fails with the Windows version and the WSL-Remote. But this is not the recommended way.

After reading this issue, I'll add a message in the pengwin-setup telling that this is not the recommended way.

Regards,
Carlos

**Comment by elkirk** [comment]
@crramirez that makes sense. Thanks for the reply, I'll mark this as closed.

**Comment by crramirez** [comment]
Added this change to specify in the menu that the Linux version is the one to be installed:

https://github.com/WhitewaterFoundry/pengwin-setup/commit/3b595ab804fe5f96d3c505b12481a6d549d38021
