### ISSUE TITLE
Make sure Mesa is built with D3D12 and Zink Gallium drivers

### ISSUE THREAD

**Issue by WSLUser** [WhitewaterFoundry/Pengwin#744]
**Is your feature request related to a problem? Please describe.**
D3D12 and Zink drivers for Mesa are not built by default when using the "auto" option. They must be explicitly enabled. Therefore even if you use the WSL2 kernel with the DirectX 12 graphics driver support, you still need the support from Mesa for WSLG. Zink should also be included because it allows running Vulkan-based applications and there has been some interesting features added to allow Vulkan integration into D3D12 where applicable, which of course would be WSL2 (technically also Windows itself if Mesa was built for Windows instead of Linux). Therefore Zink is also required to cover broader base of GUI applications and software.
**Describe the solution you'd like**
I'd like Pengwin to either have these Gallium driver configuration options enabled and build Mesa itself or ensure that Debian upstream has them so Pengwin users can install Mesa and get the support for free (no out of tree patches needed from Pengwin from Debian).
**Describe alternatives you've considered**
Build Mesa myself, not the greatest way to update it. This is something all distros should be enabling.
**Additional context**
Both are still under development but they are stable enough as it's been quite some time since they were first released and do work just fine for most part on native Linux (Zink that is)

**Comment by WSLUser** [comment]
I would add this also needs to be done for Fedora Remix but I can file an issue over there too for tracking purposes.

**Comment by crramirez** [comment]
Hello @WSLUser,

We compile mesa and enable Direct 3D 12. If you have already enabled zink in the compilation, can you please share with us your steps? Or the page that you used, this will speed the thing on our side to have a solution as soon as possible.

Regards,
Carlos

**Comment by WSLUser** [comment]
You add it to same way as D3D12 next to the 'auto' option.

**Comment by WSLUser** [comment]
See for Clear Linux build steps for D3D12 and Zink. Glad they decided to add it, that's one more distro we can use by default now. https://github.com/clearlinux-pkgs/mesa/commit/1af9a82f531169cef43e55e55e30b4ce60752e50

**Comment by WSLUser** [comment]
Any updates?

**Comment by crramirez** [comment]
Not yet but it is in the queue 😕. We are finetunning an improvement on Pengwin Enterprise and then the next is Pengwin.

**Comment by crramirez** [comment]
Hello @WSLUser,

In the development version of Pengwin, you can now try Mesa 22.2.0 with Open GL 4, and Zink Gallium drivers installed:

![image](https://user-images.githubusercontent.com/8397379/188335287-ca9182cc-0910-4dae-9a16-8eb944bb27b3.png)

Just do a `pengwin-setup update`
