### ISSUE TITLE
 error: 0x800701bc

### ISSUE THREAD

**Issue by PengwinEnterpriseUser** [WhitewaterFoundry/Pengwin#750]
I'm trying to install Pengwin on my Windows 11 installation and it seems that it has a kernel issue.  The opening command windows says,

Unpacking Pengwin, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800701bc
Error: 0x800701bc WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel

Press any key to continue...

So why doesn't your Flagship product work in Windows 11?

Roger

**Comment by crramirez** [comment]
Hello @PengwinEnterpriseUser,

Of course, it works with Windows 11 but you need to update it (Windows 11)

In an elevated command prompt, type: `wsl --update`

Regards

**Comment by PengwinEnterpriseUser** [comment]
Yep, that fixed it.  I would not have found that answer in a million years.  Thank you.

Roger


On Wed, 24 Aug 2022 13:48:45 -0700, Carlos Rafael Ramirez ***@***.***> wrote:
 
 

Hello @PengwinEnterpriseUser,

Of course, it works with Windows 11 but you need to update it (Windows 11)

In an elevated command prompt, type: wsl --update

Regards
