### ISSUE TITLE
Clarification `README.md`'s description of systemd

### ISSUE THREAD

**Issue by linghengqian** [WhitewaterFoundry/Pengwin#755]
**Is your feature request related to a problem? Please describe.**

- No.

**Describe the solution you'd like**

- Clarification `README.md`'s description of systemd. It indicates that systemd has been removed. But in WSL2, we should be able to edit `/etc/wsl.conf` content to open built-in systemd support, unless there are any additional changes?
- ![image](https://user-images.githubusercontent.com/20187731/201295440-85bbdef1-e2eb-4ae3-bd79-24b6eeb08e12.png)

**Describe alternatives you've considered**

- Null.

**Additional context**
- Null.

**Comment by crramirez** [comment]
Hello @linghengqian 

If you run `pengwin-setup update` you will see that **systemd** will get installed.

We are releasing soon an update with this support.

Thank you for pointing out that we need to update the README

Regards,
Carlos

**Comment by linghengqian** [comment]
@crramirez 
- Oh,  I saw it on the https://github.com/WhitewaterFoundry/pengwin-setup/pull/374 🙈, thank you! 

- But is it possible that in the future, systemd will be turned on by default? `Ubuntu(Preview)` has done this and I believe the importance of systemd (especially snapcraft and flatpak) is definitely worth it 😆 As the snapd version of pemgwin is not high enough, I verified the use of snapcraft in Ubuntu 22.04 WSL.

**Comment by crramirez** [comment]
Yes, you can now test the SystemD in pengwin-setup; we are in the process of releasing all the changes to the Store image.

The short answer is yes in the future will be turned on by default

Long one:

Microsoft said that they are looking forward to enabling systemD by default. But for now, they don't want to break existing distros.

We will observe the evolution of the adoption of systemD on WSL to see when is the best time to make it as default because Pengwin supports SystemD on Windows 10 as well. 

I am interested in why the snap version shipped by Pengwin didn't work for you, because in this case, we should find ways to backport it.

**Comment by linghengqian** [comment]
> I am interested in why the snap version shipped by Pengwin didn't work for you, because in this case, we should find ways to backport it.
> 

- Hi, I have noticed that the snapd used by pengwin is from the debian 11 source, which involves the WSL determination of older versions of snapd. According to https://github.com/microsoft/WSL/issues/9026#issuecomment-1295870810 , snapd fixes for Ubuntu are only available in Ubuntu 18.04, 20.04 and 22.04. 

- Both Ubuntu 22.10 and Debian 11 need to wait for snapd 2.57.5 to be released to their apt source. There's nothing we can do about it.

**Comment by crramirez** [comment]
Yes, maybe is an Ubuntu thing. Because I don't see those problems in Pengwin or in Fedora Remix, even on Pengwin Enterprise

![image](https://user-images.githubusercontent.com/8397379/201494321-d81bf29e-8384-483f-a569-feb18cb12797.png)

**Comment by crramirez** [comment]
I removed the line in the readme regarding SystemD

**Comment by linghengqian** [comment]
- Thank you, I will close this issue -- I assume https://github.com/WhitewaterFoundry/Pengwin/blob/master/README.zh-hans.md also needs to be updated?

**Comment by crramirez** [comment]
The team member that speaks Chinese is no longer with us. Could you please make the update there?

**Comment by linghengqian** [comment]
- I will be submitting PR for Chinese README.md soon as I am working on another project.
