### ISSUE TITLE
Desktop Environment - Resolution when you run Desktop on two different displays it is not good.

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Pengwin#757]
**Describe the bug**
Desktop Environment - Resolution when you run Desktop on two different displays it is not good.

**To Reproduce**
1. Connect second monitor with different resolutions.
2. run XFCE desktop (full screen). 
3. XFCE desktop run as expected but size of components is (text, or text box login for example) two small in the display with high resolution.

**Expected behavior**
Resolutions should be correct based on display behavior

**Screenshots**
First Monitor High resolutions (3840 x 2160 .... maybe it is to high but it is standard on my laptop)

![Windows Subsystem for Linux 11_21_2022 1_22_33 PM](https://user-images.githubusercontent.com/64733228/203054183-fe18f064-3fcc-4c6c-a61a-a1399cc77c7d.png)

Second Monitor lower resolutions (1920 x 1080)

![Windows Subsystem for Linux 11_21_2022 1_24_20 PM](https://user-images.githubusercontent.com/64733228/203054570-d877af2d-3828-4307-803e-29786bbecce4.png)

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version:**
PENGWIN_VERSION="22.11.4"

**WLS general Info:**
Release Install Date: Wed Sep 21 12:14:41 CEST 2022
Branch: ni_release
Build: 22621
Full Build: 22621.1.amd64fre.ni_release.220506-1250
Display Scaling: 2.5
Locale (Windows): en_US
Theme (Windows): light
Uptime (Windows): 0d 0h 12m
Version (WSL): 2
Uptime (WSL): 0d 0h 10m
Release: Pengwin
Kernel: Linux 5.15.74.2-microsoft-standard-WSL2
Packages: 958
IPv4 Address: 172.22.205.55
System Type (Windows): Desktop

Edition	Windows 11 Pro for Workstations
Version	22H2
Installed on	‎9/‎21/‎2022
OS build	22621.819
Experience	Windows Feature Experience Pack 1000.22636.1000.0

Processor	Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz   2.11 GHz
Installed RAM	48.0 GB (47.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points

**Comment by crramirez** [comment]
Hello @Jack31071973,

Sadly XRDP won't react to DPI changes as the remote desktop does with Windows. You must decide the scale factor that you want to use.

For 1920x1080 usually, 1 is good
For 3840, you can try with two.

To change it, use the following command:

```
#For 2
scale="2"
sudo sed -i "s/^\(.*scale_factor=\)\([0-9]*\.\?[0-9]*\)$/\1${scale}/" /etc/profile.d/hidpi.sh

#For 1
scale="1"
sudo sed -i "s/^\(.*scale_factor=\)\([0-9]*\.\?[0-9]*\)$/\1${scale}/" /etc/profile.d/hidpi.sh

#For 1.5
scale="1.5"
sudo sed -i "s/^\(.*scale_factor=\)\([0-9]*\.\?[0-9]*\)$/\1${scale}/" /etc/profile.d/hidpi.sh
```
Then start the desktop environment again.
