### ISSUE TITLE
wslu Update Error

### ISSUE THREAD

**Issue by PeteSL** [WhitewaterFoundry/Pengwin#760]
Running update tries to update wslu (wslu_4.0.0.d1671785608-1pengwin1_all.deb) but fails with the following error. Sounds like it needs to be repackaged as it is trying to overwrite a directory with a file.

```
dpkg: error processing archive /var/cache/apt/archives/wslu_4.0.0.d1671785608-1pengwin1_all.deb (--unpack):
 trying to overwrite directory '/usr/share/applications' in package python3.9 3.9.2-1 with nondirectory

```

**Comment by downsideuped** [comment]
I have the same problem. I started reinstalling the packages that dpkg was complaining about. But this only shifted the package dpkg complained about, and eventually would cycle back to a package that was already reinstalled. 

I was tempted to try removing wslu (and pengwin-setup through dependency) but decided to wait to see if there will be fix. I did try to reinstall wslu with the current package (4.0.0.d1665041018-1pengwin1)

results of "apt list --upgradable -a" :
wslu/bullseye 4.0.0.d1671817915-1pengwin1 all [upgradable from: 4.0.0.d1665041018-1pengwin1]
wslu/bullseye 4.0.0.d1671817462-1pengwin1 all
wslu/bullseye 4.0.0.d1671817289-1pengwin1 all
wslu/bullseye 4.0.0.d1671812371-1pengwin1 all
wslu/bullseye 4.0.0.d1671785608-1pengwin1 all
wslu/bullseye 4.0.0.d1671781599-1pengwin1 all
wslu/bullseye,now 4.0.0.d1665041018-1pengwin1 all [installed,upgradable to: 4.0.0.d1671817915-1pengwin1]

but that failed in the same manner.

**Comment by magneticflux-** [comment]
Possibly related to this change: https://github.com/wslutilities/wslu/pull/255

**Comment by crramirez** [comment]
Hello all,

Thanks you for reporting. I'll check the behavior and this new commit. Meanwhile I deleted these package from the repo.

Regards,
Carlos

**Comment by PeteSL** [comment]
Success! Thank you!
`Unpacking wslu (4.0.0.d1671867620-1pengwin1) over (4.0.0.d1665041018-1pengwin1) ...`
