### ISSUE TITLE
Go version is outdated

### ISSUE THREAD

**Issue by oddeirik** [WhitewaterFoundry/Pengwin#761]
**Describe the bug**

**To Reproduce**
1. Run pengwin-setup
2. Select 'PROGRAMMING'
3. Select 'GO'
4. Version downloaded and installed is not the latest/most current version

**Expected behavior**
The latest stable Go version installed (which at the time of creating this issue is 1.19.4).

**Additional context**
```
❯ pengwin-setup
Starting pengwin-setup.
Updating package database
Running upgrade check...
Holding pengwin-base & pengwin-setup to ensure no changes while operating
Selected: PROGRAMMING
PROGRAMMING
GO
Saving current directory as $CURDIR
Going to $TMPDIR: /tmp/tmp.oPLEFCQc3h
Downloading Go using wget.
--2023-01-02 11:20:38--  https://dl.google.com/go/go1.15.8.linux-amd64.tar.gz
Resolving dl.google.com (dl.google.com)... 142.250.74.78, 2a00:1450:400f:802::200e
Connecting to dl.google.com (dl.google.com)|142.250.74.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 121066822 (115M) [application/gzip]
Saving to: ‘go1.15.8.linux-amd64.tar.gz’
2023-01-02 11:20:42 (29.5 MB/s) - ‘go1.15.8.linux-amd64.tar.gz’ saved [121066822/121066822]

Unpacking tar binaries to /usr/local/go.
Creating ~/go/ for your projects.
Creating ~/go/ default structure.
Setting Go environment variables GOROOT, GOPATH, and adding Go to PATH with export.
Saving Go environment variables to /etc/profile.d/go.sh so they will persist.
#!/bin/sh

export GOROOT="/usr/local/go"
export GOPATH="${HOME}/go"
export PATH="${GOPATH}/bin:${GOROOT}/bin:/usr/local/go/bin:${PATH}"

Also for fish.
#!/bin/fish

set --export GOROOT "/usr/local/go"
set --export GOPATH "$HOME/go"
set --export PATH "$GOPATH/bin:$GOROOT/bin:/usr/local/go/bin:$PATH"

Returning to /home/[REDACTED]
Cleaning up /tmp/tmp.oPLEFCQc3h
Unholding pengwin-base & pengwin-setup
```

**Basic Troubleshooting Checklist**

[X] I have searched Google for the error message.
[X] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[X] I have run Windows 10 updates and restarted.
[X] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Run `grep "PENGWIN_VERSION" /etc/os-release` in Pengwin.

Insert here:
`PENGWIN_VERSION="22.11.4"`

**WSL general info**

Run `wslsys` in Pengwin.

Insert here:
```
Release Install Date: Wed Oct  5 10:39:39 CEST 2022
Branch: ni_release
Build: 22623
Full Build: 22621.1.amd64fre.ni_release.220506-1250
Display Scaling: 1
Locale (Windows): nb_NO
Theme (Windows): dark
Uptime (Windows): 15d 17h 55m
Version (WSL): 2
Uptime (WSL): 0d 0h 44m
Release: Pengwin
Kernel: Linux 5.15.79.1-microsoft-standard-WSL2
Packages: 972
IPv4 Address: 172.21.15.214
System Type (Windows): Desktop
SystemD Status: disabled
```

**Comment by crramirez** [comment]
Hello,

Thanks for reporting, we will update it.

**Comment by crramirez** [comment]
Hello, 

The Go version was increased. Run pengwin-setup again to install it

Regards,

**Comment by oddeirik** [comment]
Just tested it and pengwin-setup now downloaded version 1.19.4. Thank you!
