### ISSUE TITLE
Unable to install a package due to perl package dependency error

### ISSUE THREAD

**Issue by gellenburg** [WhitewaterFoundry/Pengwin#767]
**Describe the bug**
I'm trying to install Webmin from the Webmin Debian apt repository. It's complaining about `perlapi` but `perl` is already installed.

**To Reproduce**
1. `curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh`
2. `sudo sh setup-repos.sh`
3. `sudo apt-get update`
4. `sudo apt-get install webmin`

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libauthen-pam-perl : Depends: perlapi-5.32.0
 libio-pty-perl : Depends: perlapi-5.32.0
 libnet-ssleay-perl : Depends: perlapi-5.32.0
E: Unable to correct problems, you have held broken packages.
```
5.

```
gme@DESKTOP-TIEUOMF:~$ dpkg -l | grep perl-base
ii  perl-base                         5.36.0-7                          amd64        minimal Perl system
gme@DESKTOP-TIEUOMF:~$
```

***Perl 5.36.0 is already installed.***

**Expected behavior**
Webmin to install. It installs on Ubuntu.

**Screenshots**

**Additional context**

**Basic Troubleshooting Checklist**

[X] I have searched Google for the error message.
[X] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[X] I have run Windows 10 updates and restarted.
[X] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

What other troubleshooting have you attempted?

Might be related to https://github.com/WhitewaterFoundry/Pengwin/issues/196 but that issue is 5 years old and there's no way I'm downgrading my system.

Insert here:

**Pengwin Version**

Run `grep "PENGWIN_VERSION" /etc/os-release` in Pengwin.

Insert here:

`PENGWIN_VERSION="23.03.1"`

**WSL general info**

Run `wslsys` in Pengwin.

Insert here:

```
gme@DESKTOP-TIEUOMF:~$ wslsys
Release Install Date: Mon Mar  6 18:59:38 EST 2023
Branch: ni_release
Build: 22621
Full Build: 22621.1.amd64fre.ni_release.220506-1250
Display Scaling: 1.25
Locale (Windows): en_US
Theme (Windows): dark
Uptime (Windows): 0d 6h 24m
Version (WSL): 2
Uptime (WSL): 0d 3h 22m
Release: Pengwin
Kernel: Linux 5.15.90.1-microsoft-standard-WSL2
Packages: 563
IPv4 Address: 172.25.26.70
System Type (Windows): Desktop
SystemD Status: disabled
gme@DESKTOP-TIEUOMF:~$
```

**Comment by crramirez** [comment]
We will check it. Thanks for reporting

**Comment by crramirez** [comment]
Hello @gellenburg,

I tried to reproduce the error with a clean installation of Pengwin and in fact the perl-base included is:

```bash
~$ dpkg -l | grep perl-base
ii  perl-base                         5.32.1-4+deb11u2               amd64        minimal Perl system
```

Could you share your `/etc/apt/sources.list` file?

**Comment by crramirez** [comment]
Check of your /etc/apt/sources.list has the testing repo enabled and if it does, comment it. Then `sudo apt uodate`

**Comment by andika-eka** [comment]
I was having the same problem on ubuntu. I forced ubuntu version using synaptic on the perl-base package. if you don't have synaptic you can try download the .deb manually.
