### ISSUE TITLE
Troubleshooting Docker-ce installation

### ISSUE THREAD

**Issue by jimmerk** [WhitewaterFoundry/Pengwin#768]
I have docker-ce installed in Pengwin on WSL2 (v 1.2.5). I'm able to pull images and create containers, but none of the containers are able to see outside the docker network. They can't ping the host machine, my router or wan. Is there anything unique required in this distro to enable/configure networking in docker-ce containers? Or are there any specific instructions for docker installation on Pengwin? I followed a debian-based installation method. I'm also curious if there's a better approach to getting docker working. Maybe pengwin-setup > Docker secure bridge?

**Comment by jimmerk** [comment]
This was fixed by disabling auto generation of resolv.conf and adding my local nameserver. For some reason the (auto-generated) resolv.conf contained a 172 address. Not sure why.

**Comment by crramirez** [comment]
Hello

It should have an internal DNS thus the 172 address. Do you have any VPN?

You can also check this: https://github.com/WhitewaterFoundry/Pengwin/discussions/734 Debian installation of docker uses an iptables incompatible with WSL

**Comment by jimmerk** [comment]
@crramirez It sounds like I need to revert my dns changes and keep internal dns, and solve the problem another way. Correct?

**Comment by crramirez** [comment]
Hello @jimmerk,

Many people work in this way without problems, especially the ones using VPNs. If it works for you leave it in this way.

Regards,
Carlos
