### ISSUE TITLE
Node update problems - Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Pengwin#780]
**Describe the bug**
Every time I do sudo apt update I am getting the following warning:
W: https://deb.nodesource.com/node_14.x/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

and I do not understand why, this should be fixed as far as I remember.

**To Reproduce**
1. Open Pengwin, run Pengwin-setup update (everything is working fine)
2. run sudo apt update and you will get the following warning:
    W: https://deb.nodesource.com/node_14.x/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring 
    (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

**Expected behavior**
Should not be the warning message

**Screenshots**

![image](https://github.com/WhitewaterFoundry/Pengwin/assets/64733228/b6177701-b47f-4ce4-a570-c8f15eb05695)

**Additional context**
That version of node is not installed as far as I can check
`jack3173@LAPTOP-P9C2E5RE:~$ node -v
v21.1.0
jack3173@LAPTOP-P9C2E5RE:~$`

**Basic Troubleshooting Checklist**

[x ] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have run Windows 10 updates and restarted.
[ ] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

PENGWIN_VERSION="23.07.2"

**WSL general info**

Run `wslsys` in Pengwin.

`jack3173@LAPTOP-P9C2E5RE:~$  `wslsys`
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
/usr/bin/wslvar: line 273: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
/usr/bin/wslvar: line 276: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
/usr/bin/wslsys: line 273: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
/usr/bin/wslsys: line 276: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
/usr/bin/wslsys: line 273: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
/usr/bin/wslsys: line 276: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
/usr/bin/wslsys: line 273: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
/usr/bin/wslsys: line 276: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
/usr/bin/wslsys: line 273: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
/usr/bin/wslsys: line 276: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
-bash: Release: command not found
jack3173@LAPTOP-P9C2E5RE:~$ wslsys
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
Release Install Date: Thu Jan  1 01:00:00 CET 1970
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
Branch:
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
Build:
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
Full Build:
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
/usr/bin/wslvar: line 273: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
/usr/bin/wslvar: line 276: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
/usr/bin/wslsys: line 273: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
/usr/bin/wslsys: line 276: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
Display Scaling:
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
/usr/bin/wslsys: line 273: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
/usr/bin/wslsys: line 276: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
Locale (Windows):
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
Theme (Windows): dark
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
/usr/bin/wslsys: line 273: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
/usr/bin/wslsys: line 276: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
Uptime (Windows): 0d 0h 0m
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
Version (WSL): 1
Uptime (WSL): 0d 0h 31m
Release: Pengwin
Kernel: Linux 5.15.90.1-microsoft-standard-WSL2
Packages: 1288
IPv4 Address: 172.18.60.41
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
/usr/bin/wslsys: line 273: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
/usr/bin/wslsys: line 276: [: : integer expression expected
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/chcp.com
System Type (Windows): Unknown
run-detectors: unable to find an interpreter for /mnt/c/Windows/System32/reg.exe
SystemD Status: N/A`

**Comment by Jack31071973** [comment]
@crramirez may I just use this command to fix it?
`sudo apt-add-repository --remove  https://deb.nodesource.com/node_14.x/dists/bullseye/InRelease`

**Comment by crramirez** [comment]
Hello @Jack31071973 ,

I was looking for time to make the proper tests in order to help you. But with the heck of the simultaneous release of Fedora and Redhat, we haven't had time to do anything else.

Node 14 is pretty old and it was installed I the old way. You can use the pengwin-setup Uninstaller to get rid of it and then use it to install a newer one. The latest LTS version is 20.

If you see any inconvenience with that, simply ignore the warning, it won't hurt in any way.

The error that you saw with wslsys is because sometimes WSL lose the Interop. Just issue the wsl --shutdown command from Powershell to fix it.

Hope it helps

**Comment by Jack31071973** [comment]
@crramirez thank you your fix works, so I am closing it.

**Comment by Jack31071973** [comment]
done.
