### ISSUE TITLE
App Missing in Microsoft Store

### ISSUE THREAD

**Issue by MJK1234** [WhitewaterFoundry/Pengwin#783]
Hello, awhile back now I purchased the Pengwin OS on the Microsoft store. Actually, to be accurate I made a donation to Whitewater foundry so I could obtain the program. Since then, I have had to reset my computer. When I went on the Microsoft store today, to re-install the OS I found that the app was no longer in my list and wanted me to purchase it again when I went to the app page itself. I have attached a copy of the donation I made because I was unable to download the app at the time. Whitewater Foundry has a great product in the Pengwin OS. It's unfortunate that you have decided to sell this product exclusively on the Microsoft Store, their platform seems to have a lot of problems. This would have easily been avoided if I had a hard copy of the program saved to an external drive. I hope this issue can be easily resolved, thank you for your time.   

mjkightley@gmail.com

[Receipt.pdf](https://github.com/WhitewaterFoundry/Pengwin/files/13780074/Receipt.pdf)

**Comment by crramirez** [comment]
Hello @MJK1234

This is the link : https://apps.microsoft.com/detail/9NV1GV1PXZ6P

The application is still on the store don't worry.

Regards,
Carlos

**Comment by MJK1234** [comment]
Hi Carlos, I,m pretty sure it was you who helped me the first time. The
link worked, I was thrown off at first because it still asked me to pay. I
clicked the link anyway and it gave me the option to install. Thanks for
your help. Cheers
