### ISSUE TITLE
NLI e IBUS installation

### ISSUE THREAD

**Issue by marcorotondi** [WhitewaterFoundry/Pengwin#784]
**Describe the bug**
I try to install NLI support but after 30 min installation is pending.

**To Reproduce**
1) pengwin-setup
2) GUI
3) NLI
4) IBUS

**Expected behavior**
installation procedure completed

**Screenshots**
![image](https://github.com/WhitewaterFoundry/Pengwin/assets/22365419/f54858e1-00a0-4ae7-81d3-e9de600ae98f)

**Additional context**
wsl --version
Versione WSL: 2.1.1.0
Versione kernel: 5.15.146.1-2
Versione WSLg: 1.0.60
Versione MSRDC: 1.2.5105
Versione Direct3D: 1.611.1-81528511
Versione DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versione di Windows: 10.0.22631.3085

**Basic Troubleshooting Checklist**

[ ] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have run Windows 10 updates and restarted.
[ ] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Insert here:

PENGWIN_VERSION="23.07.2"

**WSL general info**

Release Install Date: Mon Feb 20 10:24:40 CET 2023
Branch: ni_release
Build: 22631
Full Build: 22621.1.amd64fre.ni_release.220506-1250
Display Scaling: 1
Locale (Windows): it_IT
Theme (Windows): dark
Uptime (Windows): 0d 3h 1m
Version (WSL): 1
Uptime (WSL): 0d 1h 21m
Release: Pengwin
Kernel: Linux 5.15.146.1-microsoft-standard-WSL2
Packages: 1071
IPv4 Address: 172.19.155.110
System Type (Windows): Desktop
SystemD Status: N/A

**Comment by crramirez** [comment]
Hello @marcorotondi,

Thank you for reporting.

We will take a look.

Regards,
Carlos

**Comment by crramirez** [comment]
Hello,

Thanks for reporting, the error was fixed. Please run again pengwin-setup and let it update itself.

Regards,
Carlos

**Comment by marcorotondi** [comment]
Hi, thanks i test it roday and confirm all works

**Comment by marcorotondi** [comment]
Hi, thanks i test it roday and confirm all works
