### ISSUE TITLE
strange behaviours: copy and paste some URL and numeric keypad that does not work

### ISSUE THREAD

**Issue by aborruso** [WhitewaterFoundry/Pengwin#785]
Hi,
I have these really strange behaviours. I don't know if they are related, but they appeared together.

## Copy and paste an URL in the shell

I use Windows Terminal. If I copy the URL "https://github.com/" and paste it in the shell the dots are replaced by `n`: I have `https://githubncom/`

![image](https://github.com/WhitewaterFoundry/Pengwin/assets/30607/95d78996-3d19-4824-a0eb-6c9492db858f)

But it works in the other shells

![image](https://github.com/WhitewaterFoundry/Pengwin/assets/30607/29a41606-3a94-4478-9c5d-115daf87572f)

## Numeric keypad does not work

If I open pengwin shell and I click `1`, `2`, ecc., `ENTER` in the numeric keypad, nothing happens.

If I open the other shells the numeric keypad buttons work.

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[x] I have run Windows 10 updates and restarted.
[x] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Run `grep "PENGWIN_VERSION" /etc/os-release` in Pengwin.

Insert here: PENGWIN_VERSION="24.02.0"

**WSL general info**

Run `wslsys` in Pengwin.

Insert here:

```
Release Install Date: Thu Jan  5 16:10:17 CET 2023
Branch: ni_release
Build: 22631
Full Build: 22621.1.amd64fre.ni_release.220506-1250
Display Scaling: 1
Locale (Windows): it_IT
Theme (Windows): light
Uptime (Windows): 2d 2h 17m
Version (WSL): 2
Uptime (WSL): 0d 0h 12m
Release: Pengwin
Kernel: Linux 5.15.133.1-microsoft-standard-WSL2
Packages: 1473
IPv4 Address: 172.21.207.137
System Type (Windows): Desktop
SystemD Status: enabled
```

**Comment by aborruso** [comment]
It could be a ohmyzsh problem, because if I run bash, I have no problem.
I have opened a related issue https://github.com/ohmyzsh/ohmyzsh/issues/12196

**Comment by crramirez** [comment]
Interesting, let's see what they say. Thanks for reporting

**Comment by aborruso** [comment]
> Interesting, let's see what they say. Thanks for reporting

We are doing a lot of testing, but we still don't get to the bottom of it

**Comment by aborruso** [comment]
@crramirez please could you make a test?

Apparently, the numeric keypad [never works](https://github.com/ohmyzsh/ohmyzsh/issues/12196#issuecomment-1931730573) in oh-myzsh.
Can you confirm that in pengwin this is the case for you? That if you click Enter in the numeric keypad nothing happens to you?

**Comment by ygol** [comment]
got the same problem since few days/weeks

**Comment by aborruso** [comment]
Please, can someone who uses pengwin tell me if the enter key on the numeric keypad works for them?

@crramirez can you do this test?

**Comment by ygol** [comment]
the enter key on the numeric keypad doesn't work for me

**Comment by aborruso** [comment]
> the enter key on the numeric keypad doesn't work for me

Did it previously work for you?

**Comment by aborruso** [comment]
@ygol do you also have the problem of copying and pasting URLs, with replacing `.` with `n`?

**Comment by ygol** [comment]
no. the pasting works ok. just all the keys of the number pad

**Comment by aborruso** [comment]
I'm running pengwin with Windows Terminal Preview app. If I switch to the Windows Terminal (the non preview version) all is working correctly . 
I found out thanks to @crismanzoni

**Comment by ygol** [comment]
indeed. I am also using the terminal preview :)

**Comment by crramirez** [comment]
Looks like this is related https://github.com/microsoft/terminal/issues/16641

**Comment by ygol** [comment]
this is great. thank you @crramirez I am also using zsh and after adding the following to my zshrc file all is working fine:
```
# Keypad
# 0 . Enter
bindkey -s "^[Op" "0"
bindkey -s "^[On" "."
bindkey -s "^[OM" "^M"
# 1 2 3
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
# 4 5 6
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
# 7 8 9
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
# + -  * /
bindkey -s "^[Ok" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"
```

**Comment by crramirez** [comment]
Hopefully they fix the issue before it goes out preview
