### ISSUE TITLE
xfce desktop  does not works

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Pengwin#787]
xfce desktop  does not works
- Installed xfce desktop following this instruction
   https://www.whitewaterfoundry.com/blog/2022/11/21/pengwin-november-2022-systemd-xfce
- Start the connection 
![xfce_desktop_not_work](https://github.com/WhitewaterFoundry/Pengwin/assets/64733228/0aba36d3-db89-4d2a-bb4c-b4ce45d9f495)

Remote desktop cannot connect with remote computer.
Please find attached image.

[Window Title]
Remote Desktop Connection

[Content]
Remote Desktop can't connect to the remote computer for one of these reasons:

1) Remote access to the server is not enabled
2) The remote computer is turned off
3) The remote computer is not available on the network

Make sure the remote computer is turned on and connected to the network, and that remote access is enabled.

[Expanded Information]
Error code: 0x204
Extended error code: 0x0
Timestamp (UTC): 06/15/24 03:02:41 PM

**Expected behavior**
The desktop run as should be.

**Basic Troubleshooting Checklist**

[ x] I have searched Google for the error message.
[ x] I have restarted WSL service: `wsl.exe --terminate WLinux` `wsl.exe --shutdown`.

Remote-Desktop: enabled
Re-install xfce desktop.

**Pengwin Version**
PENGWIN_VERSION="24.05.0"

**WSL general info**

WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.3737

Run `wslsys` in Pengwin.

Release Install Date: Wed Sep 21 12:14:41 CEST 2022
Branch: ni_release
Build: 22631
Full Build: 22621.1.amd64fre.ni_release.220506-1250
Display Scaling: 1
Locale (Windows): en_US
Theme (Windows): dark
Uptime (Windows): 0d 0h 43m
Version (WSL): 2
Uptime (WSL): 0d 0h 35m
Release: Pengwin
Kernel: Linux 5.15.153.1-microsoft-standard-WSL2
Packages: 1707
IPv4 Address: 172.24.47.245
System Type (Windows): Desktop
SystemD Status: enabled

OS:
Edition	Windows 11 Pro for Workstations
Version	23H2
Installed on	‎9/‎21/‎2022
OS build	22631.3737
Experience	Windows Feature Experience Pack 1000.22700.1009.0

**Comment by Jack31071973** [comment]
This fact also impacts code development because I was creating documentation with Sphinx and then switched to LaTeX-PDF. The documentation includes Draw.io diagrams for the HTML part, and standard PDF images for the LaTeX-PDF part. As a result, some packages used for importing Draw.io utilize X11 functionalities that are broken, causing the build to fail. Removing all xfce and restore WSLg solved the problem. Please when you got a time solve it.

**Comment by crramirez** [comment]
Hello @Jack31071973,

Let me check and go back to you. Thanks for reporting

**Comment by eloekset** [comment]
What's the status of this issue? Is there a workaround until the configuration tools get an update?

**Comment by Petzku12** [comment]
up

**Comment by Petzku12** [comment]
> I encountered the same issue. I have noticed that my current nameserver entry looks very different to that in the past: `nameserver 10.255.255.254`
> 
> When I connect to the ip of eth0 it works as good as before.

Thanks bierbo.

I noticed that nameserver change as well. I too connected to that eth0. I couldn't remember how to get eth0's ip address when wsl2 also has docker. But on the net I found help >` wsl -d WLinux hostname -I `. But now i have a clean WLinux installation and updated WSL .

**Comment by crramirez** [comment]
@bierbo good findings. In fact, what is happening is that in WSL 2.2.1 the DNS Tunneling was enabled by default. If you disable it via `.wslconfig` file, xfce will work as always. Now it add a new network interface for the tunnel and it confuses the script. To get a quick fix run:

`sudo sed -i "s/-v 127.0.0/eth/" /usr/local/bin/remote_desktop.sh`

I am patching pengwin-setup to fix the problem.

I apologize for the delay, many things are moving internally and this issue called in this storm. I realized it wasn't solved when you began talking about it.

Thanks for keep trying and your patience
