### ISSUE TITLE
wslu Error on Update

### ISSUE THREAD

**Issue by PeteSL** [WhitewaterFoundry/Pengwin#790]
Received the following when doing the update this morning:
```
Setting up wslu (4.1.3.d1725441364-1pengwin1) ...
Error on file "/usr/share/wslu/wslview.desktop": No such file or directory
dpkg: error processing package wslu (--configure):
 installed wslu package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 wslu
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Checked /usr/share/wslu and that file is not there.  This is in a WSLv1 installation.

**Comment by Trobeloo** [comment]
Same problem here with a new install.

**Comment by crramirez** [comment]
Hello,

Thanks a lot for reporting this issue.

Meanwhile we fix the problem, run

`sudo apt upgrade --allow-downgrades wslu=4.1.3.d1722478247-1pengwin1`

**Comment by crramirez** [comment]
https://github.com/wslutilities/wslu-debian-tools/pull/1 solution is ongoing

**Comment by crramirez** [comment]
The new package was uploaded and the issue fixed. Thanks for reporting it

**Comment by Trobeloo** [comment]
Problem solved with new package.
